# COINS 02 - OOF Runs And Data Manipulation

This notebook shows the data before final model training. It computes same-family OOF scores, applies Weighted Repair/CWMS, applies Boundary Fill/MSBS, then explicitly previews the final training data that is fed to `model.fit(...)`.

In [1]:
from __future__ import annotations

import os
import time
import warnings
from pathlib import Path
from typing import Any

warnings.filterwarnings("ignore")
os.environ["PYTHONWARNINGS"] = "ignore"

import numpy as np
import pandas as pd
from scipy.stats import norm, wilcoxon
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import average_precision_score
from sklearn.model_selection import StratifiedKFold, train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.svm import SVC

pd.set_option("display.max_columns", 160)
pd.set_option("display.max_rows", 260)
pd.options.mode.chained_assignment = None

ROOT = Path.cwd()
if not (ROOT / "data").exists() and ROOT.name == "data":
    ROOT = ROOT.parent
DATA_DIR = ROOT / "data"
RAW_RESULTS = ROOT / "docs" / "experiments" / "raw" / "full-benchmark-solution-v2.csv"
SMOKE = os.environ.get("COINS_SMOKE", "0") == "1"

DATA_FILES = {
    "pima": "pima.parquet", "credit-g": "credit-g.parquet", "yeast": "yeast.parquet",
    "ecoli": "ecoli.parquet", "phoneme": "phoneme.parquet", "breast_cancer": "breast_cancer.parquet",
    "ilpd": "ilpd.parquet", "blood": "blood.parquet", "haberman": "haberman.parquet",
    "ionosphere": "ionosphere.parquet", "vehicle_bus": "vehicle_bus.parquet", "glass_float": "glass_float.parquet",
    "abalone": "abalone.parquet", "spambase": "spambase.parquet", "kc1": "kc1.parquet",
}
MINORITY_TEXT = {
    "pima": "tested_positive", "credit-g": "bad", "yeast": "MIT", "ecoli": "im", "phoneme": "nasal",
    "breast_cancer": "malignant", "ilpd": "no_disease", "blood": "donated", "haberman": "died",
    "ionosphere": "bad", "vehicle_bus": "bus", "glass_float": "window_float", "abalone": "rings_gt_10",
    "spambase": "spam", "kc1": "defective",
}
SEEDS_FULL = [13, 17, 23, 29, 31, 37, 41, 43, 47, 53]
PROTOCOLS_FULL = {
    "hidden_minority_low": (0.10, 0.05),
    "hidden_minority_medium": (0.30, 0.10),
    "hidden_minority_high": (0.40, 0.20),
}
GOAL_MINORITY_RATIO = 0.15
BUDGET_RATIO = 0.10
DATA_NAMES = ["pima"] if SMOKE else list(DATA_FILES)
SEEDS = [13] if SMOKE else SEEDS_FULL
PROTOCOLS = {"hidden_minority_medium": PROTOCOLS_FULL["hidden_minority_medium"]} if SMOKE else PROTOCOLS_FULL
print("root", ROOT)
print("data_dir", DATA_DIR)
print("smoke", SMOKE)


def read_data(name: str) -> tuple[pd.DataFrame, np.ndarray, str]:
    df = pd.read_parquet(DATA_DIR / DATA_FILES[name])
    label_col = df.columns[-1]
    y = (df[label_col] == MINORITY_TEXT[name]).astype(int).to_numpy()
    X = df.drop(columns=[label_col])
    return X, y, label_col


def induce_ratio(X: pd.DataFrame, y: np.ndarray, goal_ratio: float, rng: np.random.Generator) -> tuple[pd.DataFrame, np.ndarray]:
    min_idx = np.where(y == 1)[0]
    maj_idx = np.where(y == 0)[0]
    if len(min_idx) / len(y) <= goal_ratio:
        return X.reset_index(drop=True), y.copy()
    keep_min_n = min(len(min_idx), max(2, int((goal_ratio / (1 - goal_ratio)) * len(maj_idx))))
    keep_min = rng.choice(min_idx, size=keep_min_n, replace=False)
    keep = np.concatenate([maj_idx, keep_min])
    rng.shuffle(keep)
    return X.iloc[keep].reset_index(drop=True), y[keep].copy()


def add_noise(y_clean: np.ndarray, min_to_maj: float, maj_to_min: float, rng: np.random.Generator) -> tuple[np.ndarray, np.ndarray]:
    y = y_clean.copy()
    mask = np.zeros(len(y), dtype=bool)
    for i, val in enumerate(y_clean):
        p = min_to_maj if val == 1 else maj_to_min
        if rng.random() < p:
            y[i] = 1 - y[i]
            mask[i] = True
    return y, mask


def preprocessor_for(X: pd.DataFrame) -> ColumnTransformer:
    cat = list(X.select_dtypes(include=["object", "category", "bool"]).columns)
    num = [c for c in X.columns if c not in cat]
    try:
        enc = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
    except TypeError:
        enc = OneHotEncoder(handle_unknown="ignore", sparse=False)
    return ColumnTransformer([
        ("num", Pipeline([("imp", SimpleImputer(strategy="median")), ("sc", StandardScaler())]), num),
        ("cat", Pipeline([("imp", SimpleImputer(strategy="most_frequent")), ("oh", enc)]), cat),
    ])


def split_data(name: str, seed: int, min_to_maj: float, maj_to_min: float) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, pd.DataFrame, list[str]]:
    rng = np.random.default_rng(seed)
    X_raw, y_raw, _label_col = read_data(name)
    X_tr_df, X_te_df, y_tr_clean, y_te = train_test_split(X_raw, y_raw, test_size=0.25, stratify=y_raw, random_state=seed)
    X_tr_df, y_tr_clean = induce_ratio(X_tr_df.reset_index(drop=True), y_tr_clean, GOAL_MINORITY_RATIO, rng)
    prep = preprocessor_for(X_tr_df)
    X_tr = prep.fit_transform(X_tr_df).astype(float)
    X_te = prep.transform(X_te_df.reset_index(drop=True)).astype(float)
    y_noisy, noisy_mask = add_noise(y_tr_clean, min_to_maj, maj_to_min, rng)
    try:
        feature_names = prep.get_feature_names_out().tolist()
    except Exception:
        feature_names = [f"feature_{i}" for i in range(X_tr.shape[1])]
    return X_tr, X_te, y_tr_clean, y_noisy, y_te, noisy_mask, X_tr_df, feature_names


def make_model(name: str, seed: int, balanced: bool = False) -> LogisticRegression | SVC:
    if name == "lr":
        return LogisticRegression(class_weight="balanced" if balanced else None, max_iter=1000, random_state=seed)
    if name == "svm":
        return SVC(kernel="rbf", probability=True, class_weight="balanced" if balanced else None, random_state=seed)
    raise ValueError(name)


def min_scores(model: LogisticRegression | SVC, X: np.ndarray) -> np.ndarray:
    return model.predict_proba(X)[:, list(model.classes_).index(1)]


def same_family_oof(X: np.ndarray, y: np.ndarray, model_name: str, seed: int) -> np.ndarray:
    out = np.full(len(y), np.nan)
    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=seed)
    for tr, va in cv.split(X, y):
        model = make_model(model_name, seed, balanced=True)
        model.fit(X[tr], y[tr])
        out[va] = min_scores(model, X[va])
    out[y == 1] = np.nan
    return out


def msbs(X: np.ndarray, y: np.ndarray, scores: np.ndarray, budget: int, seed: int) -> tuple[np.ndarray, np.ndarray, int]:
    rng = np.random.default_rng(seed)
    min_idx = np.where(y == 1)[0]
    maj_idx = np.where(y == 0)[0]
    if len(min_idx) == 0 or len(maj_idx) == 0 or budget <= 0:
        return X.copy(), y.copy(), 0
    vals = np.nan_to_num(scores[maj_idx], nan=0.0)
    probs = np.full(len(maj_idx), 1 / len(maj_idx)) if vals.sum() <= 0 else vals / vals.sum()
    synth = []
    for _ in range(budget):
        anchor = X[rng.choice(min_idx)]
        seed_point = X[rng.choice(maj_idx, p=probs)]
        synth.append(anchor + rng.random() * (seed_point - anchor))
    return np.vstack([X, np.asarray(synth)]), np.concatenate([y, np.ones(len(synth), dtype=int)]), len(synth)


def build_coins_training_data(X: np.ndarray, y_noisy: np.ndarray, scores: np.ndarray, budget: int, seed: int) -> dict[str, Any]:
    weights = np.ones(len(y_noisy))
    majority = y_noisy == 0
    weights[majority] = 1 - np.nan_to_num(scores[majority], nan=0.0)
    X_aug, y_aug, n_synth = msbs(X, y_noisy, scores, budget, seed)
    final_weights = np.concatenate([np.clip(weights, 0, 1), np.ones(n_synth)])
    row_stage = np.array(["original_weighted_repair"] * len(y_noisy) + ["synthetic_boundary_fill"] * n_synth)
    return {"X_aug": X_aug, "y_aug": y_aug, "weights": final_weights, "original_weights": weights, "row_stage": row_stage, "n_synthetic": n_synth}


def preview_frame(X: np.ndarray, y: np.ndarray, weights: np.ndarray, row_stage: np.ndarray, feature_names: list[str], dataset: str, model: str, seed: int, protocol: str, start: int = 0, n: int = 5) -> pd.DataFrame:
    end = min(start + n, len(y))
    cols = feature_names[: min(6, X.shape[1])]
    df = pd.DataFrame(X[start:end, : len(cols)], columns=cols)
    df.insert(0, "dataset", dataset)
    df.insert(1, "model", model)
    df.insert(2, "seed", seed)
    df.insert(3, "noise_protocol", protocol)
    df.insert(4, "row_index", np.arange(start, end))
    df.insert(5, "observed_label_for_training", y[start:end])
    df.insert(6, "sample_weight", weights[start:end])
    df.insert(7, "row_stage", row_stage[start:end])
    return df

root /home/than-minh/project/DSP
data_dir /home/than-minh/project/DSP/data
smoke False

## Noise Protocol Explanation

A noise protocol is controlled label corruption on training labels only. `hidden_minority_medium`, for example, flips 30% of true minority training labels into majority labels and 10% of true majority labels into minority labels. Test labels stay clean.

In [2]:
protocol_table = pd.DataFrame([
    {"noise_protocol": "hidden_minority_low", "minority_to_majority_flip_rate": 0.10, "majority_to_minority_flip_rate": 0.05},
    {"noise_protocol": "hidden_minority_medium", "minority_to_majority_flip_rate": 0.30, "majority_to_minority_flip_rate": 0.10},
    {"noise_protocol": "hidden_minority_high", "minority_to_majority_flip_rate": 0.40, "majority_to_minority_flip_rate": 0.20},
])
display(protocol_table)

,noise_protocol,minority_to_majority_flip_rate,majority_to_minority_flip_rate
0,hidden_minority_low,0.1,0.05
1,hidden_minority_medium,0.3,0.10
2,hidden_minority_high,0.4,0.20

## Full OOF Score Runs

OOF means each row is scored only by a model that did not train on that row. Same-family means LR uses balanced LR for scoring and SVM uses balanced SVM for scoring.

In [3]:
OOF_MODELS = ["lr", "svm"]
oof_cache = {}
oof_rows = []
combo_total = len(DATA_NAMES) * len(OOF_MODELS) * len(SEEDS) * len(PROTOCOLS)
start = time.time()
combo_i = 0
for dataset in DATA_NAMES:
    for model in OOF_MODELS:
        for seed in SEEDS:
            for protocol, (mn, mj) in PROTOCOLS.items():
                combo_i += 1
                if combo_i <= 5 or combo_i % 100 == 0 or combo_i == combo_total:
                    print(f"[OOF {combo_i}/{combo_total}] {dataset} {model} seed={seed} {protocol}")
                X, _X_te, y_clean, y_noisy, _y_te, mask, _X_df, _feature_names = split_data(dataset, seed, mn, mj)
                scores = same_family_oof(X, y_noisy, model, seed)
                oof_cache[(dataset, model, seed, protocol)] = scores
                observed_majority = y_noisy == 0
                hidden_minority = (y_clean == 1) & observed_majority
                clean_majority = (y_clean == 0) & observed_majority
                target = hidden_minority[observed_majority].astype(int)
                vals = np.nan_to_num(scores[observed_majority], nan=0.0)
                ap = np.nan if target.sum() == 0 or target.sum() == len(target) else float(average_precision_score(target, vals))
                hidden_mean = float(np.nanmean(scores[hidden_minority])) if hidden_minority.any() else np.nan
                clean_mean = float(np.nanmean(scores[clean_majority])) if clean_majority.any() else np.nan
                oof_rows.append({
                    "dataset": dataset,
                    "model": model,
                    "seed": seed,
                    "noise_protocol": protocol,
                    "train_rows": len(y_noisy),
                    "observed_majority_rows": int(observed_majority.sum()),
                    "observed_minority_rows": int((y_noisy == 1).sum()),
                    "hidden_minority_rows": int(hidden_minority.sum()),
                    "true_noise_rate": float(mask.mean()),
                    "majority_score_mean": float(np.nanmean(scores[observed_majority])),
                    "hidden_minority_score_mean": hidden_mean,
                    "clean_majority_score_mean": clean_mean,
                    "score_gap": hidden_mean - clean_mean if np.isfinite(hidden_mean) and np.isfinite(clean_mean) else np.nan,
                    "hidden_minority_ap": ap,
                })
oof_table = pd.DataFrame(oof_rows)
print("OOF rows", len(oof_table), "minutes", round((time.time() - start) / 60, 2))
display(oof_table.head(20))

[OOF 1/900] pima lr seed=13 hidden_minority_low
[OOF 2/900] pima lr seed=13 hidden_minority_medium
[OOF 3/900] pima lr seed=13 hidden_minority_high
[OOF 4/900] pima lr seed=17 hidden_minority_low
[OOF 5/900] pima lr seed=17 hidden_minority_medium

[OOF 100/900] credit-g svm seed=29 hidden_minority_low

[OOF 200/900] ecoli lr seed=41 hidden_minority_medium

[OOF 300/900] phoneme svm seed=53 hidden_minority_high

[OOF 400/900] ilpd svm seed=29 hidden_minority_low

[OOF 500/900] haberman lr seed=41 hidden_minority_medium

[OOF 600/900] ionosphere svm seed=53 hidden_minority_high

[OOF 700/900] glass_float svm seed=29 hidden_minority_low

[OOF 800/900] spambase lr seed=41 hidden_minority_medium

[OOF 900/900] kc1 svm seed=53 hidden_minority_high

OOF rows 900 minutes 4.53

,dataset,model,seed,noise_protocol,train_rows,observed_majority_rows,observed_minority_rows,hidden_minority_rows,true_noise_rate,majority_score_mean,hidden_minority_score_mean,clean_majority_score_mean,score_gap,hidden_minority_ap
0,pima,lr,13,hidden_minority_low,441,361,80,9,0.072562,0.434049,0.671954,0.427966,0.243987,0.299003
1,pima,lr,13,hidden_minority_medium,441,355,86,20,0.136054,0.443601,0.606101,0.433900,0.172201,0.243617
2,pima,lr,13,hidden_minority_high,441,326,115,26,0.229025,0.490764,0.549048,0.485712,0.063335,0.244196
3,pima,lr,17,hidden_minority_low,441,366,75,5,0.043084,0.417723,0.683501,0.414042,0.269459,0.248102
4,pima,lr,17,hidden_minority_medium,441,357,84,15,0.108844,0.459733,0.632909,0.452138,0.180771,0.229675
5,pima,lr,17,hidden_minority_high,441,319,122,25,0.240363,0.487500,0.578301,0.479778,0.098523,0.217560
6,pima,lr,23,hidden_minority_low,441,366,75,5,0.043084,0.415379,0.562093,0.413347,0.148746,0.044150
7,pima,lr,23,hidden_minority_medium,441,352,89,15,0.120181,0.457508,0.592408,0.451503,0.140905,0.120571
8,pima,lr,23,hidden_minority_high,441,325,116,24,0.222222,0.489491,0.552767,0.484445,0.068322,0.223410
9,pima,lr,29,hidden_minority_low,441,369,72,9,0.054422,0.351702,0.568588,0.346280,0.222308,0.081805
10,pima,lr,29,hidden_minority_medium,441,366,75,22,0.120181,0.421008,0.620491,0.408250,0.212241,0.216163
11,pima,lr,29,hidden_minority_high,441,335,106,27,0.213152,0.481133,0.582966,0.472206,0.110760,0.216726
12,pima,lr,31,hidden_minority_low,441,368,73,5,0.038549,0.348752,0.702577,0.343878,0.358699,0.142132
13,pima,lr,31,hidden_minority_medium,441,355,86,19,0.131519,0.449228,0.629655,0.439025,0.190630,0.313721
14,pima,lr,31,hidden_minority_high,441,323,118,25,0.231293,0.477578,0.603991,0.466973,0.137018,0.335306
15,pima,lr,37,hidden_minority_low,441,354,87,2,0.056689,0.385501,0.941822,0.382340,0.559482,0.750000
16,pima,lr,37,hidden_minority_medium,441,361,80,20,0.122449,0.452060,0.644590,0.440768,0.203822,0.394952
17,pima,lr,37,hidden_minority_high,441,329,112,28,0.231293,0.497641,0.567513,0.491141,0.076371,0.295400
18,pima,lr,41,hidden_minority_low,441,366,75,9,0.061224,0.447078,0.624253,0.442611,0.181642,0.186314
19,pima,lr,41,hidden_minority_medium,441,363,78,21,0.122449,0.472227,0.593391,0.464788,0.128604,0.188362

## OOF Result Tables

In [4]:
display(oof_table.groupby(["model", "noise_protocol"])[["hidden_minority_rows", "majority_score_mean", "hidden_minority_score_mean", "clean_majority_score_mean", "score_gap", "hidden_minority_ap"]].mean().reset_index())
display(oof_table.groupby(["dataset", "model"])[["score_gap", "hidden_minority_ap", "true_noise_rate"]].mean().reset_index().sort_values(["model", "dataset"]))

,model,noise_protocol,hidden_minority_rows,majority_score_mean,hidden_minority_score_mean,clean_majority_score_mean,score_gap,hidden_minority_ap
0,lr,hidden_minority_high,52.580000,0.469391,0.588150,0.459482,0.128668,0.323167
1,lr,hidden_minority_low,12.886667,0.364602,0.678763,0.359451,0.318582,0.276328
2,lr,hidden_minority_medium,39.100000,0.425017,0.628001,0.413728,0.214273,0.330423
3,svm,hidden_minority_high,52.580000,0.252832,0.308838,0.248252,0.060586,0.278637
4,svm,hidden_minority_low,12.886667,0.145820,0.406597,0.141563,0.265205,0.280308
5,svm,hidden_minority_medium,39.100000,0.178053,0.315379,0.170562,0.144817,0.334353

          dataset model  score_gap  hidden_minority_ap  true_noise_rate
0         abalone    lr   0.191104            0.257909         0.137153
2           blood    lr   0.085214            0.163191         0.138419
4   breast_cancer    lr   0.497621            0.761593         0.138535
6        credit-g    lr   0.126297            0.109079         0.134954
8           ecoli    lr   0.332783            0.506121         0.130994
10    glass_float    lr   0.116273            0.106189         0.135433
12       haberman    lr   0.058295            0.127941         0.131980
14           ilpd    lr   0.080801            0.090787         0.138601
16     ionosphere    lr   0.344099            0.543658         0.132492
18            kc1    lr   0.153101            0.204774         0.138020
20        phoneme    lr   0.149011            0.178836         0.139138
22           pima    lr   0.174825            0.236718         0.134694
24       spambase    lr   0.362795            0.440721         0.139715
26    vehicle_bus    lr   0.422383            0.668879         0.136703
28          yeast    lr   0.192173            0.253473         0.137172
1         abalone   svm   0.105715            0.180728         0.137153
3           blood   svm   0.029890            0.109717         0.138419
5   breast_cancer   svm   0.396266            0.800245         0.138535
7        credit-g   svm   0.042287            0.108558         0.134954
9           ecoli   svm   0.229237            0.397536         0.130994
11    glass_float   svm   0.052751            0.165110         0.135433
13       haberman   svm   0.007854            0.083548         0.131980
15           ilpd   svm   0.019595            0.085980         0.138601
17     ionosphere   svm   0.285646            0.469423         0.132492
19            kc1   svm   0.078970            0.144521         0.138020
21        phoneme   svm   0.171294            0.283267         0.139138
23           pima   svm   0.056125            0.116182         0.134694
25       spambase   svm   0.312553            0.503529         0.139715
27    vehicle_bus   svm   0.383143            0.714391         0.136703
29          yeast   svm   0.158455            0.299729         0.137172

## Weighted Repair And Boundary Fill Checkpoints

For each dataset, this table shows row counts before COINS, after Weighted Repair/CWMS, and after Boundary Fill/MSBS. The final checkpoint is the training matrix used by COINS.

In [5]:
checkpoint_rows = []
preview_before = []
preview_weighted = []
preview_final_original_head = []
preview_final_synthetic_head = []
for dataset in DATA_NAMES:
    for model in ["lr", "svm"]:
        seed = SEEDS_FULL[0]
        protocol = "hidden_minority_medium"
        mn, mj = PROTOCOLS_FULL[protocol]
        X, _X_te, y_clean, y_noisy, _y_te, mask, _X_df, feature_names = split_data(dataset, seed, mn, mj)
        scores = oof_cache.get((dataset, model, seed, protocol))
        if scores is None:
            scores = same_family_oof(X, y_noisy, model, seed)
            oof_cache[(dataset, model, seed, protocol)] = scores
        budget = max(1, int(round(BUDGET_RATIO * len(y_noisy))))
        coins_data = build_coins_training_data(X, y_noisy, scores, budget, seed)
        observed_majority = y_noisy == 0
        threshold = np.nanquantile(scores[observed_majority], 0.80)
        suspicious = observed_majority & (np.nan_to_num(scores, nan=0.0) >= threshold)
        checkpoint_rows.extend([
            {"dataset": dataset, "model": model, "checkpoint": "before_coins", "rows": len(y_noisy), "minority_rows": int((y_noisy == 1).sum()), "majority_rows": int((y_noisy == 0).sum()), "synthetic_rows": 0, "mean_weight": 1.0, "fit_ready": False},
            {"dataset": dataset, "model": model, "checkpoint": "after_weighted_repair_cwms", "rows": len(y_noisy), "minority_rows": int((y_noisy == 1).sum()), "majority_rows": int((y_noisy == 0).sum()), "synthetic_rows": 0, "mean_weight": float(coins_data["original_weights"].mean()), "fit_ready": False},
            {"dataset": dataset, "model": model, "checkpoint": "after_boundary_fill_msbs_final_training_data", "rows": len(coins_data["y_aug"]), "minority_rows": int((coins_data["y_aug"] == 1).sum()), "majority_rows": int((coins_data["y_aug"] == 0).sum()), "synthetic_rows": int(coins_data["n_synthetic"]), "mean_weight": float(coins_data["weights"].mean()), "fit_ready": True},
        ])
        before_stage = np.array(["before_coins"] * len(y_noisy))
        weighted_stage = np.array(["weighted_repair_cwms"] * len(y_noisy))
        preview_before.append(preview_frame(X, y_noisy, np.ones(len(y_noisy)), before_stage, feature_names, dataset, model, seed, protocol))
        preview_weighted.append(preview_frame(X, y_noisy, coins_data["original_weights"], weighted_stage, feature_names, dataset, model, seed, protocol))
        preview_final_original_head.append(preview_frame(coins_data["X_aug"], coins_data["y_aug"], coins_data["weights"], coins_data["row_stage"], feature_names, dataset, model, seed, protocol, start=0))
        synth_start = len(y_noisy)
        preview_final_synthetic_head.append(preview_frame(coins_data["X_aug"], coins_data["y_aug"], coins_data["weights"], coins_data["row_stage"], feature_names, dataset, model, seed, protocol, start=synth_start))

checkpoint_table = pd.DataFrame(checkpoint_rows)
display(checkpoint_table)

,dataset,model,checkpoint,rows,minority_rows,majority_rows,synthetic_rows,mean_weight,fit_ready
0,pima,lr,before_coins,441,86,355,0,1.000000,False
1,pima,lr,after_weighted_repair_cwms,441,86,355,0,0.642906,False
2,pima,lr,after_boundary_fill_msbs_final_training_data,485,130,355,44,0.675302,True
3,pima,svm,before_coins,441,86,355,0,1.000000,False
4,pima,svm,after_weighted_repair_cwms,441,86,355,0,0.844398,False
5,pima,svm,after_boundary_fill_msbs_final_training_data,485,130,355,44,0.858515,True
6,credit-g,lr,before_coins,617,120,497,0,1.000000,False
7,credit-g,lr,after_weighted_repair_cwms,617,120,497,0,0.650922,False
8,credit-g,lr,after_boundary_fill_msbs_final_training_data,679,182,497,62,0.682797,True
9,credit-g,svm,before_coins,617,120,497,0,1.000000,False
10,credit-g,svm,after_weighted_repair_cwms,617,120,497,0,0.846800,False
11,credit-g,svm,after_boundary_fill_msbs_final_training_data,679,182,497,62,0.860789,True
12,yeast,lr,before_coins,1094,214,880,0,1.000000,False
13,yeast,lr,after_weighted_repair_cwms,1094,214,880,0,0.641494,False
14,yeast,lr,after_boundary_fill_msbs_final_training_data,1203,323,880,109,0.673977,True
15,yeast,svm,before_coins,1094,214,880,0,1.000000,False
16,yeast,svm,after_weighted_repair_cwms,1094,214,880,0,0.853737,False
17,yeast,svm,after_boundary_fill_msbs_final_training_data,1203,323,880,109,0.866989,True
18,ecoli,lr,before_coins,228,46,182,0,1.000000,False
19,ecoli,lr,after_weighted_repair_cwms,228,46,182,0,0.647360,False
20,ecoli,lr,after_boundary_fill_msbs_final_training_data,251,69,182,23,0.679674,True
21,ecoli,svm,before_coins,228,46,182,0,1.000000,False
22,ecoli,svm,after_weighted_repair_cwms,228,46,182,0,0.848305,False
23,ecoli,svm,after_boundary_fill_msbs_final_training_data,251,69,182,23,0.862206,True
24,phoneme,lr,before_coins,3368,602,2766,0,1.000000,False
25,phoneme,lr,after_weighted_repair_cwms,3368,602,2766,0,0.629121,False
26,phoneme,lr,after_boundary_fill_msbs_final_training_data,3705,939,2766,337,0.662856,True
27,phoneme,svm,before_coins,3368,602,2766,0,1.000000,False
28,phoneme,svm,after_weighted_repair_cwms,3368,602,2766,0,0.867061,False
29,phoneme,svm,after_boundary_fill_msbs_final_training_data,3705,939,2766,337,0.879153,True
30,breast_cancer,lr,before_coins,314,67,247,0,1.000000,False
31,breast_cancer,lr,after_weighted_repair_cwms,314,67,247,0,0.736091,False
32,breast_cancer,lr,after_boundary_fill_msbs_final_training_data,345,98,247,31,0.759804,True
33,breast_cancer,svm,before_coins,314,67,247,0,1.000000,False
34,breast_cancer,svm,after_weighted_repair_cwms,314,67,247,0,0.865942,False
35,breast_cancer,svm,after_boundary_fill_msbs_final_training_data,345,98,247,31,0.877988,True
36,ilpd,lr,before_coins,367,77,290,0,1.000000,False
37,ilpd,lr,after_weighted_repair_cwms,367,77,290,0,0.624868,False
38,ilpd,lr,after_boundary_fill_msbs_final_training_data,404,114,290,37,0.659224,True
39,ilpd,svm,before_coins,367,77,290,0,1.000000,False
40,ilpd,svm,after_weighted_repair_cwms,367,77,290,0,0.834151,False
41,ilpd,svm,after_boundary_fill_msbs_final_training_data,404,114,290,37,0.849340,True
42,blood,lr,before_coins,502,101,401,0,1.000000,False
43,blood,lr,after_weighted_repair_cwms,502,101,401,0,0.615361,False
44,blood,lr,after_boundary_fill_msbs_final_training_data,552,151,401,50,0.650201,True
45,blood,svm,before_coins,502,101,401,0,1.000000,False
46,blood,svm,after_weighted_repair_cwms,502,101,401,0,0.842277,False
47,blood,svm,after_boundary_fill_msbs_final_training_data,552,151,401,50,0.856564,True
48,haberman,lr,before_coins,197,36,161,0,1.000000,False
49,haberman,lr,after_weighted_repair_cwms,197,36,161,0,0.629868,False
50,haberman,lr,after_boundary_fill_msbs_final_training_data,217,56,161,20,0.663982,True
51,haberman,svm,before_coins,197,36,161,0,1.000000,False
52,haberman,svm,after_weighted_repair_cwms,197,36,161,0,0.843816,False
53,haberman,svm,after_boundary_fill_msbs_final_training_data,217,56,161,20,0.858211,True
54,ionosphere,lr,before_coins,198,30,168,0,1.000000,False
55,ionosphere,lr,after_weighted_repair_cwms,198,30,168,0,0.724769,False
56,ionosphere,lr,after_boundary_fill_msbs_final_training_data,218,50,168,20,0.750019,True
57,ionosphere,svm,before_coins,198,30,168,0,1.000000,False
58,ionosphere,svm,after_weighted_repair_cwms,198,30,168,0,0.868547,False
59,ionosphere,svm,after_boundary_fill_msbs_final_training_data,218,50,168,20,0.880607,True
60,vehicle_bus,lr,before_coins,554,115,439,0,1.000000,False
61,vehicle_bus,lr,after_weighted_repair_cwms,554,115,439,0,0.677627,False
62,vehicle_bus,lr,after_boundary_fill_msbs_final_training_data,609,170,439,55,0.706741,True
63,vehicle_bus,svm,before_coins,554,115,439,0,1.000000,False
64,vehicle_bus,svm,after_weighted_repair_cwms,554,115,439,0,0.854461,False
65,vehicle_bus,svm,after_boundary_fill_msbs_final_training_data,609,170,439,55,0.867605,True
66,glass_float,lr,before_coins,127,25,102,0,1.000000,False
67,glass_float,lr,after_weighted_repair_cwms,127,25,102,0,0.660369,False
68,glass_float,lr,after_boundary_fill_msbs_final_training_data,140,38,102,13,0.691906,True
69,glass_float,svm,before_coins,127,25,102,0,1.000000,False
70,glass_float,svm,after_weighted_repair_cwms,127,25,102,0,0.838835,False
71,glass_float,svm,after_boundary_fill_msbs_final_training_data,140,38,102,13,0.853800,True
72,abalone,lr,before_coins,1152,222,930,0,1.000000,False
73,abalone,lr,after_weighted_repair_cwms,1152,222,930,0,0.639888,False
74,abalone,lr,after_boundary_fill_msbs_final_training_data,1267,337,930,115,0.672574,True
75,abalone,svm,before_coins,1152,222,930,0,1.000000,False
76,abalone,svm,after_weighted_repair_cwms,1152,222,930,0,0.852441,False
77,abalone,svm,after_boundary_fill_msbs_final_training_data,1267,337,930,115,0.865835,True
78,spambase,lr,before_coins,2460,451,2009,0,1.000000,False
79,spambase,lr,after_weighted_repair_cwms,2460,451,2009,0,0.679829,False
80,spambase,lr,after_boundary_fill_msbs_final_training_data,2706,697,2009,246,0.708936,True
81,spambase,svm,before_coins,2460,451,2009,0,1.000000,False
82,spambase,svm,after_weighted_repair_cwms,2460,451,2009,0,0.873102,False
83,spambase,svm,after_boundary_fill_msbs_final_training_data,2706,697,2009,246,0.884639,True
84,kc1,lr,before_coins,1572,292,1280,0,1.000000,False
85,kc1,lr,after_weighted_repair_cwms,1572,292,1280,0,0.616673,False
86,kc1,lr,after_boundary_fill_msbs_final_training_data,1729,449,1280,157,0.651480,True
87,kc1,svm,before_coins,1572,292,1280,0,1.000000,False
88,kc1,svm,after_weighted_repair_cwms,1572,292,1280,0,0.851483,False
89,kc1,svm,after_boundary_fill_msbs_final_training_data,1729,449,1280,157,0.864969,True

## Before COINS `head(5)` For Each Dataset And Model

In [6]:
for df in preview_before:
    print("DATASET", df["dataset"].iloc[0], "MODEL", df["model"].iloc[0])
    display(df.head(5))

DATASET pima MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__preg,num__plas,num__pres,num__skin,num__insu,num__mass
0,pima,lr,13,hidden_minority_medium,0,0,1.0,before_coins,0.501533,0.659328,0.637019,-1.273588,-0.698213,-0.583918
1,pima,lr,13,hidden_minority_medium,1,0,1.0,before_coins,0.823477,0.351315,0.201982,1.677644,1.709804,0.355337
2,pima,lr,13,hidden_minority_medium,2,0,1.0,before_coins,0.501533,1.172681,0.365121,-1.273588,-0.698213,-0.155728
3,pima,lr,13,hidden_minority_medium,3,0,1.0,before_coins,-1.108190,0.043303,0.637019,0.956232,2.285634,1.819470
4,pima,lr,13,hidden_minority_medium,4,0,1.0,before_coins,-1.108190,1.172681,0.908918,2.267891,-0.698213,1.626094

DATASET pima MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__preg,num__plas,num__pres,num__skin,num__insu,num__mass
0,pima,svm,13,hidden_minority_medium,0,0,1.0,before_coins,0.501533,0.659328,0.637019,-1.273588,-0.698213,-0.583918
1,pima,svm,13,hidden_minority_medium,1,0,1.0,before_coins,0.823477,0.351315,0.201982,1.677644,1.709804,0.355337
2,pima,svm,13,hidden_minority_medium,2,0,1.0,before_coins,0.501533,1.172681,0.365121,-1.273588,-0.698213,-0.155728
3,pima,svm,13,hidden_minority_medium,3,0,1.0,before_coins,-1.108190,0.043303,0.637019,0.956232,2.285634,1.819470
4,pima,svm,13,hidden_minority_medium,4,0,1.0,before_coins,-1.108190,1.172681,0.908918,2.267891,-0.698213,1.626094

DATASET credit-g MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__duration,num__credit_amount,num__installment_commitment,num__residence_since,num__age,num__existing_credits
0,credit-g,lr,13,hidden_minority_medium,0,0,1.0,before_coins,0.364387,-0.089388,0.058790,1.002163,1.297566,-0.715642
1,credit-g,lr,13,hidden_minority_medium,1,0,1.0,before_coins,0.364387,-0.082600,-0.825926,-1.754157,-0.164635,-0.715642
2,credit-g,lr,13,hidden_minority_medium,2,0,1.0,before_coins,-0.777311,-0.681467,0.943505,1.002163,0.351436,0.963259
3,credit-g,lr,13,hidden_minority_medium,3,0,1.0,before_coins,0.100918,0.177236,-1.710641,1.002163,-0.852730,-0.715642
4,credit-g,lr,13,hidden_minority_medium,4,0,1.0,before_coins,-0.426019,-1.032189,0.943505,1.002163,-1.110766,-0.715642

DATASET credit-g MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__duration,num__credit_amount,num__installment_commitment,num__residence_since,num__age,num__existing_credits
0,credit-g,svm,13,hidden_minority_medium,0,0,1.0,before_coins,0.364387,-0.089388,0.058790,1.002163,1.297566,-0.715642
1,credit-g,svm,13,hidden_minority_medium,1,0,1.0,before_coins,0.364387,-0.082600,-0.825926,-1.754157,-0.164635,-0.715642
2,credit-g,svm,13,hidden_minority_medium,2,0,1.0,before_coins,-0.777311,-0.681467,0.943505,1.002163,0.351436,0.963259
3,credit-g,svm,13,hidden_minority_medium,3,0,1.0,before_coins,0.100918,0.177236,-1.710641,1.002163,-0.852730,-0.715642
4,credit-g,svm,13,hidden_minority_medium,4,0,1.0,before_coins,-0.426019,-1.032189,0.943505,1.002163,-1.110766,-0.715642

DATASET yeast MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__mcg,num__gvh,num__alm,num__mit,num__erl,num__pox
0,yeast,lr,13,hidden_minority_medium,0,1,1.0,before_coins,0.856331,0.655157,0.236387,-0.796109,-0.096047,-0.094038
1,yeast,lr,13,hidden_minority_medium,1,0,1.0,before_coins,1.070055,0.655157,0.351579,-0.351031,-0.096047,-0.094038
2,yeast,lr,13,hidden_minority_medium,2,0,1.0,before_coins,0.713848,1.137108,0.697156,0.761663,-0.096047,-0.094038
3,yeast,lr,13,hidden_minority_medium,3,0,1.0,before_coins,-0.354775,0.574832,-1.376307,0.168226,-0.096047,-0.094038
4,yeast,lr,13,hidden_minority_medium,4,0,1.0,before_coins,0.785089,-0.951347,0.812349,0.761663,-0.096047,-0.094038

DATASET yeast MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__mcg,num__gvh,num__alm,num__mit,num__erl,num__pox
0,yeast,svm,13,hidden_minority_medium,0,1,1.0,before_coins,0.856331,0.655157,0.236387,-0.796109,-0.096047,-0.094038
1,yeast,svm,13,hidden_minority_medium,1,0,1.0,before_coins,1.070055,0.655157,0.351579,-0.351031,-0.096047,-0.094038
2,yeast,svm,13,hidden_minority_medium,2,0,1.0,before_coins,0.713848,1.137108,0.697156,0.761663,-0.096047,-0.094038
3,yeast,svm,13,hidden_minority_medium,3,0,1.0,before_coins,-0.354775,0.574832,-1.376307,0.168226,-0.096047,-0.094038
4,yeast,svm,13,hidden_minority_medium,4,0,1.0,before_coins,0.785089,-0.951347,0.812349,0.761663,-0.096047,-0.094038

DATASET ecoli MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__mcg,num__gvh,num__lip,num__chg,num__aac,num__alm1
0,ecoli,lr,13,hidden_minority_medium,0,1,1.0,before_coins,-0.849296,-0.062081,-0.164399,-0.066372,0.734146,1.900295
1,ecoli,lr,13,hidden_minority_medium,1,1,1.0,before_coins,-0.422425,-1.723413,-0.164399,-0.066372,0.647373,-0.985831
2,ecoli,lr,13,hidden_minority_medium,2,0,1.0,before_coins,-0.529143,-1.391147,-0.164399,-0.066372,-0.654223,-0.587745
3,ecoli,lr,13,hidden_minority_medium,3,0,1.0,before_coins,-0.155630,-0.261441,-0.164399,-0.066372,1.081238,1.352926
4,ecoli,lr,13,hidden_minority_medium,4,0,1.0,before_coins,0.004447,1.067624,-0.164399,-0.066372,-1.608727,2.248621

DATASET ecoli MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__mcg,num__gvh,num__lip,num__chg,num__aac,num__alm1
0,ecoli,svm,13,hidden_minority_medium,0,1,1.0,before_coins,-0.849296,-0.062081,-0.164399,-0.066372,0.734146,1.900295
1,ecoli,svm,13,hidden_minority_medium,1,1,1.0,before_coins,-0.422425,-1.723413,-0.164399,-0.066372,0.647373,-0.985831
2,ecoli,svm,13,hidden_minority_medium,2,0,1.0,before_coins,-0.529143,-1.391147,-0.164399,-0.066372,-0.654223,-0.587745
3,ecoli,svm,13,hidden_minority_medium,3,0,1.0,before_coins,-0.155630,-0.261441,-0.164399,-0.066372,1.081238,1.352926
4,ecoli,svm,13,hidden_minority_medium,4,0,1.0,before_coins,0.004447,1.067624,-0.164399,-0.066372,-1.608727,2.248621

DATASET phoneme MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__V1,num__V2,num__V3,num__V4,num__V5
0,phoneme,lr,13,hidden_minority_medium,0,0,1.0,before_coins,-0.717583,-0.353237,-0.312972,0.172724,0.990362
1,phoneme,lr,13,hidden_minority_medium,1,0,1.0,before_coins,-0.564656,1.023772,0.955050,0.615022,-0.755116
2,phoneme,lr,13,hidden_minority_medium,2,0,1.0,before_coins,-0.635559,-0.945903,1.185795,0.726156,2.148179
3,phoneme,lr,13,hidden_minority_medium,3,0,1.0,before_coins,0.303368,-0.631372,-0.867714,-0.297395,-0.196041
4,phoneme,lr,13,hidden_minority_medium,4,0,1.0,before_coins,-0.842904,-0.607324,1.555115,-1.554757,-0.096784

DATASET phoneme MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__V1,num__V2,num__V3,num__V4,num__V5
0,phoneme,svm,13,hidden_minority_medium,0,0,1.0,before_coins,-0.717583,-0.353237,-0.312972,0.172724,0.990362
1,phoneme,svm,13,hidden_minority_medium,1,0,1.0,before_coins,-0.564656,1.023772,0.955050,0.615022,-0.755116
2,phoneme,svm,13,hidden_minority_medium,2,0,1.0,before_coins,-0.635559,-0.945903,1.185795,0.726156,2.148179
3,phoneme,svm,13,hidden_minority_medium,3,0,1.0,before_coins,0.303368,-0.631372,-0.867714,-0.297395,-0.196041
4,phoneme,svm,13,hidden_minority_medium,4,0,1.0,before_coins,-0.842904,-0.607324,1.555115,-1.554757,-0.096784

DATASET breast_cancer MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__V1,num__V2,num__V3,num__V4,num__V5,num__V6
0,breast_cancer,lr,13,hidden_minority_medium,0,0,1.0,before_coins,0.657463,0.374065,0.620129,0.497735,0.155067,-0.130567
1,breast_cancer,lr,13,hidden_minority_medium,1,0,1.0,before_coins,2.319486,0.617415,2.325630,2.404353,1.126951,1.629118
2,breast_cancer,lr,13,hidden_minority_medium,2,0,1.0,before_coins,1.336754,0.198572,1.238298,1.225544,-1.361156,-0.388823
3,breast_cancer,lr,13,hidden_minority_medium,3,0,1.0,before_coins,-0.932149,-0.475322,-0.903646,-0.817288,-0.347509,-0.194786
4,breast_cancer,lr,13,hidden_minority_medium,4,0,1.0,before_coins,-1.458341,-0.414484,-1.436238,-1.133171,0.723474,-0.341637

DATASET breast_cancer MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__V1,num__V2,num__V3,num__V4,num__V5,num__V6
0,breast_cancer,svm,13,hidden_minority_medium,0,0,1.0,before_coins,0.657463,0.374065,0.620129,0.497735,0.155067,-0.130567
1,breast_cancer,svm,13,hidden_minority_medium,1,0,1.0,before_coins,2.319486,0.617415,2.325630,2.404353,1.126951,1.629118
2,breast_cancer,svm,13,hidden_minority_medium,2,0,1.0,before_coins,1.336754,0.198572,1.238298,1.225544,-1.361156,-0.388823
3,breast_cancer,svm,13,hidden_minority_medium,3,0,1.0,before_coins,-0.932149,-0.475322,-0.903646,-0.817288,-0.347509,-0.194786
4,breast_cancer,svm,13,hidden_minority_medium,4,0,1.0,before_coins,-1.458341,-0.414484,-1.436238,-1.133171,0.723474,-0.341637

DATASET ilpd MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__V1,num__V3,num__V4,num__V5,num__V6,num__V7
0,ilpd,lr,13,hidden_minority_medium,0,1,1.0,before_coins,-1.424899,-0.167327,-0.252116,-0.575074,-0.062032,-0.024316
1,ilpd,lr,13,hidden_minority_medium,1,1,1.0,before_coins,0.926496,0.686179,0.766900,0.036633,1.544965,2.042331
2,ilpd,lr,13,hidden_minority_medium,2,0,1.0,before_coins,-0.496717,-0.297523,-0.320051,-0.641564,-0.159426,-0.221548
3,ilpd,lr,13,hidden_minority_medium,3,0,1.0,before_coins,-0.744232,-0.254124,-0.354018,-0.375604,-0.217862,-0.278717
4,ilpd,lr,13,hidden_minority_medium,4,1,1.0,before_coins,-0.001686,-0.210726,-0.218149,-0.539612,-0.300647,-0.244415

DATASET ilpd MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__V1,num__V3,num__V4,num__V5,num__V6,num__V7
0,ilpd,svm,13,hidden_minority_medium,0,1,1.0,before_coins,-1.424899,-0.167327,-0.252116,-0.575074,-0.062032,-0.024316
1,ilpd,svm,13,hidden_minority_medium,1,1,1.0,before_coins,0.926496,0.686179,0.766900,0.036633,1.544965,2.042331
2,ilpd,svm,13,hidden_minority_medium,2,0,1.0,before_coins,-0.496717,-0.297523,-0.320051,-0.641564,-0.159426,-0.221548
3,ilpd,svm,13,hidden_minority_medium,3,0,1.0,before_coins,-0.744232,-0.254124,-0.354018,-0.375604,-0.217862,-0.278717
4,ilpd,svm,13,hidden_minority_medium,4,1,1.0,before_coins,-0.001686,-0.210726,-0.218149,-0.539612,-0.300647,-0.244415

DATASET blood MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__V1,num__V2,num__V3,num__V4
0,blood,lr,13,hidden_minority_medium,0,0,1.0,before_coins,-0.728132,2.071229,2.071229,1.515775
1,blood,lr,13,hidden_minority_medium,1,0,1.0,before_coins,0.760757,-0.801028,-0.801028,-0.731894
2,blood,lr,13,hidden_minority_medium,2,0,1.0,before_coins,-0.976280,-0.226576,-0.226576,-0.731894
3,blood,lr,13,hidden_minority_medium,3,0,1.0,before_coins,0.388535,-0.226576,-0.226576,-0.523776
4,blood,lr,13,hidden_minority_medium,4,0,1.0,before_coins,0.512609,1.496778,1.496778,0.974670

DATASET blood MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__V1,num__V2,num__V3,num__V4
0,blood,svm,13,hidden_minority_medium,0,0,1.0,before_coins,-0.728132,2.071229,2.071229,1.515775
1,blood,svm,13,hidden_minority_medium,1,0,1.0,before_coins,0.760757,-0.801028,-0.801028,-0.731894
2,blood,svm,13,hidden_minority_medium,2,0,1.0,before_coins,-0.976280,-0.226576,-0.226576,-0.731894
3,blood,svm,13,hidden_minority_medium,3,0,1.0,before_coins,0.388535,-0.226576,-0.226576,-0.523776
4,blood,svm,13,hidden_minority_medium,4,0,1.0,before_coins,0.512609,1.496778,1.496778,0.974670

DATASET haberman MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__Age_of_patient_at_time_of_operation,num__Number_of_positive_axillary_nodes_detected,cat__Patients_year_of_operation_58,cat__Patients_year_of_operation_59,cat__Patients_year_of_operation_60,cat__Patients_year_of_operation_61
0,haberman,lr,13,hidden_minority_medium,0,0,1.0,before_coins,-0.720775,-0.515014,0.0,0.0,0.0,1.0
1,haberman,lr,13,hidden_minority_medium,1,1,1.0,before_coins,0.200657,0.892345,0.0,0.0,1.0,0.0
2,haberman,lr,13,hidden_minority_medium,2,0,1.0,before_coins,-1.642206,0.380578,0.0,0.0,0.0,0.0
3,haberman,lr,13,hidden_minority_medium,3,0,1.0,before_coins,-1.181490,-0.515014,0.0,0.0,0.0,0.0
4,haberman,lr,13,hidden_minority_medium,4,0,1.0,before_coins,-0.905061,-0.387073,0.0,0.0,1.0,0.0

DATASET haberman MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__Age_of_patient_at_time_of_operation,num__Number_of_positive_axillary_nodes_detected,cat__Patients_year_of_operation_58,cat__Patients_year_of_operation_59,cat__Patients_year_of_operation_60,cat__Patients_year_of_operation_61
0,haberman,svm,13,hidden_minority_medium,0,0,1.0,before_coins,-0.720775,-0.515014,0.0,0.0,0.0,1.0
1,haberman,svm,13,hidden_minority_medium,1,1,1.0,before_coins,0.200657,0.892345,0.0,0.0,1.0,0.0
2,haberman,svm,13,hidden_minority_medium,2,0,1.0,before_coins,-1.642206,0.380578,0.0,0.0,0.0,0.0
3,haberman,svm,13,hidden_minority_medium,3,0,1.0,before_coins,-1.181490,-0.515014,0.0,0.0,0.0,0.0
4,haberman,svm,13,hidden_minority_medium,4,0,1.0,before_coins,-0.905061,-0.387073,0.0,0.0,1.0,0.0

DATASET ionosphere MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__a01,num__a02,num__a03,num__a04,num__a05,num__a06
0,ionosphere,lr,13,hidden_minority_medium,0,0,1.0,before_coins,0.230633,0.0,-0.179309,-0.142050,0.657098,-0.183277
1,ionosphere,lr,13,hidden_minority_medium,1,1,1.0,before_coins,0.230633,0.0,-0.752975,-1.457900,-1.745080,-0.356508
2,ionosphere,lr,13,hidden_minority_medium,2,0,1.0,before_coins,0.230633,0.0,-0.063087,-0.122596,-0.100938,-0.463196
3,ionosphere,lr,13,hidden_minority_medium,3,0,1.0,before_coins,0.230633,0.0,-1.137054,-0.375653,-0.429781,-0.356508
4,ionosphere,lr,13,hidden_minority_medium,4,0,1.0,before_coins,0.230633,0.0,0.618804,1.288709,-0.624068,0.488805

DATASET ionosphere MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__a01,num__a02,num__a03,num__a04,num__a05,num__a06
0,ionosphere,svm,13,hidden_minority_medium,0,0,1.0,before_coins,0.230633,0.0,-0.179309,-0.142050,0.657098,-0.183277
1,ionosphere,svm,13,hidden_minority_medium,1,1,1.0,before_coins,0.230633,0.0,-0.752975,-1.457900,-1.745080,-0.356508
2,ionosphere,svm,13,hidden_minority_medium,2,0,1.0,before_coins,0.230633,0.0,-0.063087,-0.122596,-0.100938,-0.463196
3,ionosphere,svm,13,hidden_minority_medium,3,0,1.0,before_coins,0.230633,0.0,-1.137054,-0.375653,-0.429781,-0.356508
4,ionosphere,svm,13,hidden_minority_medium,4,0,1.0,before_coins,0.230633,0.0,0.618804,1.288709,-0.624068,0.488805

DATASET vehicle_bus MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__COMPACTNESS,num__CIRCULARITY,num__DISTANCE_CIRCULARITY,num__RADIUS_RATIO,num__PR.AXIS_ASPECT_RATIO,num__MAX.LENGTH_ASPECT_RATIO
0,vehicle_bus,lr,13,hidden_minority_medium,0,1,1.0,before_coins,-0.848723,-0.447202,-0.784185,-0.914175,-0.334894,-0.368441
1,vehicle_bus,lr,13,hidden_minority_medium,1,1,1.0,before_coins,-1.447237,-0.605509,-0.784185,-0.435316,0.340256,-0.368441
2,vehicle_bus,lr,13,hidden_minority_medium,2,0,1.0,before_coins,1.305927,0.977559,1.352298,0.821688,-0.199864,0.464687
3,vehicle_bus,lr,13,hidden_minority_medium,3,0,1.0,before_coins,-0.489615,0.186025,-0.478973,-1.093747,-0.875014,0.464687
4,vehicle_bus,lr,13,hidden_minority_medium,4,0,1.0,before_coins,-0.250209,-0.922123,0.497705,0.642116,0.070196,-0.160159

DATASET vehicle_bus MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__COMPACTNESS,num__CIRCULARITY,num__DISTANCE_CIRCULARITY,num__RADIUS_RATIO,num__PR.AXIS_ASPECT_RATIO,num__MAX.LENGTH_ASPECT_RATIO
0,vehicle_bus,svm,13,hidden_minority_medium,0,1,1.0,before_coins,-0.848723,-0.447202,-0.784185,-0.914175,-0.334894,-0.368441
1,vehicle_bus,svm,13,hidden_minority_medium,1,1,1.0,before_coins,-1.447237,-0.605509,-0.784185,-0.435316,0.340256,-0.368441
2,vehicle_bus,svm,13,hidden_minority_medium,2,0,1.0,before_coins,1.305927,0.977559,1.352298,0.821688,-0.199864,0.464687
3,vehicle_bus,svm,13,hidden_minority_medium,3,0,1.0,before_coins,-0.489615,0.186025,-0.478973,-1.093747,-0.875014,0.464687
4,vehicle_bus,svm,13,hidden_minority_medium,4,0,1.0,before_coins,-0.250209,-0.922123,0.497705,0.642116,0.070196,-0.160159

DATASET glass_float MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__RI,num__Na,num__Mg,num__Al,num__Si,num__K
0,glass_float,lr,13,hidden_minority_medium,0,0,1.0,before_coins,-0.636010,-0.460671,0.728277,0.070225,0.216483,0.105522
1,glass_float,lr,13,hidden_minority_medium,1,0,1.0,before_coins,-0.302091,1.749425,-1.619081,0.558398,0.421752,-0.667873
2,glass_float,lr,13,hidden_minority_medium,2,0,1.0,before_coins,-0.066759,-0.460671,0.872528,-0.793467,0.524387,0.042129
3,glass_float,lr,13,hidden_minority_medium,3,0,1.0,before_coins,-0.085840,0.344031,0.957767,0.070225,-1.092111,0.016772
4,glass_float,lr,13,hidden_minority_medium,4,0,1.0,before_coins,-0.152623,0.264694,0.774175,-1.600830,0.434582,-0.591801

DATASET glass_float MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__RI,num__Na,num__Mg,num__Al,num__Si,num__K
0,glass_float,svm,13,hidden_minority_medium,0,0,1.0,before_coins,-0.636010,-0.460671,0.728277,0.070225,0.216483,0.105522
1,glass_float,svm,13,hidden_minority_medium,1,0,1.0,before_coins,-0.302091,1.749425,-1.619081,0.558398,0.421752,-0.667873
2,glass_float,svm,13,hidden_minority_medium,2,0,1.0,before_coins,-0.066759,-0.460671,0.872528,-0.793467,0.524387,0.042129
3,glass_float,svm,13,hidden_minority_medium,3,0,1.0,before_coins,-0.085840,0.344031,0.957767,0.070225,-1.092111,0.016772
4,glass_float,svm,13,hidden_minority_medium,4,0,1.0,before_coins,-0.152623,0.264694,0.774175,-1.600830,0.434582,-0.591801

DATASET abalone MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__Length,num__Diameter,num__Height,num__Whole_weight,num__Shucked_weight,num__Viscera_weight
0,abalone,lr,13,hidden_minority_medium,0,1,1.0,before_coins,0.325975,0.274833,-0.332763,0.087928,0.349271,0.203565
1,abalone,lr,13,hidden_minority_medium,1,0,1.0,before_coins,-0.047556,-0.128104,0.069486,-0.470587,-0.500000,-0.393549
2,abalone,lr,13,hidden_minority_medium,2,0,1.0,before_coins,1.363563,1.181440,1.812562,1.837075,1.632772,2.124924
3,abalone,lr,13,hidden_minority_medium,3,0,1.0,before_coins,-1.541682,-1.538382,-1.271342,-1.331090,-1.289293,-1.322928
4,abalone,lr,13,hidden_minority_medium,4,0,1.0,before_coins,-1.915214,-1.991686,-1.807674,-1.385210,-1.325279,-1.385529

DATASET abalone MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__Length,num__Diameter,num__Height,num__Whole_weight,num__Shucked_weight,num__Viscera_weight
0,abalone,svm,13,hidden_minority_medium,0,1,1.0,before_coins,0.325975,0.274833,-0.332763,0.087928,0.349271,0.203565
1,abalone,svm,13,hidden_minority_medium,1,0,1.0,before_coins,-0.047556,-0.128104,0.069486,-0.470587,-0.500000,-0.393549
2,abalone,svm,13,hidden_minority_medium,2,0,1.0,before_coins,1.363563,1.181440,1.812562,1.837075,1.632772,2.124924
3,abalone,svm,13,hidden_minority_medium,3,0,1.0,before_coins,-1.541682,-1.538382,-1.271342,-1.331090,-1.289293,-1.322928
4,abalone,svm,13,hidden_minority_medium,4,0,1.0,before_coins,-1.915214,-1.991686,-1.807674,-1.385210,-1.325279,-1.385529

DATASET spambase MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__word_freq_make,num__word_freq_address,num__word_freq_all,num__word_freq_3d,num__word_freq_our,num__word_freq_over
0,spambase,lr,13,hidden_minority_medium,0,0,1.0,before_coins,1.415177,-0.155892,-0.463470,-0.031669,-0.350292,-0.290500
1,spambase,lr,13,hidden_minority_medium,1,0,1.0,before_coins,0.613899,-0.155892,0.106608,-0.031669,-0.350292,-0.290500
2,spambase,lr,13,hidden_minority_medium,2,1,1.0,before_coins,-0.279833,-0.155892,-0.463470,-0.031669,-0.350292,-0.290500
3,spambase,lr,13,hidden_minority_medium,3,0,1.0,before_coins,-0.279833,-0.155892,-0.463470,-0.031669,-0.350292,-0.290500
4,spambase,lr,13,hidden_minority_medium,4,0,1.0,before_coins,1.230266,-0.155892,-0.463470,-0.031669,0.382144,1.902169

DATASET spambase MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__word_freq_make,num__word_freq_address,num__word_freq_all,num__word_freq_3d,num__word_freq_our,num__word_freq_over
0,spambase,svm,13,hidden_minority_medium,0,0,1.0,before_coins,1.415177,-0.155892,-0.463470,-0.031669,-0.350292,-0.290500
1,spambase,svm,13,hidden_minority_medium,1,0,1.0,before_coins,0.613899,-0.155892,0.106608,-0.031669,-0.350292,-0.290500
2,spambase,svm,13,hidden_minority_medium,2,1,1.0,before_coins,-0.279833,-0.155892,-0.463470,-0.031669,-0.350292,-0.290500
3,spambase,svm,13,hidden_minority_medium,3,0,1.0,before_coins,-0.279833,-0.155892,-0.463470,-0.031669,-0.350292,-0.290500
4,spambase,svm,13,hidden_minority_medium,4,0,1.0,before_coins,1.230266,-0.155892,-0.463470,-0.031669,0.382144,1.902169

DATASET kc1 MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__loc,num__v(g),num__ev(g),num__iv(g),num__n,num__v
0,kc1,lr,13,hidden_minority_medium,0,0,1.0,before_coins,4.372250,5.688859,7.945143,6.571513,4.377983,4.467136
1,kc1,lr,13,hidden_minority_medium,1,0,1.0,before_coins,-0.620252,-0.473054,-0.316316,-0.459450,-0.565969,-0.508153
2,kc1,lr,13,hidden_minority_medium,2,0,1.0,before_coins,0.704290,0.553932,0.601624,0.712377,0.617093,0.481918
3,kc1,lr,13,hidden_minority_medium,3,1,1.0,before_coins,-0.280626,-0.473054,-0.316316,-0.459450,-0.167464,-0.235943
4,kc1,lr,13,hidden_minority_medium,4,0,1.0,before_coins,-0.450439,-0.473054,-0.316316,-0.459450,-0.441436,-0.421575

DATASET kc1 MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__loc,num__v(g),num__ev(g),num__iv(g),num__n,num__v
0,kc1,svm,13,hidden_minority_medium,0,0,1.0,before_coins,4.372250,5.688859,7.945143,6.571513,4.377983,4.467136
1,kc1,svm,13,hidden_minority_medium,1,0,1.0,before_coins,-0.620252,-0.473054,-0.316316,-0.459450,-0.565969,-0.508153
2,kc1,svm,13,hidden_minority_medium,2,0,1.0,before_coins,0.704290,0.553932,0.601624,0.712377,0.617093,0.481918
3,kc1,svm,13,hidden_minority_medium,3,1,1.0,before_coins,-0.280626,-0.473054,-0.316316,-0.459450,-0.167464,-0.235943
4,kc1,svm,13,hidden_minority_medium,4,0,1.0,before_coins,-0.450439,-0.473054,-0.316316,-0.459450,-0.441436,-0.421575

## After Weighted Repair / CWMS `head(5)` For Each Dataset And Model

In [7]:
for df in preview_weighted:
    print("DATASET", df["dataset"].iloc[0], "MODEL", df["model"].iloc[0])
    display(df.head(5))

DATASET pima MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__preg,num__plas,num__pres,num__skin,num__insu,num__mass
0,pima,lr,13,hidden_minority_medium,0,0,0.378133,weighted_repair_cwms,0.501533,0.659328,0.637019,-1.273588,-0.698213,-0.583918
1,pima,lr,13,hidden_minority_medium,1,0,0.413516,weighted_repair_cwms,0.823477,0.351315,0.201982,1.677644,1.709804,0.355337
2,pima,lr,13,hidden_minority_medium,2,0,0.407984,weighted_repair_cwms,0.501533,1.172681,0.365121,-1.273588,-0.698213,-0.155728
3,pima,lr,13,hidden_minority_medium,3,0,0.763640,weighted_repair_cwms,-1.108190,0.043303,0.637019,0.956232,2.285634,1.819470
4,pima,lr,13,hidden_minority_medium,4,0,0.453327,weighted_repair_cwms,-1.108190,1.172681,0.908918,2.267891,-0.698213,1.626094

DATASET pima MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__preg,num__plas,num__pres,num__skin,num__insu,num__mass
0,pima,svm,13,hidden_minority_medium,0,0,0.809580,weighted_repair_cwms,0.501533,0.659328,0.637019,-1.273588,-0.698213,-0.583918
1,pima,svm,13,hidden_minority_medium,1,0,0.889498,weighted_repair_cwms,0.823477,0.351315,0.201982,1.677644,1.709804,0.355337
2,pima,svm,13,hidden_minority_medium,2,0,0.736508,weighted_repair_cwms,0.501533,1.172681,0.365121,-1.273588,-0.698213,-0.155728
3,pima,svm,13,hidden_minority_medium,3,0,0.829724,weighted_repair_cwms,-1.108190,0.043303,0.637019,0.956232,2.285634,1.819470
4,pima,svm,13,hidden_minority_medium,4,0,0.849022,weighted_repair_cwms,-1.108190,1.172681,0.908918,2.267891,-0.698213,1.626094

DATASET credit-g MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__duration,num__credit_amount,num__installment_commitment,num__residence_since,num__age,num__existing_credits
0,credit-g,lr,13,hidden_minority_medium,0,0,0.191764,weighted_repair_cwms,0.364387,-0.089388,0.058790,1.002163,1.297566,-0.715642
1,credit-g,lr,13,hidden_minority_medium,1,0,0.538483,weighted_repair_cwms,0.364387,-0.082600,-0.825926,-1.754157,-0.164635,-0.715642
2,credit-g,lr,13,hidden_minority_medium,2,0,0.423088,weighted_repair_cwms,-0.777311,-0.681467,0.943505,1.002163,0.351436,0.963259
3,credit-g,lr,13,hidden_minority_medium,3,0,0.564127,weighted_repair_cwms,0.100918,0.177236,-1.710641,1.002163,-0.852730,-0.715642
4,credit-g,lr,13,hidden_minority_medium,4,0,0.207158,weighted_repair_cwms,-0.426019,-1.032189,0.943505,1.002163,-1.110766,-0.715642

DATASET credit-g MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__duration,num__credit_amount,num__installment_commitment,num__residence_since,num__age,num__existing_credits
0,credit-g,svm,13,hidden_minority_medium,0,0,0.768537,weighted_repair_cwms,0.364387,-0.089388,0.058790,1.002163,1.297566,-0.715642
1,credit-g,svm,13,hidden_minority_medium,1,0,0.782686,weighted_repair_cwms,0.364387,-0.082600,-0.825926,-1.754157,-0.164635,-0.715642
2,credit-g,svm,13,hidden_minority_medium,2,0,0.822810,weighted_repair_cwms,-0.777311,-0.681467,0.943505,1.002163,0.351436,0.963259
3,credit-g,svm,13,hidden_minority_medium,3,0,0.812172,weighted_repair_cwms,0.100918,0.177236,-1.710641,1.002163,-0.852730,-0.715642
4,credit-g,svm,13,hidden_minority_medium,4,0,0.672485,weighted_repair_cwms,-0.426019,-1.032189,0.943505,1.002163,-1.110766,-0.715642

DATASET yeast MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__mcg,num__gvh,num__alm,num__mit,num__erl,num__pox
0,yeast,lr,13,hidden_minority_medium,0,1,1.000000,weighted_repair_cwms,0.856331,0.655157,0.236387,-0.796109,-0.096047,-0.094038
1,yeast,lr,13,hidden_minority_medium,1,0,0.552569,weighted_repair_cwms,1.070055,0.655157,0.351579,-0.351031,-0.096047,-0.094038
2,yeast,lr,13,hidden_minority_medium,2,0,0.405707,weighted_repair_cwms,0.713848,1.137108,0.697156,0.761663,-0.096047,-0.094038
3,yeast,lr,13,hidden_minority_medium,3,0,0.497504,weighted_repair_cwms,-0.354775,0.574832,-1.376307,0.168226,-0.096047,-0.094038
4,yeast,lr,13,hidden_minority_medium,4,0,0.389328,weighted_repair_cwms,0.785089,-0.951347,0.812349,0.761663,-0.096047,-0.094038

DATASET yeast MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__mcg,num__gvh,num__alm,num__mit,num__erl,num__pox
0,yeast,svm,13,hidden_minority_medium,0,1,1.000000,weighted_repair_cwms,0.856331,0.655157,0.236387,-0.796109,-0.096047,-0.094038
1,yeast,svm,13,hidden_minority_medium,1,0,0.797082,weighted_repair_cwms,1.070055,0.655157,0.351579,-0.351031,-0.096047,-0.094038
2,yeast,svm,13,hidden_minority_medium,2,0,0.542020,weighted_repair_cwms,0.713848,1.137108,0.697156,0.761663,-0.096047,-0.094038
3,yeast,svm,13,hidden_minority_medium,3,0,0.831662,weighted_repair_cwms,-0.354775,0.574832,-1.376307,0.168226,-0.096047,-0.094038
4,yeast,svm,13,hidden_minority_medium,4,0,0.665855,weighted_repair_cwms,0.785089,-0.951347,0.812349,0.761663,-0.096047,-0.094038

DATASET ecoli MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__mcg,num__gvh,num__lip,num__chg,num__aac,num__alm1
0,ecoli,lr,13,hidden_minority_medium,0,1,1.000000,weighted_repair_cwms,-0.849296,-0.062081,-0.164399,-0.066372,0.734146,1.900295
1,ecoli,lr,13,hidden_minority_medium,1,1,1.000000,weighted_repair_cwms,-0.422425,-1.723413,-0.164399,-0.066372,0.647373,-0.985831
2,ecoli,lr,13,hidden_minority_medium,2,0,0.678715,weighted_repair_cwms,-0.529143,-1.391147,-0.164399,-0.066372,-0.654223,-0.587745
3,ecoli,lr,13,hidden_minority_medium,3,0,0.246837,weighted_repair_cwms,-0.155630,-0.261441,-0.164399,-0.066372,1.081238,1.352926
4,ecoli,lr,13,hidden_minority_medium,4,0,0.260862,weighted_repair_cwms,0.004447,1.067624,-0.164399,-0.066372,-1.608727,2.248621

DATASET ecoli MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__mcg,num__gvh,num__lip,num__chg,num__aac,num__alm1
0,ecoli,svm,13,hidden_minority_medium,0,1,1.000000,weighted_repair_cwms,-0.849296,-0.062081,-0.164399,-0.066372,0.734146,1.900295
1,ecoli,svm,13,hidden_minority_medium,1,1,1.000000,weighted_repair_cwms,-0.422425,-1.723413,-0.164399,-0.066372,0.647373,-0.985831
2,ecoli,svm,13,hidden_minority_medium,2,0,0.894897,weighted_repair_cwms,-0.529143,-1.391147,-0.164399,-0.066372,-0.654223,-0.587745
3,ecoli,svm,13,hidden_minority_medium,3,0,0.425128,weighted_repair_cwms,-0.155630,-0.261441,-0.164399,-0.066372,1.081238,1.352926
4,ecoli,svm,13,hidden_minority_medium,4,0,0.749319,weighted_repair_cwms,0.004447,1.067624,-0.164399,-0.066372,-1.608727,2.248621

DATASET phoneme MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__V1,num__V2,num__V3,num__V4,num__V5
0,phoneme,lr,13,hidden_minority_medium,0,0,0.429898,weighted_repair_cwms,-0.717583,-0.353237,-0.312972,0.172724,0.990362
1,phoneme,lr,13,hidden_minority_medium,1,0,0.458092,weighted_repair_cwms,-0.564656,1.023772,0.955050,0.615022,-0.755116
2,phoneme,lr,13,hidden_minority_medium,2,0,0.253021,weighted_repair_cwms,-0.635559,-0.945903,1.185795,0.726156,2.148179
3,phoneme,lr,13,hidden_minority_medium,3,0,0.595441,weighted_repair_cwms,0.303368,-0.631372,-0.867714,-0.297395,-0.196041
4,phoneme,lr,13,hidden_minority_medium,4,0,0.456711,weighted_repair_cwms,-0.842904,-0.607324,1.555115,-1.554757,-0.096784

DATASET phoneme MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__V1,num__V2,num__V3,num__V4,num__V5
0,phoneme,svm,13,hidden_minority_medium,0,0,0.770724,weighted_repair_cwms,-0.717583,-0.353237,-0.312972,0.172724,0.990362
1,phoneme,svm,13,hidden_minority_medium,1,0,0.793630,weighted_repair_cwms,-0.564656,1.023772,0.955050,0.615022,-0.755116
2,phoneme,svm,13,hidden_minority_medium,2,0,0.604518,weighted_repair_cwms,-0.635559,-0.945903,1.185795,0.726156,2.148179
3,phoneme,svm,13,hidden_minority_medium,3,0,0.906305,weighted_repair_cwms,0.303368,-0.631372,-0.867714,-0.297395,-0.196041
4,phoneme,svm,13,hidden_minority_medium,4,0,0.878698,weighted_repair_cwms,-0.842904,-0.607324,1.555115,-1.554757,-0.096784

DATASET breast_cancer MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__V1,num__V2,num__V3,num__V4,num__V5,num__V6
0,breast_cancer,lr,13,hidden_minority_medium,0,0,0.270864,weighted_repair_cwms,0.657463,0.374065,0.620129,0.497735,0.155067,-0.130567
1,breast_cancer,lr,13,hidden_minority_medium,1,0,0.015106,weighted_repair_cwms,2.319486,0.617415,2.325630,2.404353,1.126951,1.629118
2,breast_cancer,lr,13,hidden_minority_medium,2,0,0.667960,weighted_repair_cwms,1.336754,0.198572,1.238298,1.225544,-1.361156,-0.388823
3,breast_cancer,lr,13,hidden_minority_medium,3,0,0.743837,weighted_repair_cwms,-0.932149,-0.475322,-0.903646,-0.817288,-0.347509,-0.194786
4,breast_cancer,lr,13,hidden_minority_medium,4,0,0.844088,weighted_repair_cwms,-1.458341,-0.414484,-1.436238,-1.133171,0.723474,-0.341637

DATASET breast_cancer MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__V1,num__V2,num__V3,num__V4,num__V5,num__V6
0,breast_cancer,svm,13,hidden_minority_medium,0,0,0.638921,weighted_repair_cwms,0.657463,0.374065,0.620129,0.497735,0.155067,-0.130567
1,breast_cancer,svm,13,hidden_minority_medium,1,0,0.205127,weighted_repair_cwms,2.319486,0.617415,2.325630,2.404353,1.126951,1.629118
2,breast_cancer,svm,13,hidden_minority_medium,2,0,0.607112,weighted_repair_cwms,1.336754,0.198572,1.238298,1.225544,-1.361156,-0.388823
3,breast_cancer,svm,13,hidden_minority_medium,3,0,0.911126,weighted_repair_cwms,-0.932149,-0.475322,-0.903646,-0.817288,-0.347509,-0.194786
4,breast_cancer,svm,13,hidden_minority_medium,4,0,0.940578,weighted_repair_cwms,-1.458341,-0.414484,-1.436238,-1.133171,0.723474,-0.341637

DATASET ilpd MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__V1,num__V3,num__V4,num__V5,num__V6,num__V7
0,ilpd,lr,13,hidden_minority_medium,0,1,1.000000,weighted_repair_cwms,-1.424899,-0.167327,-0.252116,-0.575074,-0.062032,-0.024316
1,ilpd,lr,13,hidden_minority_medium,1,1,1.000000,weighted_repair_cwms,0.926496,0.686179,0.766900,0.036633,1.544965,2.042331
2,ilpd,lr,13,hidden_minority_medium,2,0,0.491403,weighted_repair_cwms,-0.496717,-0.297523,-0.320051,-0.641564,-0.159426,-0.221548
3,ilpd,lr,13,hidden_minority_medium,3,0,0.463763,weighted_repair_cwms,-0.744232,-0.254124,-0.354018,-0.375604,-0.217862,-0.278717
4,ilpd,lr,13,hidden_minority_medium,4,1,1.000000,weighted_repair_cwms,-0.001686,-0.210726,-0.218149,-0.539612,-0.300647,-0.244415

DATASET ilpd MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__V1,num__V3,num__V4,num__V5,num__V6,num__V7
0,ilpd,svm,13,hidden_minority_medium,0,1,1.000000,weighted_repair_cwms,-1.424899,-0.167327,-0.252116,-0.575074,-0.062032,-0.024316
1,ilpd,svm,13,hidden_minority_medium,1,1,1.000000,weighted_repair_cwms,0.926496,0.686179,0.766900,0.036633,1.544965,2.042331
2,ilpd,svm,13,hidden_minority_medium,2,0,0.789536,weighted_repair_cwms,-0.496717,-0.297523,-0.320051,-0.641564,-0.159426,-0.221548
3,ilpd,svm,13,hidden_minority_medium,3,0,0.789990,weighted_repair_cwms,-0.744232,-0.254124,-0.354018,-0.375604,-0.217862,-0.278717
4,ilpd,svm,13,hidden_minority_medium,4,1,1.000000,weighted_repair_cwms,-0.001686,-0.210726,-0.218149,-0.539612,-0.300647,-0.244415

DATASET blood MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__V1,num__V2,num__V3,num__V4
0,blood,lr,13,hidden_minority_medium,0,0,0.466777,weighted_repair_cwms,-0.728132,2.071229,2.071229,1.515775
1,blood,lr,13,hidden_minority_medium,1,0,0.560890,weighted_repair_cwms,0.760757,-0.801028,-0.801028,-0.731894
2,blood,lr,13,hidden_minority_medium,2,0,0.440393,weighted_repair_cwms,-0.976280,-0.226576,-0.226576,-0.731894
3,blood,lr,13,hidden_minority_medium,3,0,0.505713,weighted_repair_cwms,0.388535,-0.226576,-0.226576,-0.523776
4,blood,lr,13,hidden_minority_medium,4,0,0.504720,weighted_repair_cwms,0.512609,1.496778,1.496778,0.974670

DATASET blood MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__V1,num__V2,num__V3,num__V4
0,blood,svm,13,hidden_minority_medium,0,0,0.848548,weighted_repair_cwms,-0.728132,2.071229,2.071229,1.515775
1,blood,svm,13,hidden_minority_medium,1,0,0.847909,weighted_repair_cwms,0.760757,-0.801028,-0.801028,-0.731894
2,blood,svm,13,hidden_minority_medium,2,0,0.764985,weighted_repair_cwms,-0.976280,-0.226576,-0.226576,-0.731894
3,blood,svm,13,hidden_minority_medium,3,0,0.804687,weighted_repair_cwms,0.388535,-0.226576,-0.226576,-0.523776
4,blood,svm,13,hidden_minority_medium,4,0,0.816368,weighted_repair_cwms,0.512609,1.496778,1.496778,0.974670

DATASET haberman MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__Age_of_patient_at_time_of_operation,num__Number_of_positive_axillary_nodes_detected,cat__Patients_year_of_operation_58,cat__Patients_year_of_operation_59,cat__Patients_year_of_operation_60,cat__Patients_year_of_operation_61
0,haberman,lr,13,hidden_minority_medium,0,0,0.491867,weighted_repair_cwms,-0.720775,-0.515014,0.0,0.0,0.0,1.0
1,haberman,lr,13,hidden_minority_medium,1,1,1.000000,weighted_repair_cwms,0.200657,0.892345,0.0,0.0,1.0,0.0
2,haberman,lr,13,hidden_minority_medium,2,0,0.432192,weighted_repair_cwms,-1.642206,0.380578,0.0,0.0,0.0,0.0
3,haberman,lr,13,hidden_minority_medium,3,0,0.768433,weighted_repair_cwms,-1.181490,-0.515014,0.0,0.0,0.0,0.0
4,haberman,lr,13,hidden_minority_medium,4,0,0.513133,weighted_repair_cwms,-0.905061,-0.387073,0.0,0.0,1.0,0.0

DATASET haberman MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__Age_of_patient_at_time_of_operation,num__Number_of_positive_axillary_nodes_detected,cat__Patients_year_of_operation_58,cat__Patients_year_of_operation_59,cat__Patients_year_of_operation_60,cat__Patients_year_of_operation_61
0,haberman,svm,13,hidden_minority_medium,0,0,0.694438,weighted_repair_cwms,-0.720775,-0.515014,0.0,0.0,0.0,1.0
1,haberman,svm,13,hidden_minority_medium,1,1,1.000000,weighted_repair_cwms,0.200657,0.892345,0.0,0.0,1.0,0.0
2,haberman,svm,13,hidden_minority_medium,2,0,0.818351,weighted_repair_cwms,-1.642206,0.380578,0.0,0.0,0.0,0.0
3,haberman,svm,13,hidden_minority_medium,3,0,0.832164,weighted_repair_cwms,-1.181490,-0.515014,0.0,0.0,0.0,0.0
4,haberman,svm,13,hidden_minority_medium,4,0,0.829815,weighted_repair_cwms,-0.905061,-0.387073,0.0,0.0,1.0,0.0

DATASET ionosphere MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__a01,num__a02,num__a03,num__a04,num__a05,num__a06
0,ionosphere,lr,13,hidden_minority_medium,0,0,0.380749,weighted_repair_cwms,0.230633,0.0,-0.179309,-0.142050,0.657098,-0.183277
1,ionosphere,lr,13,hidden_minority_medium,1,1,1.000000,weighted_repair_cwms,0.230633,0.0,-0.752975,-1.457900,-1.745080,-0.356508
2,ionosphere,lr,13,hidden_minority_medium,2,0,0.698812,weighted_repair_cwms,0.230633,0.0,-0.063087,-0.122596,-0.100938,-0.463196
3,ionosphere,lr,13,hidden_minority_medium,3,0,0.557515,weighted_repair_cwms,0.230633,0.0,-1.137054,-0.375653,-0.429781,-0.356508
4,ionosphere,lr,13,hidden_minority_medium,4,0,0.205183,weighted_repair_cwms,0.230633,0.0,0.618804,1.288709,-0.624068,0.488805

DATASET ionosphere MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__a01,num__a02,num__a03,num__a04,num__a05,num__a06
0,ionosphere,svm,13,hidden_minority_medium,0,0,0.784554,weighted_repair_cwms,0.230633,0.0,-0.179309,-0.142050,0.657098,-0.183277
1,ionosphere,svm,13,hidden_minority_medium,1,1,1.000000,weighted_repair_cwms,0.230633,0.0,-0.752975,-1.457900,-1.745080,-0.356508
2,ionosphere,svm,13,hidden_minority_medium,2,0,0.863063,weighted_repair_cwms,0.230633,0.0,-0.063087,-0.122596,-0.100938,-0.463196
3,ionosphere,svm,13,hidden_minority_medium,3,0,0.841369,weighted_repair_cwms,0.230633,0.0,-1.137054,-0.375653,-0.429781,-0.356508
4,ionosphere,svm,13,hidden_minority_medium,4,0,0.500000,weighted_repair_cwms,0.230633,0.0,0.618804,1.288709,-0.624068,0.488805

DATASET vehicle_bus MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__COMPACTNESS,num__CIRCULARITY,num__DISTANCE_CIRCULARITY,num__RADIUS_RATIO,num__PR.AXIS_ASPECT_RATIO,num__MAX.LENGTH_ASPECT_RATIO
0,vehicle_bus,lr,13,hidden_minority_medium,0,1,1.000000,weighted_repair_cwms,-0.848723,-0.447202,-0.784185,-0.914175,-0.334894,-0.368441
1,vehicle_bus,lr,13,hidden_minority_medium,1,1,1.000000,weighted_repair_cwms,-1.447237,-0.605509,-0.784185,-0.435316,0.340256,-0.368441
2,vehicle_bus,lr,13,hidden_minority_medium,2,0,0.868969,weighted_repair_cwms,1.305927,0.977559,1.352298,0.821688,-0.199864,0.464687
3,vehicle_bus,lr,13,hidden_minority_medium,3,0,0.700262,weighted_repair_cwms,-0.489615,0.186025,-0.478973,-1.093747,-0.875014,0.464687
4,vehicle_bus,lr,13,hidden_minority_medium,4,0,0.605678,weighted_repair_cwms,-0.250209,-0.922123,0.497705,0.642116,0.070196,-0.160159

DATASET vehicle_bus MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__COMPACTNESS,num__CIRCULARITY,num__DISTANCE_CIRCULARITY,num__RADIUS_RATIO,num__PR.AXIS_ASPECT_RATIO,num__MAX.LENGTH_ASPECT_RATIO
0,vehicle_bus,svm,13,hidden_minority_medium,0,1,1.000000,weighted_repair_cwms,-0.848723,-0.447202,-0.784185,-0.914175,-0.334894,-0.368441
1,vehicle_bus,svm,13,hidden_minority_medium,1,1,1.000000,weighted_repair_cwms,-1.447237,-0.605509,-0.784185,-0.435316,0.340256,-0.368441
2,vehicle_bus,svm,13,hidden_minority_medium,2,0,0.888370,weighted_repair_cwms,1.305927,0.977559,1.352298,0.821688,-0.199864,0.464687
3,vehicle_bus,svm,13,hidden_minority_medium,3,0,0.848858,weighted_repair_cwms,-0.489615,0.186025,-0.478973,-1.093747,-0.875014,0.464687
4,vehicle_bus,svm,13,hidden_minority_medium,4,0,0.827144,weighted_repair_cwms,-0.250209,-0.922123,0.497705,0.642116,0.070196,-0.160159

DATASET glass_float MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__RI,num__Na,num__Mg,num__Al,num__Si,num__K
0,glass_float,lr,13,hidden_minority_medium,0,0,0.509652,weighted_repair_cwms,-0.636010,-0.460671,0.728277,0.070225,0.216483,0.105522
1,glass_float,lr,13,hidden_minority_medium,1,0,0.844935,weighted_repair_cwms,-0.302091,1.749425,-1.619081,0.558398,0.421752,-0.667873
2,glass_float,lr,13,hidden_minority_medium,2,0,0.357432,weighted_repair_cwms,-0.066759,-0.460671,0.872528,-0.793467,0.524387,0.042129
3,glass_float,lr,13,hidden_minority_medium,3,0,0.374047,weighted_repair_cwms,-0.085840,0.344031,0.957767,0.070225,-1.092111,0.016772
4,glass_float,lr,13,hidden_minority_medium,4,0,0.180525,weighted_repair_cwms,-0.152623,0.264694,0.774175,-1.600830,0.434582,-0.591801

DATASET glass_float MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__RI,num__Na,num__Mg,num__Al,num__Si,num__K
0,glass_float,svm,13,hidden_minority_medium,0,0,0.806390,weighted_repair_cwms,-0.636010,-0.460671,0.728277,0.070225,0.216483,0.105522
1,glass_float,svm,13,hidden_minority_medium,1,0,0.913427,weighted_repair_cwms,-0.302091,1.749425,-1.619081,0.558398,0.421752,-0.667873
2,glass_float,svm,13,hidden_minority_medium,2,0,0.698826,weighted_repair_cwms,-0.066759,-0.460671,0.872528,-0.793467,0.524387,0.042129
3,glass_float,svm,13,hidden_minority_medium,3,0,0.732639,weighted_repair_cwms,-0.085840,0.344031,0.957767,0.070225,-1.092111,0.016772
4,glass_float,svm,13,hidden_minority_medium,4,0,0.577936,weighted_repair_cwms,-0.152623,0.264694,0.774175,-1.600830,0.434582,-0.591801

DATASET abalone MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__Length,num__Diameter,num__Height,num__Whole_weight,num__Shucked_weight,num__Viscera_weight
0,abalone,lr,13,hidden_minority_medium,0,1,1.000000,weighted_repair_cwms,0.325975,0.274833,-0.332763,0.087928,0.349271,0.203565
1,abalone,lr,13,hidden_minority_medium,1,0,0.631065,weighted_repair_cwms,-0.047556,-0.128104,0.069486,-0.470587,-0.500000,-0.393549
2,abalone,lr,13,hidden_minority_medium,2,0,0.293170,weighted_repair_cwms,1.363563,1.181440,1.812562,1.837075,1.632772,2.124924
3,abalone,lr,13,hidden_minority_medium,3,0,0.706307,weighted_repair_cwms,-1.541682,-1.538382,-1.271342,-1.331090,-1.289293,-1.322928
4,abalone,lr,13,hidden_minority_medium,4,0,0.732329,weighted_repair_cwms,-1.915214,-1.991686,-1.807674,-1.385210,-1.325279,-1.385529

DATASET abalone MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__Length,num__Diameter,num__Height,num__Whole_weight,num__Shucked_weight,num__Viscera_weight
0,abalone,svm,13,hidden_minority_medium,0,1,1.000000,weighted_repair_cwms,0.325975,0.274833,-0.332763,0.087928,0.349271,0.203565
1,abalone,svm,13,hidden_minority_medium,1,0,0.887509,weighted_repair_cwms,-0.047556,-0.128104,0.069486,-0.470587,-0.500000,-0.393549
2,abalone,svm,13,hidden_minority_medium,2,0,0.684977,weighted_repair_cwms,1.363563,1.181440,1.812562,1.837075,1.632772,2.124924
3,abalone,svm,13,hidden_minority_medium,3,0,0.900031,weighted_repair_cwms,-1.541682,-1.538382,-1.271342,-1.331090,-1.289293,-1.322928
4,abalone,svm,13,hidden_minority_medium,4,0,0.902777,weighted_repair_cwms,-1.915214,-1.991686,-1.807674,-1.385210,-1.325279,-1.385529

DATASET spambase MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__word_freq_make,num__word_freq_address,num__word_freq_all,num__word_freq_3d,num__word_freq_our,num__word_freq_over
0,spambase,lr,13,hidden_minority_medium,0,0,0.589663,weighted_repair_cwms,1.415177,-0.155892,-0.463470,-0.031669,-0.350292,-0.290500
1,spambase,lr,13,hidden_minority_medium,1,0,0.589824,weighted_repair_cwms,0.613899,-0.155892,0.106608,-0.031669,-0.350292,-0.290500
2,spambase,lr,13,hidden_minority_medium,2,1,1.000000,weighted_repair_cwms,-0.279833,-0.155892,-0.463470,-0.031669,-0.350292,-0.290500
3,spambase,lr,13,hidden_minority_medium,3,0,0.725571,weighted_repair_cwms,-0.279833,-0.155892,-0.463470,-0.031669,-0.350292,-0.290500
4,spambase,lr,13,hidden_minority_medium,4,0,0.614946,weighted_repair_cwms,1.230266,-0.155892,-0.463470,-0.031669,0.382144,1.902169

DATASET spambase MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__word_freq_make,num__word_freq_address,num__word_freq_all,num__word_freq_3d,num__word_freq_our,num__word_freq_over
0,spambase,svm,13,hidden_minority_medium,0,0,0.811851,weighted_repair_cwms,1.415177,-0.155892,-0.463470,-0.031669,-0.350292,-0.290500
1,spambase,svm,13,hidden_minority_medium,1,0,0.892791,weighted_repair_cwms,0.613899,-0.155892,0.106608,-0.031669,-0.350292,-0.290500
2,spambase,svm,13,hidden_minority_medium,2,1,1.000000,weighted_repair_cwms,-0.279833,-0.155892,-0.463470,-0.031669,-0.350292,-0.290500
3,spambase,svm,13,hidden_minority_medium,3,0,0.916250,weighted_repair_cwms,-0.279833,-0.155892,-0.463470,-0.031669,-0.350292,-0.290500
4,spambase,svm,13,hidden_minority_medium,4,0,0.903798,weighted_repair_cwms,1.230266,-0.155892,-0.463470,-0.031669,0.382144,1.902169

DATASET kc1 MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__loc,num__v(g),num__ev(g),num__iv(g),num__n,num__v
0,kc1,lr,13,hidden_minority_medium,0,0,0.402631,weighted_repair_cwms,4.372250,5.688859,7.945143,6.571513,4.377983,4.467136
1,kc1,lr,13,hidden_minority_medium,1,0,0.608840,weighted_repair_cwms,-0.620252,-0.473054,-0.316316,-0.459450,-0.565969,-0.508153
2,kc1,lr,13,hidden_minority_medium,2,0,0.445835,weighted_repair_cwms,0.704290,0.553932,0.601624,0.712377,0.617093,0.481918
3,kc1,lr,13,hidden_minority_medium,3,1,1.000000,weighted_repair_cwms,-0.280626,-0.473054,-0.316316,-0.459450,-0.167464,-0.235943
4,kc1,lr,13,hidden_minority_medium,4,0,0.545452,weighted_repair_cwms,-0.450439,-0.473054,-0.316316,-0.459450,-0.441436,-0.421575

DATASET kc1 MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__loc,num__v(g),num__ev(g),num__iv(g),num__n,num__v
0,kc1,svm,13,hidden_minority_medium,0,0,0.773460,weighted_repair_cwms,4.372250,5.688859,7.945143,6.571513,4.377983,4.467136
1,kc1,svm,13,hidden_minority_medium,1,0,0.847363,weighted_repair_cwms,-0.620252,-0.473054,-0.316316,-0.459450,-0.565969,-0.508153
2,kc1,svm,13,hidden_minority_medium,2,0,0.706204,weighted_repair_cwms,0.704290,0.553932,0.601624,0.712377,0.617093,0.481918
3,kc1,svm,13,hidden_minority_medium,3,1,1.000000,weighted_repair_cwms,-0.280626,-0.473054,-0.316316,-0.459450,-0.167464,-0.235943
4,kc1,svm,13,hidden_minority_medium,4,0,0.848468,weighted_repair_cwms,-0.450439,-0.473054,-0.316316,-0.459450,-0.441436,-0.421575

## Final Training Data Fed To Model: Original Weighted Rows `head(5)`

This is the actual final `X_aug`, `y_aug`, and `sample_weight` input after Boundary Fill. These first five rows are original rows with COINS weights.

In [8]:
for df in preview_final_original_head:
    print("DATASET", df["dataset"].iloc[0], "MODEL", df["model"].iloc[0])
    display(df.head(5))

DATASET pima MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__preg,num__plas,num__pres,num__skin,num__insu,num__mass
0,pima,lr,13,hidden_minority_medium,0,0,0.378133,original_weighted_repair,0.501533,0.659328,0.637019,-1.273588,-0.698213,-0.583918
1,pima,lr,13,hidden_minority_medium,1,0,0.413516,original_weighted_repair,0.823477,0.351315,0.201982,1.677644,1.709804,0.355337
2,pima,lr,13,hidden_minority_medium,2,0,0.407984,original_weighted_repair,0.501533,1.172681,0.365121,-1.273588,-0.698213,-0.155728
3,pima,lr,13,hidden_minority_medium,3,0,0.763640,original_weighted_repair,-1.108190,0.043303,0.637019,0.956232,2.285634,1.819470
4,pima,lr,13,hidden_minority_medium,4,0,0.453327,original_weighted_repair,-1.108190,1.172681,0.908918,2.267891,-0.698213,1.626094

DATASET pima MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__preg,num__plas,num__pres,num__skin,num__insu,num__mass
0,pima,svm,13,hidden_minority_medium,0,0,0.809580,original_weighted_repair,0.501533,0.659328,0.637019,-1.273588,-0.698213,-0.583918
1,pima,svm,13,hidden_minority_medium,1,0,0.889498,original_weighted_repair,0.823477,0.351315,0.201982,1.677644,1.709804,0.355337
2,pima,svm,13,hidden_minority_medium,2,0,0.736508,original_weighted_repair,0.501533,1.172681,0.365121,-1.273588,-0.698213,-0.155728
3,pima,svm,13,hidden_minority_medium,3,0,0.829724,original_weighted_repair,-1.108190,0.043303,0.637019,0.956232,2.285634,1.819470
4,pima,svm,13,hidden_minority_medium,4,0,0.849022,original_weighted_repair,-1.108190,1.172681,0.908918,2.267891,-0.698213,1.626094

DATASET credit-g MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__duration,num__credit_amount,num__installment_commitment,num__residence_since,num__age,num__existing_credits
0,credit-g,lr,13,hidden_minority_medium,0,0,0.191764,original_weighted_repair,0.364387,-0.089388,0.058790,1.002163,1.297566,-0.715642
1,credit-g,lr,13,hidden_minority_medium,1,0,0.538483,original_weighted_repair,0.364387,-0.082600,-0.825926,-1.754157,-0.164635,-0.715642
2,credit-g,lr,13,hidden_minority_medium,2,0,0.423088,original_weighted_repair,-0.777311,-0.681467,0.943505,1.002163,0.351436,0.963259
3,credit-g,lr,13,hidden_minority_medium,3,0,0.564127,original_weighted_repair,0.100918,0.177236,-1.710641,1.002163,-0.852730,-0.715642
4,credit-g,lr,13,hidden_minority_medium,4,0,0.207158,original_weighted_repair,-0.426019,-1.032189,0.943505,1.002163,-1.110766,-0.715642

DATASET credit-g MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__duration,num__credit_amount,num__installment_commitment,num__residence_since,num__age,num__existing_credits
0,credit-g,svm,13,hidden_minority_medium,0,0,0.768537,original_weighted_repair,0.364387,-0.089388,0.058790,1.002163,1.297566,-0.715642
1,credit-g,svm,13,hidden_minority_medium,1,0,0.782686,original_weighted_repair,0.364387,-0.082600,-0.825926,-1.754157,-0.164635,-0.715642
2,credit-g,svm,13,hidden_minority_medium,2,0,0.822810,original_weighted_repair,-0.777311,-0.681467,0.943505,1.002163,0.351436,0.963259
3,credit-g,svm,13,hidden_minority_medium,3,0,0.812172,original_weighted_repair,0.100918,0.177236,-1.710641,1.002163,-0.852730,-0.715642
4,credit-g,svm,13,hidden_minority_medium,4,0,0.672485,original_weighted_repair,-0.426019,-1.032189,0.943505,1.002163,-1.110766,-0.715642

DATASET yeast MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__mcg,num__gvh,num__alm,num__mit,num__erl,num__pox
0,yeast,lr,13,hidden_minority_medium,0,1,1.000000,original_weighted_repair,0.856331,0.655157,0.236387,-0.796109,-0.096047,-0.094038
1,yeast,lr,13,hidden_minority_medium,1,0,0.552569,original_weighted_repair,1.070055,0.655157,0.351579,-0.351031,-0.096047,-0.094038
2,yeast,lr,13,hidden_minority_medium,2,0,0.405707,original_weighted_repair,0.713848,1.137108,0.697156,0.761663,-0.096047,-0.094038
3,yeast,lr,13,hidden_minority_medium,3,0,0.497504,original_weighted_repair,-0.354775,0.574832,-1.376307,0.168226,-0.096047,-0.094038
4,yeast,lr,13,hidden_minority_medium,4,0,0.389328,original_weighted_repair,0.785089,-0.951347,0.812349,0.761663,-0.096047,-0.094038

DATASET yeast MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__mcg,num__gvh,num__alm,num__mit,num__erl,num__pox
0,yeast,svm,13,hidden_minority_medium,0,1,1.000000,original_weighted_repair,0.856331,0.655157,0.236387,-0.796109,-0.096047,-0.094038
1,yeast,svm,13,hidden_minority_medium,1,0,0.797082,original_weighted_repair,1.070055,0.655157,0.351579,-0.351031,-0.096047,-0.094038
2,yeast,svm,13,hidden_minority_medium,2,0,0.542020,original_weighted_repair,0.713848,1.137108,0.697156,0.761663,-0.096047,-0.094038
3,yeast,svm,13,hidden_minority_medium,3,0,0.831662,original_weighted_repair,-0.354775,0.574832,-1.376307,0.168226,-0.096047,-0.094038
4,yeast,svm,13,hidden_minority_medium,4,0,0.665855,original_weighted_repair,0.785089,-0.951347,0.812349,0.761663,-0.096047,-0.094038

DATASET ecoli MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__mcg,num__gvh,num__lip,num__chg,num__aac,num__alm1
0,ecoli,lr,13,hidden_minority_medium,0,1,1.000000,original_weighted_repair,-0.849296,-0.062081,-0.164399,-0.066372,0.734146,1.900295
1,ecoli,lr,13,hidden_minority_medium,1,1,1.000000,original_weighted_repair,-0.422425,-1.723413,-0.164399,-0.066372,0.647373,-0.985831
2,ecoli,lr,13,hidden_minority_medium,2,0,0.678715,original_weighted_repair,-0.529143,-1.391147,-0.164399,-0.066372,-0.654223,-0.587745
3,ecoli,lr,13,hidden_minority_medium,3,0,0.246837,original_weighted_repair,-0.155630,-0.261441,-0.164399,-0.066372,1.081238,1.352926
4,ecoli,lr,13,hidden_minority_medium,4,0,0.260862,original_weighted_repair,0.004447,1.067624,-0.164399,-0.066372,-1.608727,2.248621

DATASET ecoli MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__mcg,num__gvh,num__lip,num__chg,num__aac,num__alm1
0,ecoli,svm,13,hidden_minority_medium,0,1,1.000000,original_weighted_repair,-0.849296,-0.062081,-0.164399,-0.066372,0.734146,1.900295
1,ecoli,svm,13,hidden_minority_medium,1,1,1.000000,original_weighted_repair,-0.422425,-1.723413,-0.164399,-0.066372,0.647373,-0.985831
2,ecoli,svm,13,hidden_minority_medium,2,0,0.894897,original_weighted_repair,-0.529143,-1.391147,-0.164399,-0.066372,-0.654223,-0.587745
3,ecoli,svm,13,hidden_minority_medium,3,0,0.425128,original_weighted_repair,-0.155630,-0.261441,-0.164399,-0.066372,1.081238,1.352926
4,ecoli,svm,13,hidden_minority_medium,4,0,0.749319,original_weighted_repair,0.004447,1.067624,-0.164399,-0.066372,-1.608727,2.248621

DATASET phoneme MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__V1,num__V2,num__V3,num__V4,num__V5
0,phoneme,lr,13,hidden_minority_medium,0,0,0.429898,original_weighted_repair,-0.717583,-0.353237,-0.312972,0.172724,0.990362
1,phoneme,lr,13,hidden_minority_medium,1,0,0.458092,original_weighted_repair,-0.564656,1.023772,0.955050,0.615022,-0.755116
2,phoneme,lr,13,hidden_minority_medium,2,0,0.253021,original_weighted_repair,-0.635559,-0.945903,1.185795,0.726156,2.148179
3,phoneme,lr,13,hidden_minority_medium,3,0,0.595441,original_weighted_repair,0.303368,-0.631372,-0.867714,-0.297395,-0.196041
4,phoneme,lr,13,hidden_minority_medium,4,0,0.456711,original_weighted_repair,-0.842904,-0.607324,1.555115,-1.554757,-0.096784

DATASET phoneme MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__V1,num__V2,num__V3,num__V4,num__V5
0,phoneme,svm,13,hidden_minority_medium,0,0,0.770724,original_weighted_repair,-0.717583,-0.353237,-0.312972,0.172724,0.990362
1,phoneme,svm,13,hidden_minority_medium,1,0,0.793630,original_weighted_repair,-0.564656,1.023772,0.955050,0.615022,-0.755116
2,phoneme,svm,13,hidden_minority_medium,2,0,0.604518,original_weighted_repair,-0.635559,-0.945903,1.185795,0.726156,2.148179
3,phoneme,svm,13,hidden_minority_medium,3,0,0.906305,original_weighted_repair,0.303368,-0.631372,-0.867714,-0.297395,-0.196041
4,phoneme,svm,13,hidden_minority_medium,4,0,0.878698,original_weighted_repair,-0.842904,-0.607324,1.555115,-1.554757,-0.096784

DATASET breast_cancer MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__V1,num__V2,num__V3,num__V4,num__V5,num__V6
0,breast_cancer,lr,13,hidden_minority_medium,0,0,0.270864,original_weighted_repair,0.657463,0.374065,0.620129,0.497735,0.155067,-0.130567
1,breast_cancer,lr,13,hidden_minority_medium,1,0,0.015106,original_weighted_repair,2.319486,0.617415,2.325630,2.404353,1.126951,1.629118
2,breast_cancer,lr,13,hidden_minority_medium,2,0,0.667960,original_weighted_repair,1.336754,0.198572,1.238298,1.225544,-1.361156,-0.388823
3,breast_cancer,lr,13,hidden_minority_medium,3,0,0.743837,original_weighted_repair,-0.932149,-0.475322,-0.903646,-0.817288,-0.347509,-0.194786
4,breast_cancer,lr,13,hidden_minority_medium,4,0,0.844088,original_weighted_repair,-1.458341,-0.414484,-1.436238,-1.133171,0.723474,-0.341637

DATASET breast_cancer MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__V1,num__V2,num__V3,num__V4,num__V5,num__V6
0,breast_cancer,svm,13,hidden_minority_medium,0,0,0.638921,original_weighted_repair,0.657463,0.374065,0.620129,0.497735,0.155067,-0.130567
1,breast_cancer,svm,13,hidden_minority_medium,1,0,0.205127,original_weighted_repair,2.319486,0.617415,2.325630,2.404353,1.126951,1.629118
2,breast_cancer,svm,13,hidden_minority_medium,2,0,0.607112,original_weighted_repair,1.336754,0.198572,1.238298,1.225544,-1.361156,-0.388823
3,breast_cancer,svm,13,hidden_minority_medium,3,0,0.911126,original_weighted_repair,-0.932149,-0.475322,-0.903646,-0.817288,-0.347509,-0.194786
4,breast_cancer,svm,13,hidden_minority_medium,4,0,0.940578,original_weighted_repair,-1.458341,-0.414484,-1.436238,-1.133171,0.723474,-0.341637

DATASET ilpd MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__V1,num__V3,num__V4,num__V5,num__V6,num__V7
0,ilpd,lr,13,hidden_minority_medium,0,1,1.000000,original_weighted_repair,-1.424899,-0.167327,-0.252116,-0.575074,-0.062032,-0.024316
1,ilpd,lr,13,hidden_minority_medium,1,1,1.000000,original_weighted_repair,0.926496,0.686179,0.766900,0.036633,1.544965,2.042331
2,ilpd,lr,13,hidden_minority_medium,2,0,0.491403,original_weighted_repair,-0.496717,-0.297523,-0.320051,-0.641564,-0.159426,-0.221548
3,ilpd,lr,13,hidden_minority_medium,3,0,0.463763,original_weighted_repair,-0.744232,-0.254124,-0.354018,-0.375604,-0.217862,-0.278717
4,ilpd,lr,13,hidden_minority_medium,4,1,1.000000,original_weighted_repair,-0.001686,-0.210726,-0.218149,-0.539612,-0.300647,-0.244415

DATASET ilpd MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__V1,num__V3,num__V4,num__V5,num__V6,num__V7
0,ilpd,svm,13,hidden_minority_medium,0,1,1.000000,original_weighted_repair,-1.424899,-0.167327,-0.252116,-0.575074,-0.062032,-0.024316
1,ilpd,svm,13,hidden_minority_medium,1,1,1.000000,original_weighted_repair,0.926496,0.686179,0.766900,0.036633,1.544965,2.042331
2,ilpd,svm,13,hidden_minority_medium,2,0,0.789536,original_weighted_repair,-0.496717,-0.297523,-0.320051,-0.641564,-0.159426,-0.221548
3,ilpd,svm,13,hidden_minority_medium,3,0,0.789990,original_weighted_repair,-0.744232,-0.254124,-0.354018,-0.375604,-0.217862,-0.278717
4,ilpd,svm,13,hidden_minority_medium,4,1,1.000000,original_weighted_repair,-0.001686,-0.210726,-0.218149,-0.539612,-0.300647,-0.244415

DATASET blood MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__V1,num__V2,num__V3,num__V4
0,blood,lr,13,hidden_minority_medium,0,0,0.466777,original_weighted_repair,-0.728132,2.071229,2.071229,1.515775
1,blood,lr,13,hidden_minority_medium,1,0,0.560890,original_weighted_repair,0.760757,-0.801028,-0.801028,-0.731894
2,blood,lr,13,hidden_minority_medium,2,0,0.440393,original_weighted_repair,-0.976280,-0.226576,-0.226576,-0.731894
3,blood,lr,13,hidden_minority_medium,3,0,0.505713,original_weighted_repair,0.388535,-0.226576,-0.226576,-0.523776
4,blood,lr,13,hidden_minority_medium,4,0,0.504720,original_weighted_repair,0.512609,1.496778,1.496778,0.974670

DATASET blood MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__V1,num__V2,num__V3,num__V4
0,blood,svm,13,hidden_minority_medium,0,0,0.848548,original_weighted_repair,-0.728132,2.071229,2.071229,1.515775
1,blood,svm,13,hidden_minority_medium,1,0,0.847909,original_weighted_repair,0.760757,-0.801028,-0.801028,-0.731894
2,blood,svm,13,hidden_minority_medium,2,0,0.764985,original_weighted_repair,-0.976280,-0.226576,-0.226576,-0.731894
3,blood,svm,13,hidden_minority_medium,3,0,0.804687,original_weighted_repair,0.388535,-0.226576,-0.226576,-0.523776
4,blood,svm,13,hidden_minority_medium,4,0,0.816368,original_weighted_repair,0.512609,1.496778,1.496778,0.974670

DATASET haberman MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__Age_of_patient_at_time_of_operation,num__Number_of_positive_axillary_nodes_detected,cat__Patients_year_of_operation_58,cat__Patients_year_of_operation_59,cat__Patients_year_of_operation_60,cat__Patients_year_of_operation_61
0,haberman,lr,13,hidden_minority_medium,0,0,0.491867,original_weighted_repair,-0.720775,-0.515014,0.0,0.0,0.0,1.0
1,haberman,lr,13,hidden_minority_medium,1,1,1.000000,original_weighted_repair,0.200657,0.892345,0.0,0.0,1.0,0.0
2,haberman,lr,13,hidden_minority_medium,2,0,0.432192,original_weighted_repair,-1.642206,0.380578,0.0,0.0,0.0,0.0
3,haberman,lr,13,hidden_minority_medium,3,0,0.768433,original_weighted_repair,-1.181490,-0.515014,0.0,0.0,0.0,0.0
4,haberman,lr,13,hidden_minority_medium,4,0,0.513133,original_weighted_repair,-0.905061,-0.387073,0.0,0.0,1.0,0.0

DATASET haberman MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__Age_of_patient_at_time_of_operation,num__Number_of_positive_axillary_nodes_detected,cat__Patients_year_of_operation_58,cat__Patients_year_of_operation_59,cat__Patients_year_of_operation_60,cat__Patients_year_of_operation_61
0,haberman,svm,13,hidden_minority_medium,0,0,0.694438,original_weighted_repair,-0.720775,-0.515014,0.0,0.0,0.0,1.0
1,haberman,svm,13,hidden_minority_medium,1,1,1.000000,original_weighted_repair,0.200657,0.892345,0.0,0.0,1.0,0.0
2,haberman,svm,13,hidden_minority_medium,2,0,0.818351,original_weighted_repair,-1.642206,0.380578,0.0,0.0,0.0,0.0
3,haberman,svm,13,hidden_minority_medium,3,0,0.832164,original_weighted_repair,-1.181490,-0.515014,0.0,0.0,0.0,0.0
4,haberman,svm,13,hidden_minority_medium,4,0,0.829815,original_weighted_repair,-0.905061,-0.387073,0.0,0.0,1.0,0.0

DATASET ionosphere MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__a01,num__a02,num__a03,num__a04,num__a05,num__a06
0,ionosphere,lr,13,hidden_minority_medium,0,0,0.380749,original_weighted_repair,0.230633,0.0,-0.179309,-0.142050,0.657098,-0.183277
1,ionosphere,lr,13,hidden_minority_medium,1,1,1.000000,original_weighted_repair,0.230633,0.0,-0.752975,-1.457900,-1.745080,-0.356508
2,ionosphere,lr,13,hidden_minority_medium,2,0,0.698812,original_weighted_repair,0.230633,0.0,-0.063087,-0.122596,-0.100938,-0.463196
3,ionosphere,lr,13,hidden_minority_medium,3,0,0.557515,original_weighted_repair,0.230633,0.0,-1.137054,-0.375653,-0.429781,-0.356508
4,ionosphere,lr,13,hidden_minority_medium,4,0,0.205183,original_weighted_repair,0.230633,0.0,0.618804,1.288709,-0.624068,0.488805

DATASET ionosphere MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__a01,num__a02,num__a03,num__a04,num__a05,num__a06
0,ionosphere,svm,13,hidden_minority_medium,0,0,0.784554,original_weighted_repair,0.230633,0.0,-0.179309,-0.142050,0.657098,-0.183277
1,ionosphere,svm,13,hidden_minority_medium,1,1,1.000000,original_weighted_repair,0.230633,0.0,-0.752975,-1.457900,-1.745080,-0.356508
2,ionosphere,svm,13,hidden_minority_medium,2,0,0.863063,original_weighted_repair,0.230633,0.0,-0.063087,-0.122596,-0.100938,-0.463196
3,ionosphere,svm,13,hidden_minority_medium,3,0,0.841369,original_weighted_repair,0.230633,0.0,-1.137054,-0.375653,-0.429781,-0.356508
4,ionosphere,svm,13,hidden_minority_medium,4,0,0.500000,original_weighted_repair,0.230633,0.0,0.618804,1.288709,-0.624068,0.488805

DATASET vehicle_bus MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__COMPACTNESS,num__CIRCULARITY,num__DISTANCE_CIRCULARITY,num__RADIUS_RATIO,num__PR.AXIS_ASPECT_RATIO,num__MAX.LENGTH_ASPECT_RATIO
0,vehicle_bus,lr,13,hidden_minority_medium,0,1,1.000000,original_weighted_repair,-0.848723,-0.447202,-0.784185,-0.914175,-0.334894,-0.368441
1,vehicle_bus,lr,13,hidden_minority_medium,1,1,1.000000,original_weighted_repair,-1.447237,-0.605509,-0.784185,-0.435316,0.340256,-0.368441
2,vehicle_bus,lr,13,hidden_minority_medium,2,0,0.868969,original_weighted_repair,1.305927,0.977559,1.352298,0.821688,-0.199864,0.464687
3,vehicle_bus,lr,13,hidden_minority_medium,3,0,0.700262,original_weighted_repair,-0.489615,0.186025,-0.478973,-1.093747,-0.875014,0.464687
4,vehicle_bus,lr,13,hidden_minority_medium,4,0,0.605678,original_weighted_repair,-0.250209,-0.922123,0.497705,0.642116,0.070196,-0.160159

DATASET vehicle_bus MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__COMPACTNESS,num__CIRCULARITY,num__DISTANCE_CIRCULARITY,num__RADIUS_RATIO,num__PR.AXIS_ASPECT_RATIO,num__MAX.LENGTH_ASPECT_RATIO
0,vehicle_bus,svm,13,hidden_minority_medium,0,1,1.000000,original_weighted_repair,-0.848723,-0.447202,-0.784185,-0.914175,-0.334894,-0.368441
1,vehicle_bus,svm,13,hidden_minority_medium,1,1,1.000000,original_weighted_repair,-1.447237,-0.605509,-0.784185,-0.435316,0.340256,-0.368441
2,vehicle_bus,svm,13,hidden_minority_medium,2,0,0.888370,original_weighted_repair,1.305927,0.977559,1.352298,0.821688,-0.199864,0.464687
3,vehicle_bus,svm,13,hidden_minority_medium,3,0,0.848858,original_weighted_repair,-0.489615,0.186025,-0.478973,-1.093747,-0.875014,0.464687
4,vehicle_bus,svm,13,hidden_minority_medium,4,0,0.827144,original_weighted_repair,-0.250209,-0.922123,0.497705,0.642116,0.070196,-0.160159

DATASET glass_float MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__RI,num__Na,num__Mg,num__Al,num__Si,num__K
0,glass_float,lr,13,hidden_minority_medium,0,0,0.509652,original_weighted_repair,-0.636010,-0.460671,0.728277,0.070225,0.216483,0.105522
1,glass_float,lr,13,hidden_minority_medium,1,0,0.844935,original_weighted_repair,-0.302091,1.749425,-1.619081,0.558398,0.421752,-0.667873
2,glass_float,lr,13,hidden_minority_medium,2,0,0.357432,original_weighted_repair,-0.066759,-0.460671,0.872528,-0.793467,0.524387,0.042129
3,glass_float,lr,13,hidden_minority_medium,3,0,0.374047,original_weighted_repair,-0.085840,0.344031,0.957767,0.070225,-1.092111,0.016772
4,glass_float,lr,13,hidden_minority_medium,4,0,0.180525,original_weighted_repair,-0.152623,0.264694,0.774175,-1.600830,0.434582,-0.591801

DATASET glass_float MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__RI,num__Na,num__Mg,num__Al,num__Si,num__K
0,glass_float,svm,13,hidden_minority_medium,0,0,0.806390,original_weighted_repair,-0.636010,-0.460671,0.728277,0.070225,0.216483,0.105522
1,glass_float,svm,13,hidden_minority_medium,1,0,0.913427,original_weighted_repair,-0.302091,1.749425,-1.619081,0.558398,0.421752,-0.667873
2,glass_float,svm,13,hidden_minority_medium,2,0,0.698826,original_weighted_repair,-0.066759,-0.460671,0.872528,-0.793467,0.524387,0.042129
3,glass_float,svm,13,hidden_minority_medium,3,0,0.732639,original_weighted_repair,-0.085840,0.344031,0.957767,0.070225,-1.092111,0.016772
4,glass_float,svm,13,hidden_minority_medium,4,0,0.577936,original_weighted_repair,-0.152623,0.264694,0.774175,-1.600830,0.434582,-0.591801

DATASET abalone MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__Length,num__Diameter,num__Height,num__Whole_weight,num__Shucked_weight,num__Viscera_weight
0,abalone,lr,13,hidden_minority_medium,0,1,1.000000,original_weighted_repair,0.325975,0.274833,-0.332763,0.087928,0.349271,0.203565
1,abalone,lr,13,hidden_minority_medium,1,0,0.631065,original_weighted_repair,-0.047556,-0.128104,0.069486,-0.470587,-0.500000,-0.393549
2,abalone,lr,13,hidden_minority_medium,2,0,0.293170,original_weighted_repair,1.363563,1.181440,1.812562,1.837075,1.632772,2.124924
3,abalone,lr,13,hidden_minority_medium,3,0,0.706307,original_weighted_repair,-1.541682,-1.538382,-1.271342,-1.331090,-1.289293,-1.322928
4,abalone,lr,13,hidden_minority_medium,4,0,0.732329,original_weighted_repair,-1.915214,-1.991686,-1.807674,-1.385210,-1.325279,-1.385529

DATASET abalone MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__Length,num__Diameter,num__Height,num__Whole_weight,num__Shucked_weight,num__Viscera_weight
0,abalone,svm,13,hidden_minority_medium,0,1,1.000000,original_weighted_repair,0.325975,0.274833,-0.332763,0.087928,0.349271,0.203565
1,abalone,svm,13,hidden_minority_medium,1,0,0.887509,original_weighted_repair,-0.047556,-0.128104,0.069486,-0.470587,-0.500000,-0.393549
2,abalone,svm,13,hidden_minority_medium,2,0,0.684977,original_weighted_repair,1.363563,1.181440,1.812562,1.837075,1.632772,2.124924
3,abalone,svm,13,hidden_minority_medium,3,0,0.900031,original_weighted_repair,-1.541682,-1.538382,-1.271342,-1.331090,-1.289293,-1.322928
4,abalone,svm,13,hidden_minority_medium,4,0,0.902777,original_weighted_repair,-1.915214,-1.991686,-1.807674,-1.385210,-1.325279,-1.385529

DATASET spambase MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__word_freq_make,num__word_freq_address,num__word_freq_all,num__word_freq_3d,num__word_freq_our,num__word_freq_over
0,spambase,lr,13,hidden_minority_medium,0,0,0.589663,original_weighted_repair,1.415177,-0.155892,-0.463470,-0.031669,-0.350292,-0.290500
1,spambase,lr,13,hidden_minority_medium,1,0,0.589824,original_weighted_repair,0.613899,-0.155892,0.106608,-0.031669,-0.350292,-0.290500
2,spambase,lr,13,hidden_minority_medium,2,1,1.000000,original_weighted_repair,-0.279833,-0.155892,-0.463470,-0.031669,-0.350292,-0.290500
3,spambase,lr,13,hidden_minority_medium,3,0,0.725571,original_weighted_repair,-0.279833,-0.155892,-0.463470,-0.031669,-0.350292,-0.290500
4,spambase,lr,13,hidden_minority_medium,4,0,0.614946,original_weighted_repair,1.230266,-0.155892,-0.463470,-0.031669,0.382144,1.902169

DATASET spambase MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__word_freq_make,num__word_freq_address,num__word_freq_all,num__word_freq_3d,num__word_freq_our,num__word_freq_over
0,spambase,svm,13,hidden_minority_medium,0,0,0.811851,original_weighted_repair,1.415177,-0.155892,-0.463470,-0.031669,-0.350292,-0.290500
1,spambase,svm,13,hidden_minority_medium,1,0,0.892791,original_weighted_repair,0.613899,-0.155892,0.106608,-0.031669,-0.350292,-0.290500
2,spambase,svm,13,hidden_minority_medium,2,1,1.000000,original_weighted_repair,-0.279833,-0.155892,-0.463470,-0.031669,-0.350292,-0.290500
3,spambase,svm,13,hidden_minority_medium,3,0,0.916250,original_weighted_repair,-0.279833,-0.155892,-0.463470,-0.031669,-0.350292,-0.290500
4,spambase,svm,13,hidden_minority_medium,4,0,0.903798,original_weighted_repair,1.230266,-0.155892,-0.463470,-0.031669,0.382144,1.902169

DATASET kc1 MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__loc,num__v(g),num__ev(g),num__iv(g),num__n,num__v
0,kc1,lr,13,hidden_minority_medium,0,0,0.402631,original_weighted_repair,4.372250,5.688859,7.945143,6.571513,4.377983,4.467136
1,kc1,lr,13,hidden_minority_medium,1,0,0.608840,original_weighted_repair,-0.620252,-0.473054,-0.316316,-0.459450,-0.565969,-0.508153
2,kc1,lr,13,hidden_minority_medium,2,0,0.445835,original_weighted_repair,0.704290,0.553932,0.601624,0.712377,0.617093,0.481918
3,kc1,lr,13,hidden_minority_medium,3,1,1.000000,original_weighted_repair,-0.280626,-0.473054,-0.316316,-0.459450,-0.167464,-0.235943
4,kc1,lr,13,hidden_minority_medium,4,0,0.545452,original_weighted_repair,-0.450439,-0.473054,-0.316316,-0.459450,-0.441436,-0.421575

DATASET kc1 MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__loc,num__v(g),num__ev(g),num__iv(g),num__n,num__v
0,kc1,svm,13,hidden_minority_medium,0,0,0.773460,original_weighted_repair,4.372250,5.688859,7.945143,6.571513,4.377983,4.467136
1,kc1,svm,13,hidden_minority_medium,1,0,0.847363,original_weighted_repair,-0.620252,-0.473054,-0.316316,-0.459450,-0.565969,-0.508153
2,kc1,svm,13,hidden_minority_medium,2,0,0.706204,original_weighted_repair,0.704290,0.553932,0.601624,0.712377,0.617093,0.481918
3,kc1,svm,13,hidden_minority_medium,3,1,1.000000,original_weighted_repair,-0.280626,-0.473054,-0.316316,-0.459450,-0.167464,-0.235943
4,kc1,svm,13,hidden_minority_medium,4,0,0.848468,original_weighted_repair,-0.450439,-0.473054,-0.316316,-0.459450,-0.441436,-0.421575

## Final Training Data Fed To Model: Synthetic Boundary Fill Rows `head(5)`

These are the appended synthetic minority rows. Showing them separately makes the actual Boundary Fill additions visible instead of hiding them after the original rows.

In [9]:
for df in preview_final_synthetic_head:
    print("DATASET", df["dataset"].iloc[0], "MODEL", df["model"].iloc[0])
    display(df.head(5))

DATASET

 pima MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__preg,num__plas,num__pres,num__skin,num__insu,num__mass
0,pima,lr,13,hidden_minority_medium,441,1,1.0,synthetic_boundary_fill,0.719542,0.964914,0.497430,0.553955,0.371668,-0.342471
1,pima,lr,13,hidden_minority_medium,442,1,1.0,synthetic_boundary_fill,1.417658,1.472890,-0.316627,0.431568,4.219960,0.406322
2,pima,lr,13,hidden_minority_medium,443,1,1.0,synthetic_boundary_fill,1.147115,0.041052,-0.124869,-1.273588,-0.698213,0.241094
3,pima,lr,13,hidden_minority_medium,444,1,1.0,synthetic_boundary_fill,-0.425161,0.272467,0.106444,0.830049,0.281288,1.128672
4,pima,lr,13,hidden_minority_medium,445,1,1.0,synthetic_boundary_fill,-0.949005,0.078287,-3.489291,-1.111451,-0.642995,0.324911

DATASET pima MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__preg,num__plas,num__pres,num__skin,num__insu,num__mass
0,pima,svm,13,hidden_minority_medium,441,1,1.0,synthetic_boundary_fill,0.719542,0.964914,0.497430,0.553955,0.371668,-0.342471
1,pima,svm,13,hidden_minority_medium,442,1,1.0,synthetic_boundary_fill,1.318242,1.250959,-0.299834,0.375876,4.145601,0.369001
2,pima,svm,13,hidden_minority_medium,443,1,1.0,synthetic_boundary_fill,1.141187,0.041863,-0.125155,-1.270655,-0.694908,0.245527
3,pima,svm,13,hidden_minority_medium,444,1,1.0,synthetic_boundary_fill,0.208943,-0.940859,-0.536195,0.184186,-0.192997,-0.408429
4,pima,svm,13,hidden_minority_medium,445,1,1.0,synthetic_boundary_fill,-1.108190,0.021881,-3.713356,-1.273588,-0.698213,0.238402

DATASET credit-g MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__duration,num__credit_amount,num__installment_commitment,num__residence_since,num__age,num__existing_credits
0,credit-g,lr,13,hidden_minority_medium,617,1,1.0,synthetic_boundary_fill,-0.632783,0.077526,-0.275591,-0.488131,-0.273674,-0.398369
1,credit-g,lr,13,hidden_minority_medium,618,1,1.0,synthetic_boundary_fill,-0.405680,-0.592808,-0.894225,-0.906313,0.860558,0.833649
2,credit-g,lr,13,hidden_minority_medium,619,1,1.0,synthetic_boundary_fill,0.361614,3.082245,-0.821271,0.078555,-0.592658,0.963259
3,credit-g,lr,13,hidden_minority_medium,620,1,1.0,synthetic_boundary_fill,2.432098,1.524510,0.045345,0.055465,-0.334045,0.937746
4,credit-g,lr,13,hidden_minority_medium,621,1,1.0,synthetic_boundary_fill,-0.602640,-0.280845,-1.491918,1.002163,1.005046,-0.577287

DATASET credit-g MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__duration,num__credit_amount,num__installment_commitment,num__residence_since,num__age,num__existing_credits
0,credit-g,svm,13,hidden_minority_medium,617,1,1.0,synthetic_boundary_fill,2.073821,2.770260,0.441934,0.257016,-0.134159,-0.398369
1,credit-g,svm,13,hidden_minority_medium,618,1,1.0,synthetic_boundary_fill,-0.405680,-0.592808,-0.894225,-0.906313,0.860558,0.833649
2,credit-g,svm,13,hidden_minority_medium,619,1,1.0,synthetic_boundary_fill,0.361614,3.083755,-0.823598,0.078555,-0.593563,0.958842
3,credit-g,svm,13,hidden_minority_medium,620,1,1.0,synthetic_boundary_fill,-0.681480,-0.137829,-1.697196,-0.849346,-0.926978,-0.715642
4,credit-g,svm,13,hidden_minority_medium,621,1,1.0,synthetic_boundary_fill,-0.689488,-0.314844,-1.491918,1.002163,1.054662,-0.715642

DATASET yeast MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__mcg,num__gvh,num__alm,num__mit,num__erl,num__pox
0,yeast,lr,13,hidden_minority_medium,1094,1,1.0,synthetic_boundary_fill,-0.077662,-0.111411,-0.109191,0.921121,-0.096047,-0.094038
1,yeast,lr,13,hidden_minority_medium,1095,1,1.0,synthetic_boundary_fill,-1.378631,-0.369890,0.006002,-0.858569,-0.096047,-0.094038
2,yeast,lr,13,hidden_minority_medium,1096,1,1.0,synthetic_boundary_fill,0.000683,-1.270534,1.387098,-0.499781,-0.096047,-0.094038
3,yeast,lr,13,hidden_minority_medium,1097,1,1.0,synthetic_boundary_fill,0.351144,0.083115,0.461520,-0.433102,-0.096047,-0.094038
4,yeast,lr,13,hidden_minority_medium,1098,1,1.0,synthetic_boundary_fill,0.048400,0.110955,0.862371,1.516509,-0.096047,-0.094038

DATASET yeast MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__mcg,num__gvh,num__alm,num__mit,num__erl,num__pox
0,yeast,svm,13,hidden_minority_medium,1094,1,1.0,synthetic_boundary_fill,-0.366555,-0.241702,-1.603970,0.319507,-0.096047,-0.094038
1,yeast,svm,13,hidden_minority_medium,1095,1,1.0,synthetic_boundary_fill,-1.378631,-0.400895,-0.020677,-0.824209,-0.096047,-0.094038
2,yeast,svm,13,hidden_minority_medium,1096,1,1.0,synthetic_boundary_fill,0.005181,-1.265252,1.382553,-0.496658,-0.096047,-0.094038
3,yeast,svm,13,hidden_minority_medium,1097,1,1.0,synthetic_boundary_fill,-0.841557,-0.787034,1.822822,0.662684,-0.096047,-0.094038
4,yeast,svm,13,hidden_minority_medium,1098,1,1.0,synthetic_boundary_fill,-0.063147,-0.100867,0.995269,1.437040,-0.096047,-0.094038

DATASET ecoli MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__mcg,num__gvh,num__lip,num__chg,num__aac,num__alm1
0,ecoli,lr,13,hidden_minority_medium,228,1,1.0,synthetic_boundary_fill,-1.515652,-0.469696,-0.164399,-0.066372,-0.241539,0.039163
1,ecoli,lr,13,hidden_minority_medium,229,1,1.0,synthetic_boundary_fill,0.545699,0.801095,-0.164399,-0.066372,-0.948036,-0.212886
2,ecoli,lr,13,hidden_minority_medium,230,1,1.0,synthetic_boundary_fill,-0.528160,0.003847,-0.164399,-0.066372,1.331741,1.742373
3,ecoli,lr,13,hidden_minority_medium,231,1,1.0,synthetic_boundary_fill,-0.446592,-0.119446,-0.069464,-0.066372,0.108273,-0.132336
4,ecoli,lr,13,hidden_minority_medium,232,1,1.0,synthetic_boundary_fill,0.566196,0.902598,-0.164399,-0.066372,-0.814431,-0.246516

DATASET ecoli MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__mcg,num__gvh,num__lip,num__chg,num__aac,num__alm1
0,ecoli,svm,13,hidden_minority_medium,228,1,1.0,synthetic_boundary_fill,0.258636,-0.038535,-0.164399,-0.066372,0.321461,0.684877
1,ecoli,svm,13,hidden_minority_medium,229,1,1.0,synthetic_boundary_fill,0.722828,0.970390,-0.164399,-0.066372,-0.867650,-0.139898
2,ecoli,svm,13,hidden_minority_medium,230,1,1.0,synthetic_boundary_fill,-0.528160,0.003847,-0.164399,-0.066372,1.331741,1.742373
3,ecoli,svm,13,hidden_minority_medium,231,1,1.0,synthetic_boundary_fill,-0.446592,-0.119446,-0.069464,-0.066372,0.108273,-0.132336
4,ecoli,svm,13,hidden_minority_medium,232,1,1.0,synthetic_boundary_fill,0.698112,1.055934,-0.164399,-0.066372,-0.735773,-0.020978

DATASET phoneme MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__V1,num__V2,num__V3,num__V4,num__V5
0,phoneme,lr,13,hidden_minority_medium,3368,1,1.0,synthetic_boundary_fill,-0.698901,-0.703408,0.264568,1.047589,1.751447
1,phoneme,lr,13,hidden_minority_medium,3369,1,1.0,synthetic_boundary_fill,-0.835819,-1.081746,-0.127156,1.943357,-1.746865
2,phoneme,lr,13,hidden_minority_medium,3370,1,1.0,synthetic_boundary_fill,-0.247450,0.830601,-1.259372,-0.666046,-0.337698
3,phoneme,lr,13,hidden_minority_medium,3371,1,1.0,synthetic_boundary_fill,-0.485841,0.306526,-0.129236,-0.715502,-0.314223
4,phoneme,lr,13,hidden_minority_medium,3372,1,1.0,synthetic_boundary_fill,-0.589177,-0.160884,1.498078,-1.043810,-1.094060

DATASET phoneme MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__V1,num__V2,num__V3,num__V4,num__V5
0,phoneme,svm,13,hidden_minority_medium,3368,1,1.0,synthetic_boundary_fill,-0.812395,-0.702231,0.506347,2.057634,-1.644287
1,phoneme,svm,13,hidden_minority_medium,3369,1,1.0,synthetic_boundary_fill,-0.835819,-1.081746,-0.127156,1.943357,-1.746865
2,phoneme,svm,13,hidden_minority_medium,3370,1,1.0,synthetic_boundary_fill,-0.246976,0.831301,-1.261260,-0.665332,-0.337293
3,phoneme,svm,13,hidden_minority_medium,3371,1,1.0,synthetic_boundary_fill,0.129377,-0.244727,1.141257,0.466307,-0.627133
4,phoneme,svm,13,hidden_minority_medium,3372,1,1.0,synthetic_boundary_fill,-0.586182,-0.203095,1.591397,-1.139409,-1.123262

DATASET breast_cancer MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__V1,num__V2,num__V3,num__V4,num__V5,num__V6
0,breast_cancer,lr,13,hidden_minority_medium,314,1,1.0,synthetic_boundary_fill,0.339442,0.217365,0.320661,0.231574,-0.153668,-0.058711
1,breast_cancer,lr,13,hidden_minority_medium,315,1,1.0,synthetic_boundary_fill,-0.321208,0.341650,-0.374112,-0.352352,-0.856961,-1.030932
2,breast_cancer,lr,13,hidden_minority_medium,316,1,1.0,synthetic_boundary_fill,-0.415748,-0.247439,-0.395605,-0.442237,0.965243,0.186538
3,breast_cancer,lr,13,hidden_minority_medium,317,1,1.0,synthetic_boundary_fill,-1.141217,-0.127728,-1.148766,-0.946351,-0.713850,-0.792287
4,breast_cancer,lr,13,hidden_minority_medium,318,1,1.0,synthetic_boundary_fill,2.447739,1.420954,2.435786,2.511644,0.506456,1.546540

DATASET breast_cancer MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__V1,num__V2,num__V3,num__V4,num__V5,num__V6
0,breast_cancer,svm,13,hidden_minority_medium,314,1,1.0,synthetic_boundary_fill,-0.096820,0.686102,-0.047186,-0.159077,-0.667475,0.564790
1,breast_cancer,svm,13,hidden_minority_medium,315,1,1.0,synthetic_boundary_fill,-0.321208,0.341650,-0.374112,-0.352352,-0.856961,-1.030932
2,breast_cancer,svm,13,hidden_minority_medium,316,1,1.0,synthetic_boundary_fill,-0.415748,-0.247439,-0.395605,-0.442237,0.965243,0.186538
3,breast_cancer,svm,13,hidden_minority_medium,317,1,1.0,synthetic_boundary_fill,-0.505527,-1.828337,-0.520657,-0.504721,-0.514481,-0.669655
4,breast_cancer,svm,13,hidden_minority_medium,318,1,1.0,synthetic_boundary_fill,2.078051,1.329940,2.069319,2.101012,0.502081,1.393751

DATASET ilpd MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__V1,num__V3,num__V4,num__V5,num__V6,num__V7
0,ilpd,lr,13,hidden_minority_medium,367,1,1.0,synthetic_boundary_fill,-0.934741,1.291482,2.038128,-0.689485,-0.223230,-0.083511
1,ilpd,lr,13,hidden_minority_medium,368,1,1.0,synthetic_boundary_fill,0.250606,-0.209401,-0.306695,-0.397911,-0.229105,-0.250851
2,ilpd,lr,13,hidden_minority_medium,369,1,1.0,synthetic_boundary_fill,0.920799,-0.283514,-0.320587,1.432349,-0.254847,-0.275987
3,ilpd,lr,13,hidden_minority_medium,370,1,1.0,synthetic_boundary_fill,1.534001,-0.172383,-0.189860,0.315770,-0.159648,-0.227039
4,ilpd,lr,13,hidden_minority_medium,371,1,1.0,synthetic_boundary_fill,-2.191965,-0.405229,-0.473469,0.657922,0.228683,0.232445

DATASET ilpd MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__V1,num__V3,num__V4,num__V5,num__V6,num__V7
0,ilpd,svm,13,hidden_minority_medium,367,1,1.0,synthetic_boundary_fill,0.169333,0.106506,0.302592,0.087032,-0.171888,-0.275926
1,ilpd,svm,13,hidden_minority_medium,368,1,1.0,synthetic_boundary_fill,0.250606,-0.209401,-0.306695,-0.397911,-0.229105,-0.250851
2,ilpd,svm,13,hidden_minority_medium,369,1,1.0,synthetic_boundary_fill,0.924869,-0.283133,-0.320051,1.434052,-0.256897,-0.278604
3,ilpd,svm,13,hidden_minority_medium,370,1,1.0,synthetic_boundary_fill,-0.294154,-0.428818,-0.490919,-0.421965,-0.126078,-0.246744
4,ilpd,svm,13,hidden_minority_medium,371,1,1.0,synthetic_boundary_fill,-2.176667,-0.275287,-0.277527,0.959283,0.246341,0.228440

DATASET blood MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__V1,num__V2,num__V3,num__V4
0,blood,lr,13,hidden_minority_medium,502,1,1.0,synthetic_boundary_fill,0.432498,-0.609544,-0.609544,-0.826284
1,blood,lr,13,hidden_minority_medium,503,1,1.0,synthetic_boundary_fill,-0.546141,-0.608856,-0.608856,-0.945391
2,blood,lr,13,hidden_minority_medium,504,1,1.0,synthetic_boundary_fill,-0.728785,-0.036604,-0.036604,1.675371
3,blood,lr,13,hidden_minority_medium,505,1,1.0,synthetic_boundary_fill,-0.731903,0.330416,0.330416,0.980872
4,blood,lr,13,hidden_minority_medium,506,1,1.0,synthetic_boundary_fill,-0.698836,-0.082432,-0.082432,-0.860657

DATASET blood MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__V1,num__V2,num__V3,num__V4
0,blood,svm,13,hidden_minority_medium,502,1,1.0,synthetic_boundary_fill,0.935632,1.564626,1.564626,0.794082
1,blood,svm,13,hidden_minority_medium,503,1,1.0,synthetic_boundary_fill,-0.546141,-0.608856,-0.608856,-0.945391
2,blood,svm,13,hidden_minority_medium,504,1,1.0,synthetic_boundary_fill,-0.728785,-0.036604,-0.036604,1.675371
3,blood,svm,13,hidden_minority_medium,505,1,1.0,synthetic_boundary_fill,-0.976280,-0.801028,-0.801028,-1.314623
4,blood,svm,13,hidden_minority_medium,506,1,1.0,synthetic_boundary_fill,-0.841981,-0.050872,-0.050872,-0.877807

DATASET haberman MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__Age_of_patient_at_time_of_operation,num__Number_of_positive_axillary_nodes_detected,cat__Patients_year_of_operation_58,cat__Patients_year_of_operation_59,cat__Patients_year_of_operation_60,cat__Patients_year_of_operation_61
0,haberman,lr,13,hidden_minority_medium,197,1,1.0,synthetic_boundary_fill,1.550880,-0.515014,0.0,0.000000,0.000000,0.188977
1,haberman,lr,13,hidden_minority_medium,198,1,1.0,synthetic_boundary_fill,-0.415892,0.911640,0.0,0.077199,0.000000,0.000000
2,haberman,lr,13,hidden_minority_medium,199,1,1.0,synthetic_boundary_fill,2.409911,-0.387409,0.0,0.000000,0.002631,0.000000
3,haberman,lr,13,hidden_minority_medium,200,1,1.0,synthetic_boundary_fill,1.095484,2.258875,0.0,0.000000,0.000000,0.000000
4,haberman,lr,13,hidden_minority_medium,201,1,1.0,synthetic_boundary_fill,0.539879,-0.355442,0.0,0.000000,0.000000,0.000000

DATASET haberman MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__Age_of_patient_at_time_of_operation,num__Number_of_positive_axillary_nodes_detected,cat__Patients_year_of_operation_58,cat__Patients_year_of_operation_59,cat__Patients_year_of_operation_60,cat__Patients_year_of_operation_61
0,haberman,svm,13,hidden_minority_medium,197,1,1.0,synthetic_boundary_fill,1.550880,-0.515014,0.0,0.000000,0.0,0.188977
1,haberman,svm,13,hidden_minority_medium,198,1,1.0,synthetic_boundary_fill,-0.316304,0.921517,0.0,0.077199,0.0,0.000000
2,haberman,svm,13,hidden_minority_medium,199,1,1.0,synthetic_boundary_fill,2.402154,-0.385390,0.0,0.002631,0.0,0.000000
3,haberman,svm,13,hidden_minority_medium,200,1,1.0,synthetic_boundary_fill,1.095484,-0.513070,0.0,0.000000,0.0,0.000000
4,haberman,svm,13,hidden_minority_medium,201,1,1.0,synthetic_boundary_fill,0.539879,-0.355442,0.0,0.000000,0.0,0.000000

DATASET ionosphere MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__a01,num__a02,num__a03,num__a04,num__a05,num__a06
0,ionosphere,lr,13,hidden_minority_medium,198,1,1.0,synthetic_boundary_fill,0.230633,0.0,0.368191,0.499487,0.092429,0.806022
1,ionosphere,lr,13,hidden_minority_medium,199,1,1.0,synthetic_boundary_fill,0.230633,0.0,-0.608717,0.795691,-0.332694,1.963292
2,ionosphere,lr,13,hidden_minority_medium,200,1,1.0,synthetic_boundary_fill,0.230633,0.0,-0.394106,-0.147984,-0.745065,-0.358485
3,ionosphere,lr,13,hidden_minority_medium,201,1,1.0,synthetic_boundary_fill,0.230633,0.0,0.568747,-0.094554,0.297039,-0.639042
4,ionosphere,lr,13,hidden_minority_medium,202,1,1.0,synthetic_boundary_fill,0.230633,0.0,-0.799103,0.998300,-0.733215,1.624358

DATASET ionosphere MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__a01,num__a02,num__a03,num__a04,num__a05,num__a06
0,ionosphere,svm,13,hidden_minority_medium,198,1,1.0,synthetic_boundary_fill,0.230633,0.0,-0.246552,-0.644478,0.506479,0.764044
1,ionosphere,svm,13,hidden_minority_medium,199,1,1.0,synthetic_boundary_fill,-0.121901,0.0,-0.608717,0.795691,-0.332694,1.963292
2,ionosphere,svm,13,hidden_minority_medium,200,1,1.0,synthetic_boundary_fill,0.230633,0.0,-0.394206,-0.148373,-0.748065,-0.355374
3,ionosphere,svm,13,hidden_minority_medium,201,1,1.0,synthetic_boundary_fill,0.230633,0.0,0.484638,0.161319,0.683643,-0.404409
4,ionosphere,svm,13,hidden_minority_medium,202,1,1.0,synthetic_boundary_fill,0.230633,0.0,-0.799103,0.998300,-0.733215,1.624358

DATASET vehicle_bus MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__COMPACTNESS,num__CIRCULARITY,num__DISTANCE_CIRCULARITY,num__RADIUS_RATIO,num__PR.AXIS_ASPECT_RATIO,num__MAX.LENGTH_ASPECT_RATIO
0,vehicle_bus,lr,13,hidden_minority_medium,554,1,1.0,synthetic_boundary_fill,-0.778032,-0.404821,-0.354004,-0.933027,-0.951567,-0.368441
1,vehicle_bus,lr,13,hidden_minority_medium,555,1,1.0,synthetic_boundary_fill,-0.600077,-0.520530,-0.765336,-0.591676,0.049348,-0.352362
2,vehicle_bus,lr,13,hidden_minority_medium,556,1,1.0,synthetic_boundary_fill,-0.245486,0.189357,-0.049107,0.016212,-0.467437,-0.158515
3,vehicle_bus,lr,13,hidden_minority_medium,557,1,1.0,synthetic_boundary_fill,1.173491,1.123837,1.035027,0.629836,-0.324634,0.048123
4,vehicle_bus,lr,13,hidden_minority_medium,558,1,1.0,synthetic_boundary_fill,0.020119,-0.380216,-0.728173,-0.355063,0.306874,-0.525231

DATASET vehicle_bus MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__COMPACTNESS,num__CIRCULARITY,num__DISTANCE_CIRCULARITY,num__RADIUS_RATIO,num__PR.AXIS_ASPECT_RATIO,num__MAX.LENGTH_ASPECT_RATIO
0,vehicle_bus,svm,13,hidden_minority_medium,554,1,1.0,synthetic_boundary_fill,-0.778032,-0.404821,-0.354004,-0.933027,-0.951567,-0.368441
1,vehicle_bus,svm,13,hidden_minority_medium,555,1,1.0,synthetic_boundary_fill,-0.516908,-0.373875,-0.623963,-0.533914,0.080620,-0.320204
2,vehicle_bus,svm,13,hidden_minority_medium,556,1,1.0,synthetic_boundary_fill,-0.248950,0.183526,-0.048786,0.014244,-0.469924,-0.160159
3,vehicle_bus,svm,13,hidden_minority_medium,557,1,1.0,synthetic_boundary_fill,1.173491,1.123837,1.035027,0.629836,-0.324634,0.048123
4,vehicle_bus,svm,13,hidden_minority_medium,558,1,1.0,synthetic_boundary_fill,0.227273,-0.145393,-0.597384,-0.212014,0.318001,-0.473739

DATASET glass_float MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__RI,num__Na,num__Mg,num__Al,num__Si,num__K
0,glass_float,lr,13,hidden_minority_medium,127,1,1.0,synthetic_boundary_fill,-0.196294,-0.446035,0.387423,-0.122117,0.411954,0.040132
1,glass_float,lr,13,hidden_minority_medium,128,1,1.0,synthetic_boundary_fill,-0.064892,-0.543812,0.498657,-0.799534,0.517638,0.080916
2,glass_float,lr,13,hidden_minority_medium,129,1,1.0,synthetic_boundary_fill,0.231667,0.092778,0.663036,-0.287061,-0.910408,0.029684
3,glass_float,lr,13,hidden_minority_medium,130,1,1.0,synthetic_boundary_fill,-0.737438,-0.189348,0.570812,-0.066628,0.548448,-0.169361
4,glass_float,lr,13,hidden_minority_medium,131,1,1.0,synthetic_boundary_fill,-0.144267,-0.702417,0.640700,-0.668850,0.498443,0.136244

DATASET glass_float MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__RI,num__Na,num__Mg,num__Al,num__Si,num__K
0,glass_float,svm,13,hidden_minority_medium,127,1,1.0,synthetic_boundary_fill,1.874799,0.234173,-1.186637,-0.228711,-1.336070,-0.381456
1,glass_float,svm,13,hidden_minority_medium,128,1,1.0,synthetic_boundary_fill,-0.027574,-0.590185,0.688983,-0.796635,0.350258,0.091682
2,glass_float,svm,13,hidden_minority_medium,129,1,1.0,synthetic_boundary_fill,0.230864,0.090840,0.662311,-0.287456,-0.907100,0.029684
3,glass_float,svm,13,hidden_minority_medium,130,1,1.0,synthetic_boundary_fill,-0.674801,-0.088894,0.693500,-0.307005,0.005169,0.042900
4,glass_float,svm,13,hidden_minority_medium,131,1,1.0,synthetic_boundary_fill,-0.094735,-0.655717,0.689871,-0.687417,0.406463,0.137289

DATASET abalone MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__Length,num__Diameter,num__Height,num__Whole_weight,num__Shucked_weight,num__Viscera_weight
0,abalone,lr,13,hidden_minority_medium,1152,1,1.0,synthetic_boundary_fill,1.061927,1.050962,0.714561,0.867694,0.785448,1.243244
1,abalone,lr,13,hidden_minority_medium,1153,1,1.0,synthetic_boundary_fill,0.676482,0.731301,0.779859,0.893813,0.845602,1.082594
2,abalone,lr,13,hidden_minority_medium,1154,1,1.0,synthetic_boundary_fill,1.277936,1.329891,1.942059,1.339947,0.814810,1.220599
3,abalone,lr,13,hidden_minority_medium,1155,1,1.0,synthetic_boundary_fill,0.696353,0.723544,0.865832,0.790161,0.885182,1.034251
4,abalone,lr,13,hidden_minority_medium,1156,1,1.0,synthetic_boundary_fill,1.429930,1.337251,0.963867,1.660704,1.416815,1.980714

DATASET abalone MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__Length,num__Diameter,num__Height,num__Whole_weight,num__Shucked_weight,num__Viscera_weight
0,abalone,svm,13,hidden_minority_medium,1152,1,1.0,synthetic_boundary_fill,1.600492,1.336904,2.019493,2.386368,1.826397,2.254751
1,abalone,svm,13,hidden_minority_medium,1153,1,1.0,synthetic_boundary_fill,0.750175,0.824620,0.966179,0.937765,0.882643,1.127575
2,abalone,svm,13,hidden_minority_medium,1154,1,1.0,synthetic_boundary_fill,1.275424,1.327374,1.941354,1.338230,0.812690,1.219434
3,abalone,svm,13,hidden_minority_medium,1155,1,1.0,synthetic_boundary_fill,-0.611576,-0.665303,-0.850756,-0.809822,-0.811172,-0.772550
4,abalone,svm,13,hidden_minority_medium,1156,1,1.0,synthetic_boundary_fill,1.385467,1.283293,0.897570,1.606026,1.387753,1.937857

DATASET spambase MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__word_freq_make,num__word_freq_address,num__word_freq_all,num__word_freq_3d,num__word_freq_our,num__word_freq_over
0,spambase,lr,13,hidden_minority_medium,2460,1,1.0,synthetic_boundary_fill,-0.279833,-0.155892,-0.463470,-0.031669,-0.350292,-0.2905
1,spambase,lr,13,hidden_minority_medium,2461,1,1.0,synthetic_boundary_fill,-0.279833,-0.155892,-0.463470,-0.031669,-0.350292,-0.2905
2,spambase,lr,13,hidden_minority_medium,2462,1,1.0,synthetic_boundary_fill,-0.279833,-0.155892,-0.463470,-0.031669,-0.350292,-0.2905
3,spambase,lr,13,hidden_minority_medium,2463,1,1.0,synthetic_boundary_fill,-0.279833,-0.155892,1.549879,-0.031669,1.180642,-0.2905
4,spambase,lr,13,hidden_minority_medium,2464,1,1.0,synthetic_boundary_fill,-0.279833,-0.155892,-0.463470,-0.031669,-0.350292,-0.2905

DATASET spambase MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__word_freq_make,num__word_freq_address,num__word_freq_all,num__word_freq_3d,num__word_freq_our,num__word_freq_over
0,spambase,svm,13,hidden_minority_medium,2460,1,1.0,synthetic_boundary_fill,-0.279833,-0.155892,-0.463470,-0.031669,-0.350292,-0.290500
1,spambase,svm,13,hidden_minority_medium,2461,1,1.0,synthetic_boundary_fill,-0.279833,-0.155892,-0.351169,-0.031669,-0.350292,-0.290500
2,spambase,svm,13,hidden_minority_medium,2462,1,1.0,synthetic_boundary_fill,-0.279833,-0.155892,-0.463470,-0.031669,-0.350292,-0.290500
3,spambase,svm,13,hidden_minority_medium,2463,1,1.0,synthetic_boundary_fill,-0.279833,-0.155892,-0.463470,-0.031669,-0.350292,-0.290500
4,spambase,svm,13,hidden_minority_medium,2464,1,1.0,synthetic_boundary_fill,-0.264595,-0.155892,-0.398671,-0.031669,-0.334279,-0.242561

DATASET kc1 MODEL lr

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__loc,num__v(g),num__ev(g),num__iv(g),num__n,num__v
0,kc1,lr,13,hidden_minority_medium,1572,1,1.0,synthetic_boundary_fill,-0.011866,-0.278977,-0.142846,-0.238002,-0.375738,-0.323338
1,kc1,lr,13,hidden_minority_medium,1573,1,1.0,synthetic_boundary_fill,-0.481291,-0.393771,-0.316316,-0.368986,-0.444879,-0.406699
2,kc1,lr,13,hidden_minority_medium,1574,1,1.0,synthetic_boundary_fill,1.446195,1.319443,1.514734,1.585853,1.036442,0.970528
3,kc1,lr,13,hidden_minority_medium,1575,1,1.0,synthetic_boundary_fill,-0.587220,-0.161684,-0.246568,-0.108618,-0.456391,-0.419852
4,kc1,lr,13,hidden_minority_medium,1576,1,1.0,synthetic_boundary_fill,-0.399306,-0.473054,-0.316316,-0.459450,-0.260518,-0.322639

DATASET kc1 MODEL svm

,dataset,model,seed,noise_protocol,row_index,observed_label_for_training,sample_weight,row_stage,num__loc,num__v(g),num__ev(g),num__iv(g),num__n,num__v
0,kc1,svm,13,hidden_minority_medium,1572,1,1.0,synthetic_boundary_fill,-0.369944,-0.278977,-0.142846,-0.238002,-0.335338,-0.310024
1,kc1,svm,13,hidden_minority_medium,1573,1,1.0,synthetic_boundary_fill,-0.481291,-0.393771,-0.316316,-0.368986,-0.444879,-0.406699
2,kc1,svm,13,hidden_minority_medium,1574,1,1.0,synthetic_boundary_fill,1.446195,1.319443,1.514734,1.585853,1.036442,0.970528
3,kc1,svm,13,hidden_minority_medium,1575,1,1.0,synthetic_boundary_fill,0.549960,1.608229,3.369393,-0.108618,1.456798,1.356845
4,kc1,svm,13,hidden_minority_medium,1576,1,1.0,synthetic_boundary_fill,-0.298550,-0.409580,-0.316316,-0.387024,-0.158919,-0.239659