# COINS Full Benchmark Notebook

Standalone benchmark notebook for COINS with Logistic Regression and SVM.

It implements same-family OOF scoring, CWMS, MSBS, and competitors: No Cleaning, Class-Proportional deletion, SMOTE, IW-SMOTE, and SW-approx.

COINS keeps every original label unchanged. It changes training influence through weights and adds MSBS minority rows.

## Full Run Setup

Default run: 15 cached datasets, LR/SVM, 10 seeds, 3 hidden-minority protocols, 6 methods.

For a quick execution check, launch with environment variable `COINS_SMOKE=1`.

In [1]:
from __future__ import annotations

import os
import time
import warnings
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from scipy.stats import norm, wilcoxon
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, average_precision_score, balanced_accuracy_score, f1_score, precision_score, recall_score
from sklearn.model_selection import StratifiedKFold, train_test_split
from sklearn.neighbors import NearestNeighbors
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", 80)

ROOT = Path.cwd()
DATA_DIR = ROOT / "data"
SMOKE = os.environ.get("COINS_SMOKE", "0") == "1"
print("root", ROOT)
print("smoke", SMOKE)

root /home/than-minh/project/DSP
smoke False

In [2]:
DATA_FILES = {
    "pima": "pima.parquet", "credit-g": "credit-g.parquet", "yeast": "yeast.parquet",
    "ecoli": "ecoli.parquet", "phoneme": "phoneme.parquet", "breast_cancer": "breast_cancer.parquet",
    "ilpd": "ilpd.parquet", "blood": "blood.parquet", "haberman": "haberman.parquet",
    "ionosphere": "ionosphere.parquet", "vehicle_bus": "vehicle_bus.parquet", "glass_float": "glass_float.parquet",
    "abalone": "abalone.parquet", "spambase": "spambase.parquet", "kc1": "kc1.parquet",
}

MINORITY_TEXT = {
    "pima": "tested_positive", "credit-g": "bad", "yeast": "MIT", "ecoli": "im", "phoneme": "nasal",
    "breast_cancer": "malignant", "ilpd": "no_disease", "blood": "donated", "haberman": "died",
    "ionosphere": "bad", "vehicle_bus": "bus", "glass_float": "window_float", "abalone": "rings_gt_10",
    "spambase": "spam", "kc1": "defective",
}

SEEDS_FULL = [13, 17, 23, 29, 31, 37, 41, 43, 47, 53]
PROTOCOLS_FULL = {
    "hidden_minority_low": (0.10, 0.05),
    "hidden_minority_medium": (0.30, 0.10),
    "hidden_minority_high": (0.40, 0.20),
}
MODELS = ["lr", "svm"]
METHODS = ["no_cleaning", "class_proportional", "smote", "iw_smote", "sw_approx", "coins"]
GOAL_MINORITY_RATIO = 0.15
BUDGET_RATIO = 0.10

DATA_NAMES = ["pima"] if SMOKE else list(DATA_FILES)
SEEDS = [13] if SMOKE else SEEDS_FULL
PROTOCOLS = {"hidden_minority_medium": PROTOCOLS_FULL["hidden_minority_medium"]} if SMOKE else PROTOCOLS_FULL

print(DATA_NAMES)
print(SEEDS)
print(PROTOCOLS)

['pima', 'credit-g', 'yeast', 'ecoli', 'phoneme', 'breast_cancer', 'ilpd', 'blood', 'haberman', 'ionosphere', 'vehicle_bus', 'glass_float', 'abalone', 'spambase', 'kc1']
[13, 17, 23, 29, 31, 37, 41, 43, 47, 53]
{'hidden_minority_low': (0.1, 0.05), 'hidden_minority_medium': (0.3, 0.1), 'hidden_minority_high': (0.4, 0.2)}

## Core Data And Model Helpers

In [3]:
def read_data(name: str) -> tuple[pd.DataFrame, np.ndarray]:
    """Load one cached parquet dataset and convert its minority class to label 1.

    The cached files keep the class column as the final column. The notebook uses
    `MINORITY_TEXT` so every dataset follows the same binary convention:
    minority = 1 and majority = 0.
    """
    df = pd.read_parquet(DATA_DIR / DATA_FILES[name])
    label_col = df.columns[-1]
    y = (df[label_col] == MINORITY_TEXT[name]).astype(int).to_numpy()
    X = df.drop(columns=[label_col])
    return X, y


def induce_ratio(
    X: pd.DataFrame,
    y: np.ndarray,
    goal_ratio: float,
    rng: np.random.Generator,
) -> tuple[pd.DataFrame, np.ndarray]:
    """Subsample the minority class to create the requested imbalance ratio.

    The benchmark follows the paper setup: reduce the minority side before noise
    injection so hidden-minority flips can erode an already small class.
    """
    min_idx = np.where(y == 1)[0]
    maj_idx = np.where(y == 0)[0]
    if len(min_idx) / len(y) <= goal_ratio:
        return X.reset_index(drop=True), y.copy()
    keep_min_n = min(len(min_idx), max(2, int((goal_ratio / (1 - goal_ratio)) * len(maj_idx))))
    keep_min = rng.choice(min_idx, size=keep_min_n, replace=False)
    keep = np.concatenate([maj_idx, keep_min])
    rng.shuffle(keep)
    return X.iloc[keep].reset_index(drop=True), y[keep].copy()


def add_noise(
    y_clean: np.ndarray,
    min_to_maj: float,
    maj_to_min: float,
    rng: np.random.Generator,
) -> tuple[np.ndarray, np.ndarray]:
    """Inject asymmetric training-label noise and return noisy labels plus mask.

    `min_to_maj` is the hidden-minority corruption rate. It should be larger
    than `maj_to_min` in the COINS operating condition.
    """
    y = y_clean.copy()
    mask = np.zeros(len(y), dtype=bool)
    for i, val in enumerate(y_clean):
        p = min_to_maj if val == 1 else maj_to_min
        if rng.random() < p:
            y[i] = 1 - y[i]
            mask[i] = True
    return y, mask


def preprocessor_for(X: pd.DataFrame) -> ColumnTransformer:
    """Build a tabular preprocessor for numeric and categorical columns.

    Numeric columns use median imputation and standard scaling. Categorical
    columns use most-frequent imputation and one-hot encoding. The transformed
    array is shared by all benchmark methods for a fair comparison.
    """
    cat = list(X.select_dtypes(include=["object", "category", "bool"]).columns)
    num = [c for c in X.columns if c not in cat]
    try:
        enc = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
    except TypeError:
        enc = OneHotEncoder(handle_unknown="ignore", sparse=False)
    return ColumnTransformer([
        ("num", Pipeline([("imp", SimpleImputer(strategy="median")), ("sc", StandardScaler())]), num),
        ("cat", Pipeline([("imp", SimpleImputer(strategy="most_frequent")), ("oh", enc)]), cat),
    ])


def split_data(
    name: str,
    seed: int,
    min_to_maj: float,
    maj_to_min: float,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Create one benchmark train/test split with imbalance and noisy train labels.

    The test set remains clean. Only the training labels are corrupted, matching
    the paper's controlled hidden-minority noise setup.
    """
    rng = np.random.default_rng(seed)
    X_raw, y_raw = read_data(name)
    X_tr_df, X_te_df, y_tr_clean, y_te = train_test_split(
        X_raw, y_raw, test_size=0.25, stratify=y_raw, random_state=seed
    )
    X_tr_df, y_tr_clean = induce_ratio(X_tr_df.reset_index(drop=True), y_tr_clean, GOAL_MINORITY_RATIO, rng)
    X_te_df = X_te_df.reset_index(drop=True)
    prep = preprocessor_for(X_tr_df)
    X_tr = prep.fit_transform(X_tr_df).astype(float)
    X_te = prep.transform(X_te_df).astype(float)
    y_noisy, noisy_mask = add_noise(y_tr_clean, min_to_maj, maj_to_min, rng)
    return X_tr, X_te, y_tr_clean, y_noisy, y_te, noisy_mask


def make_model(name: str, seed: int, balanced: bool = False) -> LogisticRegression | SVC:
    """Create the LR or SVM model used by the benchmark.

    `balanced=True` is used only for same-family OOF scoring. Final models are
    trained with explicit method-specific data/weights.
    """
    if name == "lr":
        return LogisticRegression(class_weight="balanced" if balanced else None, max_iter=1000, random_state=seed)
    if name == "svm":
        return SVC(kernel="rbf", probability=True, class_weight="balanced" if balanced else None, random_state=seed)
    raise ValueError(name)

In [4]:
def min_scores(model: LogisticRegression | SVC, X: np.ndarray) -> np.ndarray:
    """Return model probability for the minority class label 1."""
    return model.predict_proba(X)[:, list(model.classes_).index(1)]


def metrics_for(model: LogisticRegression | SVC, X_te: np.ndarray, y_te: np.ndarray) -> dict[str, float]:
    """Compute presentation metrics on the clean test set."""
    pred = model.predict(X_te)
    score = min_scores(model, X_te)
    return {
        "balanced_accuracy": balanced_accuracy_score(y_te, pred),
        "accuracy": accuracy_score(y_te, pred),
        "macro_f1": f1_score(y_te, pred, average="macro", zero_division=0),
        "minority_precision": precision_score(y_te, pred, pos_label=1, zero_division=0),
        "minority_recall": recall_score(y_te, pred, pos_label=1, zero_division=0),
        "majority_recall": recall_score(y_te, pred, pos_label=0, zero_division=0),
        "pr_auc": average_precision_score(y_te, score),
    }


def fit_eval(
    X_tr: np.ndarray,
    y_tr: np.ndarray,
    X_te: np.ndarray,
    y_te: np.ndarray,
    model_name: str,
    seed: int,
    weight: np.ndarray | None = None,
) -> dict[str, float]:
    """Fit one final LR/SVM model and evaluate it on clean test data."""
    model = make_model(model_name, seed)
    model.fit(X_tr, y_tr, sample_weight=weight) if weight is not None else model.fit(X_tr, y_tr)
    return metrics_for(model, X_te, y_te)


def oof_loss(X: np.ndarray, y: np.ndarray, model_name: str, seed: int) -> np.ndarray:
    """Compute out-of-fold negative log probability of each observed label.

    Class-proportional deletion uses this as a generic suspiciousness score.
    It is intentionally not COINS-specific.
    """
    out = np.zeros(len(y))
    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=seed)
    for tr, va in cv.split(X, y):
        m = make_model(model_name, seed)
        m.fit(X[tr], y[tr])
        p = m.predict_proba(X[va])
        cols = [list(m.classes_).index(v) for v in y[va]]
        out[va] = -np.log(np.clip(p[np.arange(len(va)), cols], 1e-12, 1.0))
    return out


def same_family_oof(X: np.ndarray, y: np.ndarray, model_name: str, seed: int) -> np.ndarray:
    """Compute COINS same-family OOF minority scores for majority-labeled rows.

    LR final model receives scores from balanced LR. SVM final model receives
    scores from balanced SVM. Minority-labeled rows are set to NaN because COINS
    only scores the majority pool for hidden-minority candidates.
    """
    out = np.full(len(y), np.nan)
    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=seed)
    for tr, va in cv.split(X, y):
        m = make_model(model_name, seed, balanced=True)
        m.fit(X[tr], y[tr])
        out[va] = min_scores(m, X[va])
    out[y == 1] = np.nan
    return out

## COINS And Competitor Implementations

In [5]:
def class_prop(
    X: np.ndarray,
    y: np.ndarray,
    loss: np.ndarray,
    budget: int,
) -> tuple[np.ndarray, np.ndarray, int]:
    """Delete high-loss rows with budget split proportionally by observed class."""
    selected: list[int] = []
    for lab in np.unique(y):
        idx = np.where(y == lab)[0]
        n = max(1, int(round(budget * len(idx) / len(y))))
        selected.extend(idx[np.argsort(loss[idx])[::-1]][:n].tolist())
    selected = np.array(selected[:budget], dtype=int)
    keep = np.ones(len(y), dtype=bool)
    keep[selected] = False
    return X[keep], y[keep], len(selected)


def msbs(
    X: np.ndarray,
    y: np.ndarray,
    scores: np.ndarray,
    budget: int,
    seed: int,
) -> tuple[np.ndarray, np.ndarray, int]:
    """Generate MSBS synthetic minority rows near suspicious majority seeds.

    Anchors come from observed minority rows. Seeds come from majority-labeled
    rows with probability proportional to their OOF minority score.
    """
    rng = np.random.default_rng(seed)
    min_idx = np.where(y == 1)[0]
    maj_idx = np.where(y == 0)[0]
    if len(min_idx) == 0 or len(maj_idx) == 0:
        return X.copy(), y.copy(), 0
    vals = np.nan_to_num(scores[maj_idx], nan=0.0)
    probs = np.full(len(maj_idx), 1 / len(maj_idx)) if vals.sum() <= 0 else vals / vals.sum()
    synth: list[np.ndarray] = []
    for _ in range(budget):
        a = X[rng.choice(min_idx)]
        b = X[rng.choice(maj_idx, p=probs)]
        lam = rng.random()
        synth.append(a + lam * (b - a))
    return np.vstack([X, np.asarray(synth)]), np.concatenate([y, np.ones(len(synth), dtype=int)]), len(synth)


def coins_run(
    X: np.ndarray,
    y: np.ndarray,
    X_te: np.ndarray,
    y_te: np.ndarray,
    model_name: str,
    seed: int,
    budget: int,
) -> dict[str, float]:
    """Run full COINS: same-family OOF scoring, CWMS weights, and MSBS rows."""
    scores = same_family_oof(X, y, model_name, seed)
    X_aug, y_aug, n = msbs(X, y, scores, budget, seed)
    w = np.ones(len(y))
    maj = y == 0
    w[maj] = 1 - np.nan_to_num(scores[maj], nan=0.0)
    weight = np.concatenate([np.clip(w, 0, 1), np.ones(n)])
    ans = fit_eval(X_aug, y_aug, X_te, y_te, model_name, seed, weight)
    ans.update({"n_synthetic": n, "deleted": 0, "mean_cwms_weight": float(w.mean())})
    return ans


def smote_run(
    X: np.ndarray,
    y: np.ndarray,
    X_te: np.ndarray,
    y_te: np.ndarray,
    model_name: str,
    seed: int,
    budget: int,
) -> dict[str, float]:
    """Run standard SMOTE with the same synthetic-sample budget as COINS."""
    from imblearn.over_sampling import SMOTE
    n_min = int((y == 1).sum())
    n_maj = int((y == 0).sum())
    goal = min(n_min + budget, n_maj)
    if n_min < 2 or goal <= n_min:
        ans = fit_eval(X, y, X_te, y_te, model_name, seed)
        ans.update({"n_synthetic": 0, "deleted": 0})
        return ans
    sampler = SMOTE(sampling_strategy={1: goal}, k_neighbors=min(5, n_min - 1), random_state=seed)
    X_aug, y_aug = sampler.fit_resample(X, y)
    ans = fit_eval(X_aug, y_aug, X_te, y_te, model_name, seed)
    ans.update({"n_synthetic": len(y_aug) - len(y), "deleted": 0})
    return ans

In [6]:
def iw_smote_gen(
    X: np.ndarray,
    y: np.ndarray,
    budget: int,
    seed: int,
    lamda: int = 30,
) -> tuple[np.ndarray, np.ndarray, int]:
    """Generate IW-SMOTE samples using an under-bagged tree noise filter.

    This is a compact notebook implementation of the repository baseline. It
    filters high-error rows, then allocates synthesis to retained minority rows
    according to their ensemble error rate.
    """
    rng = np.random.default_rng(seed)
    min_idx = np.where(y == 1)[0]
    maj_idx = np.where(y == 0)[0]
    if len(min_idx) < 2 or len(maj_idx) < 1:
        return X.copy(), y.copy(), 0
    Xm, XM = X[min_idx], X[maj_idx]
    n_trees = max(1, int((len(XM) / len(Xm)) * lamda))
    pm = np.empty((len(Xm), n_trees), dtype=int)
    pM = np.empty((len(XM), n_trees), dtype=int)
    for i in range(n_trees):
        n = max(1, len(Xm) // 2)
        im = rng.choice(len(Xm), n, replace=False)
        iM = rng.choice(len(XM), n, replace=True)
        tree = DecisionTreeClassifier(random_state=int(rng.integers(0, 10000)))
        tree.fit(np.vstack([Xm[im], XM[iM]]), np.concatenate([np.ones(n), np.zeros(n)]))
        pm[:, i] = tree.predict(Xm)
        pM[:, i] = tree.predict(XM)
    em = (pm != 1).mean(axis=1)
    eM = (pM != 0).mean(axis=1)
    Xm2, XM2, em2 = Xm[em < 0.5], XM[eM < 0.5], em[em < 0.5]
    if len(Xm2) < 2:
        return np.vstack([XM2, Xm2]), np.concatenate([np.zeros(len(XM2)), np.ones(len(Xm2))]).astype(int), 0
    n_new = min(budget, max(0, len(XM2) - len(Xm2)))
    if n_new <= 0:
        return np.vstack([XM2, Xm2]), np.concatenate([np.zeros(len(XM2)), np.ones(len(Xm2))]).astype(int), 0
    weights = np.maximum(em2, 1 / n_trees)
    weights = weights / weights.sum()
    counts = (weights * n_new).astype(int)
    counts[np.argsort(weights)[::-1][: n_new - counts.sum()]] += 1
    synth: list[np.ndarray] = []
    for i, c in enumerate(counts):
        if c <= 0:
            continue
        d = np.linalg.norm(Xm2 - Xm2[i], axis=1)
        d[i] = np.inf
        nn = np.argsort(d)[: min(5, len(Xm2) - 1)]
        for _ in range(c):
            nb = Xm2[rng.choice(nn)]
            alpha = rng.random()
            synth.append(Xm2[i] + alpha * (nb - Xm2[i]))
    X_aug = np.vstack([XM2, Xm2, np.asarray(synth)]) if synth else np.vstack([XM2, Xm2])
    y_aug = np.concatenate([np.zeros(len(XM2)), np.ones(len(Xm2) + len(synth))]).astype(int)
    return X_aug, y_aug, len(synth)


def sw_gen(X: np.ndarray, y: np.ndarray, budget: int, seed: int) -> tuple[np.ndarray, np.ndarray, int]:
    """Generate SW-approx samples using RF leaf proximity as chaos proxy.

    The original SW Framework has no public code in this project. This notebook
    uses the repository's approximation: cleaner minority rows in RF-proximity
    neighborhoods receive more synthetic samples.
    """
    rng = np.random.default_rng(seed)
    min_idx = np.where(y == 1)[0]
    if len(min_idx) < 2:
        return X.copy(), y.copy(), 0
    rf = RandomForestClassifier(n_estimators=100, random_state=seed, n_jobs=1)
    rf.fit(X, y)
    leaves = rf.apply(X)
    nn = NearestNeighbors(n_neighbors=min(6, len(X))).fit(leaves)
    _, near = nn.kneighbors(leaves[min_idx])
    chaos = np.array([np.mean(y[row[1:]] != 1) for row in near])
    weights = np.maximum(1 - chaos, 0.05)
    weights = weights / weights.sum()
    n_min, n_maj = len(min_idx), int((y == 0).sum())
    n_new = max(0, min(n_min + budget, n_maj) - n_min)
    if n_new <= 0:
        return X.copy(), y.copy(), 0
    counts = (weights * n_new).astype(int)
    counts[np.argsort(weights)[::-1][: n_new - counts.sum()]] += 1
    Xm = X[min_idx]
    synth: list[np.ndarray] = []
    for i, c in enumerate(counts):
        if c <= 0:
            continue
        d = np.linalg.norm(Xm - Xm[i], axis=1)
        d[i] = np.inf
        near2 = np.argsort(d)[: min(5, n_min - 1)]
        for _ in range(c):
            nb = Xm[rng.choice(near2)]
            alpha = rng.random()
            synth.append(Xm[i] + alpha * (nb - Xm[i]))
    return np.vstack([X, np.asarray(synth)]), np.concatenate([y, np.ones(len(synth), dtype=int)]), len(synth)

In [7]:
def run_method(
    method: str,
    X: np.ndarray,
    y: np.ndarray,
    X_te: np.ndarray,
    y_te: np.ndarray,
    model_name: str,
    seed: int,
    budget: int,
) -> dict[str, Any]:
    """Dispatch one benchmark method for one train/test split."""
    if method == "no_cleaning":
        ans = fit_eval(X, y, X_te, y_te, model_name, seed)
        ans.update({"n_synthetic": 0, "deleted": 0})
        return ans
    if method == "class_proportional":
        X2, y2, deleted = class_prop(X, y, oof_loss(X, y, model_name, seed), budget)
        ans = fit_eval(X2, y2, X_te, y_te, model_name, seed)
        ans.update({"n_synthetic": 0, "deleted": deleted})
        return ans
    if method == "smote":
        return smote_run(X, y, X_te, y_te, model_name, seed, budget)
    if method == "iw_smote":
        X2, y2, n = iw_smote_gen(X, y, budget, seed)
        ans = fit_eval(X2, y2, X_te, y_te, model_name, seed)
        ans.update({"n_synthetic": n, "deleted": max(0, len(y) - (len(y2) - n))})
        return ans
    if method == "sw_approx":
        X2, y2, n = sw_gen(X, y, budget, seed)
        ans = fit_eval(X2, y2, X_te, y_te, model_name, seed)
        ans.update({"n_synthetic": n, "deleted": 0})
        return ans
    if method == "coins":
        return coins_run(X, y, X_te, y_te, model_name, seed, budget)
    raise ValueError(method)


def run_combo(
    data_name: str,
    model_name: str,
    seed: int,
    proto_name: str,
    mn: float,
    mj: float,
) -> list[dict[str, Any]]:
    """Run every method for one dataset/model/seed/noise-protocol combination."""
    X, X_te, y_clean, y_noisy, y_te, mask = split_data(data_name, seed, mn, mj)
    budget = max(1, int(round(BUDGET_RATIO * len(y_noisy))))
    rows: list[dict[str, Any]] = []
    for method in METHODS:
        t0 = time.time()
        try:
            ans = run_method(method, X, y_noisy, X_te, y_te, model_name, seed, budget)
            err = ""
        except Exception as exc:
            ans = {k: np.nan for k in ["balanced_accuracy", "accuracy", "macro_f1", "minority_precision", "minority_recall", "majority_recall", "pr_auc"]}
            ans.update({"n_synthetic": 0, "deleted": 0})
            err = repr(exc)
        rows.append({
            "dataset": data_name,
            "model": model_name,
            "seed": seed,
            "noise_protocol": proto_name,
            "mn_to_maj": mn,
            "maj_to_min": mj,
            "method": method,
            "train_rows": len(y_noisy),
            "test_rows": len(y_te),
            "budget_count": budget,
            "true_noise_rate": float(mask.mean()),
            "runtime_sec": time.time() - t0,
            "error": err,
            **ans,
        })
    return rows

## Execute Benchmark

This cell stores results in memory and does not write CSV files.

In [8]:
rows = []
total = len(DATA_NAMES) * len(MODELS) * len(SEEDS) * len(PROTOCOLS)
i = 0
start = time.time()
for data_name in DATA_NAMES:
    for model_name in MODELS:
        for seed in SEEDS:
            for proto_name, (mn, mj) in PROTOCOLS.items():
                i += 1
                print(f"[{i}/{total}] {data_name} {model_name} seed={seed} {proto_name}", flush=True)
                rows.extend(run_combo(data_name, model_name, seed, proto_name, mn, mj))
results = pd.DataFrame(rows)
print("rows", len(results), "minutes", round((time.time() - start) / 60, 2))
results.head()

[1/900] pima lr seed=13 hidden_minority_low

[2/900] pima lr seed=13 hidden_minority_medium

[3/900] pima lr seed=13 hidden_minority_high

[4/900] pima lr seed=17 hidden_minority_low

[5/900] pima lr seed=17 hidden_minority_medium

[6/900] pima lr seed=17 hidden_minority_high

[7/900] pima lr seed=23 hidden_minority_low

[8/900] pima lr seed=23 hidden_minority_medium

[9/900] pima lr seed=23 hidden_minority_high

[10/900] pima lr seed=29 hidden_minority_low

[11/900] pima lr seed=29 hidden_minority_medium

[12/900] pima lr seed=29 hidden_minority_high

[13/900] pima lr seed=31 hidden_minority_low

[14/900] pima lr seed=31 hidden_minority_medium

[15/900] pima lr seed=31 hidden_minority_high

[16/900] pima lr seed=37 hidden_minority_low

[17/900] pima lr seed=37 hidden_minority_medium

[18/900] pima lr seed=37 hidden_minority_high

[19/900] pima lr seed=41 hidden_minority_low

[20/900] pima lr seed=41 hidden_minority_medium

[21/900] pima lr seed=41 hidden_minority_high

[22/900] pima lr seed=43 hidden_minority_low

[23/900] pima lr seed=43 hidden_minority_medium

[24/900] pima lr seed=43 hidden_minority_high

[25/900] pima lr seed=47 hidden_minority_low

[26/900] pima lr seed=47 hidden_minority_medium

[27/900] pima lr seed=47 hidden_minority_high

[28/900] pima lr seed=53 hidden_minority_low

[29/900] pima lr seed=53 hidden_minority_medium

[30/900] pima lr seed=53 hidden_minority_high

[31/900] pima svm seed=13 hidden_minority_low

[32/900] pima svm seed=13 hidden_minority_medium

[33/900] pima svm seed=13 hidden_minority_high

[34/900] pima svm seed=17 hidden_minority_low

[35/900] pima svm seed=17 hidden_minority_medium

[36/900] pima svm seed=17 hidden_minority_high

[37/900] pima svm seed=23 hidden_minority_low

[38/900] pima svm seed=23 hidden_minority_medium

[39/900] pima svm seed=23 hidden_minority_high

[40/900] pima svm seed=29 hidden_minority_low

[41/900] pima svm seed=29 hidden_minority_medium

[42/900] pima svm seed=29 hidden_minority_high

[43/900] pima svm seed=31 hidden_minority_low

[44/900] pima svm seed=31 hidden_minority_medium

[45/900] pima svm seed=31 hidden_minority_high

[46/900] pima svm seed=37 hidden_minority_low

[47/900] pima svm seed=37 hidden_minority_medium

[48/900] pima svm seed=37 hidden_minority_high

[49/900] pima svm seed=41 hidden_minority_low

[50/900] pima svm seed=41 hidden_minority_medium

[51/900] pima svm seed=41 hidden_minority_high

[52/900] pima svm seed=43 hidden_minority_low

[53/900] pima svm seed=43 hidden_minority_medium

[54/900] pima svm seed=43 hidden_minority_high

[55/900] pima svm seed=47 hidden_minority_low

[56/900] pima svm seed=47 hidden_minority_medium

[57/900] pima svm seed=47 hidden_minority_high

[58/900] pima svm seed=53 hidden_minority_low

[59/900] pima svm seed=53 hidden_minority_medium

[60/900] pima svm seed=53 hidden_minority_high

[61/900] credit-g lr seed=13 hidden_minority_low

[62/900] credit-g lr seed=13 hidden_minority_medium

[63/900] credit-g lr seed=13 hidden_minority_high

[64/900] credit-g lr seed=17 hidden_minority_low

[65/900] credit-g lr seed=17 hidden_minority_medium

[66/900] credit-g lr seed=17 hidden_minority_high

[67/900] credit-g lr seed=23 hidden_minority_low

[68/900] credit-g lr seed=23 hidden_minority_medium

[69/900] credit-g lr seed=23 hidden_minority_high

[70/900] credit-g lr seed=29 hidden_minority_low

[71/900] credit-g lr seed=29 hidden_minority_medium

[72/900] credit-g lr seed=29 hidden_minority_high

[73/900] credit-g lr seed=31 hidden_minority_low

[74/900] credit-g lr seed=31 hidden_minority_medium

[75/900] credit-g lr seed=31 hidden_minority_high

[76/900] credit-g lr seed=37 hidden_minority_low

[77/900] credit-g lr seed=37 hidden_minority_medium

[78/900] credit-g lr seed=37 hidden_minority_high

[79/900] credit-g lr seed=41 hidden_minority_low

[80/900] credit-g lr seed=41 hidden_minority_medium

[81/900] credit-g lr seed=41 hidden_minority_high

[82/900] credit-g lr seed=43 hidden_minority_low

[83/900] credit-g lr seed=43 hidden_minority_medium

[84/900] credit-g lr seed=43 hidden_minority_high

[85/900] credit-g lr seed=47 hidden_minority_low

[86/900] credit-g lr seed=47 hidden_minority_medium

[87/900] credit-g lr seed=47 hidden_minority_high

[88/900] credit-g lr seed=53 hidden_minority_low

[89/900] credit-g lr seed=53 hidden_minority_medium

[90/900] credit-g lr seed=53 hidden_minority_high

[91/900] credit-g svm seed=13 hidden_minority_low

[92/900] credit-g svm seed=13 hidden_minority_medium

[93/900] credit-g svm seed=13 hidden_minority_high

[94/900] credit-g svm seed=17 hidden_minority_low

[95/900] credit-g svm seed=17 hidden_minority_medium

[96/900] credit-g svm seed=17 hidden_minority_high

[97/900] credit-g svm seed=23 hidden_minority_low

[98/900] credit-g svm seed=23 hidden_minority_medium

[99/900] credit-g svm seed=23 hidden_minority_high

[100/900] credit-g svm seed=29 hidden_minority_low

[101/900] credit-g svm seed=29 hidden_minority_medium

[102/900] credit-g svm seed=29 hidden_minority_high

[103/900] credit-g svm seed=31 hidden_minority_low

[104/900] credit-g svm seed=31 hidden_minority_medium

[105/900] credit-g svm seed=31 hidden_minority_high

[106/900] credit-g svm seed=37 hidden_minority_low

[107/900] credit-g svm seed=37 hidden_minority_medium

[108/900] credit-g svm seed=37 hidden_minority_high

[109/900] credit-g svm seed=41 hidden_minority_low

[110/900] credit-g svm seed=41 hidden_minority_medium

[111/900] credit-g svm seed=41 hidden_minority_high

[112/900] credit-g svm seed=43 hidden_minority_low

[113/900] credit-g svm seed=43 hidden_minority_medium

[114/900] credit-g svm seed=43 hidden_minority_high

[115/900] credit-g svm seed=47 hidden_minority_low

[116/900] credit-g svm seed=47 hidden_minority_medium

[117/900] credit-g svm seed=47 hidden_minority_high

[118/900] credit-g svm seed=53 hidden_minority_low

[119/900] credit-g svm seed=53 hidden_minority_medium

[120/900] credit-g svm seed=53 hidden_minority_high

[121/900] yeast lr seed=13 hidden_minority_low

[122/900] yeast lr seed=13 hidden_minority_medium

[123/900] yeast lr seed=13 hidden_minority_high

[124/900] yeast lr seed=17 hidden_minority_low

[125/900] yeast lr seed=17 hidden_minority_medium

[126/900] yeast lr seed=17 hidden_minority_high

[127/900] yeast lr seed=23 hidden_minority_low

[128/900] yeast lr seed=23 hidden_minority_medium

[129/900] yeast lr seed=23 hidden_minority_high

[130/900] yeast lr seed=29 hidden_minority_low

[131/900] yeast lr seed=29 hidden_minority_medium

[132/900] yeast lr seed=29 hidden_minority_high

[133/900] yeast lr seed=31 hidden_minority_low

[134/900] yeast lr seed=31 hidden_minority_medium

[135/900] yeast lr seed=31 hidden_minority_high

[136/900] yeast lr seed=37 hidden_minority_low

[137/900] yeast lr seed=37 hidden_minority_medium

[138/900] yeast lr seed=37 hidden_minority_high

[139/900] yeast lr seed=41 hidden_minority_low

[140/900] yeast lr seed=41 hidden_minority_medium

[141/900] yeast lr seed=41 hidden_minority_high

[142/900] yeast lr seed=43 hidden_minority_low

[143/900] yeast lr seed=43 hidden_minority_medium

[144/900] yeast lr seed=43 hidden_minority_high

[145/900] yeast lr seed=47 hidden_minority_low

[146/900] yeast lr seed=47 hidden_minority_medium

[147/900] yeast lr seed=47 hidden_minority_high

[148/900] yeast lr seed=53 hidden_minority_low

[149/900] yeast lr seed=53 hidden_minority_medium

[150/900] yeast lr seed=53 hidden_minority_high

[151/900] yeast svm seed=13 hidden_minority_low

[152/900] yeast svm seed=13 hidden_minority_medium

[153/900] yeast svm seed=13 hidden_minority_high

[154/900] yeast svm seed=17 hidden_minority_low

[155/900] yeast svm seed=17 hidden_minority_medium

[156/900] yeast svm seed=17 hidden_minority_high

[157/900] yeast svm seed=23 hidden_minority_low

[158/900] yeast svm seed=23 hidden_minority_medium

[159/900] yeast svm seed=23 hidden_minority_high

[160/900] yeast svm seed=29 hidden_minority_low

[161/900] yeast svm seed=29 hidden_minority_medium

[162/900] yeast svm seed=29 hidden_minority_high

[163/900] yeast svm seed=31 hidden_minority_low

[164/900] yeast svm seed=31 hidden_minority_medium

[165/900] yeast svm seed=31 hidden_minority_high

[166/900] yeast svm seed=37 hidden_minority_low

[167/900] yeast svm seed=37 hidden_minority_medium

[168/900] yeast svm seed=37 hidden_minority_high

[169/900] yeast svm seed=41 hidden_minority_low

[170/900] yeast svm seed=41 hidden_minority_medium

[171/900] yeast svm seed=41 hidden_minority_high

[172/900] yeast svm seed=43 hidden_minority_low

[173/900] yeast svm seed=43 hidden_minority_medium

[174/900] yeast svm seed=43 hidden_minority_high

[175/900] yeast svm seed=47 hidden_minority_low

[176/900] yeast svm seed=47 hidden_minority_medium

[177/900] yeast svm seed=47 hidden_minority_high

[178/900] yeast svm seed=53 hidden_minority_low

[179/900] yeast svm seed=53 hidden_minority_medium

[180/900] yeast svm seed=53 hidden_minority_high

[181/900] ecoli lr seed=13 hidden_minority_low

[182/900] ecoli lr seed=13 hidden_minority_medium

[183/900] ecoli lr seed=13 hidden_minority_high

[184/900] ecoli lr seed=17 hidden_minority_low

[185/900] ecoli lr seed=17 hidden_minority_medium

[186/900] ecoli lr seed=17 hidden_minority_high

[187/900] ecoli lr seed=23 hidden_minority_low

[188/900] ecoli lr seed=23 hidden_minority_medium

[189/900] ecoli lr seed=23 hidden_minority_high

[190/900] ecoli lr seed=29 hidden_minority_low

[191/900] ecoli lr seed=29 hidden_minority_medium

[192/900] ecoli lr seed=29 hidden_minority_high

[193/900] ecoli lr seed=31 hidden_minority_low

[194/900] ecoli lr seed=31 hidden_minority_medium

[195/900] ecoli lr seed=31 hidden_minority_high

[196/900] ecoli lr seed=37 hidden_minority_low

[197/900] ecoli lr seed=37 hidden_minority_medium

[198/900] ecoli lr seed=37 hidden_minority_high

[199/900] ecoli lr seed=41 hidden_minority_low

[200/900] ecoli lr seed=41 hidden_minority_medium

[201/900] ecoli lr seed=41 hidden_minority_high

[202/900] ecoli lr seed=43 hidden_minority_low

[203/900] ecoli lr seed=43 hidden_minority_medium

[204/900] ecoli lr seed=43 hidden_minority_high

[205/900] ecoli lr seed=47 hidden_minority_low

[206/900] ecoli lr seed=47 hidden_minority_medium

[207/900] ecoli lr seed=47 hidden_minority_high

[208/900] ecoli lr seed=53 hidden_minority_low

[209/900] ecoli lr seed=53 hidden_minority_medium

[210/900] ecoli lr seed=53 hidden_minority_high

[211/900] ecoli svm seed=13 hidden_minority_low

[212/900] ecoli svm seed=13 hidden_minority_medium

[213/900] ecoli svm seed=13 hidden_minority_high

[214/900] ecoli svm seed=17 hidden_minority_low

[215/900] ecoli svm seed=17 hidden_minority_medium

[216/900] ecoli svm seed=17 hidden_minority_high

[217/900] ecoli svm seed=23 hidden_minority_low

[218/900] ecoli svm seed=23 hidden_minority_medium

[219/900] ecoli svm seed=23 hidden_minority_high

[220/900] ecoli svm seed=29 hidden_minority_low

[221/900] ecoli svm seed=29 hidden_minority_medium

[222/900] ecoli svm seed=29 hidden_minority_high

[223/900] ecoli svm seed=31 hidden_minority_low

[224/900] ecoli svm seed=31 hidden_minority_medium

[225/900] ecoli svm seed=31 hidden_minority_high

[226/900] ecoli svm seed=37 hidden_minority_low

[227/900] ecoli svm seed=37 hidden_minority_medium

[228/900] ecoli svm seed=37 hidden_minority_high

[229/900] ecoli svm seed=41 hidden_minority_low

[230/900] ecoli svm seed=41 hidden_minority_medium

[231/900] ecoli svm seed=41 hidden_minority_high

[232/900] ecoli svm seed=43 hidden_minority_low

[233/900] ecoli svm seed=43 hidden_minority_medium

[234/900] ecoli svm seed=43 hidden_minority_high

[235/900] ecoli svm seed=47 hidden_minority_low

[236/900] ecoli svm seed=47 hidden_minority_medium

[237/900] ecoli svm seed=47 hidden_minority_high

[238/900] ecoli svm seed=53 hidden_minority_low

[239/900] ecoli svm seed=53 hidden_minority_medium

[240/900] ecoli svm seed=53 hidden_minority_high

[241/900] phoneme lr seed=13 hidden_minority_low

[242/900] phoneme lr seed=13 hidden_minority_medium

[243/900] phoneme lr seed=13 hidden_minority_high

[244/900] phoneme lr seed=17 hidden_minority_low

[245/900] phoneme lr seed=17 hidden_minority_medium

[246/900] phoneme lr seed=17 hidden_minority_high

[247/900] phoneme lr seed=23 hidden_minority_low

[248/900] phoneme lr seed=23 hidden_minority_medium

[249/900] phoneme lr seed=23 hidden_minority_high

[250/900] phoneme lr seed=29 hidden_minority_low

[251/900] phoneme lr seed=29 hidden_minority_medium

[252/900] phoneme lr seed=29 hidden_minority_high

[253/900] phoneme lr seed=31 hidden_minority_low

[254/900] phoneme lr seed=31 hidden_minority_medium

[255/900] phoneme lr seed=31 hidden_minority_high

[256/900] phoneme lr seed=37 hidden_minority_low

[257/900] phoneme lr seed=37 hidden_minority_medium

[258/900] phoneme lr seed=37 hidden_minority_high

[259/900] phoneme lr seed=41 hidden_minority_low

[260/900] phoneme lr seed=41 hidden_minority_medium

[261/900] phoneme lr seed=41 hidden_minority_high

[262/900] phoneme lr seed=43 hidden_minority_low

[263/900] phoneme lr seed=43 hidden_minority_medium

[264/900] phoneme lr seed=43 hidden_minority_high

[265/900] phoneme lr seed=47 hidden_minority_low

[266/900] phoneme lr seed=47 hidden_minority_medium

[267/900] phoneme lr seed=47 hidden_minority_high

[268/900] phoneme lr seed=53 hidden_minority_low

[269/900] phoneme lr seed=53 hidden_minority_medium

[270/900] phoneme lr seed=53 hidden_minority_high

[271/900] phoneme svm seed=13 hidden_minority_low

[272/900] phoneme svm seed=13 hidden_minority_medium

[273/900] phoneme svm seed=13 hidden_minority_high

[274/900] phoneme svm seed=17 hidden_minority_low

[275/900] phoneme svm seed=17 hidden_minority_medium

[276/900] phoneme svm seed=17 hidden_minority_high

[277/900] phoneme svm seed=23 hidden_minority_low

[278/900] phoneme svm seed=23 hidden_minority_medium

[279/900] phoneme svm seed=23 hidden_minority_high

[280/900] phoneme svm seed=29 hidden_minority_low

[281/900] phoneme svm seed=29 hidden_minority_medium

[282/900] phoneme svm seed=29 hidden_minority_high

[283/900] phoneme svm seed=31 hidden_minority_low

[284/900] phoneme svm seed=31 hidden_minority_medium

[285/900] phoneme svm seed=31 hidden_minority_high

[286/900] phoneme svm seed=37 hidden_minority_low

[287/900] phoneme svm seed=37 hidden_minority_medium

[288/900] phoneme svm seed=37 hidden_minority_high

[289/900] phoneme svm seed=41 hidden_minority_low

[290/900] phoneme svm seed=41 hidden_minority_medium

[291/900] phoneme svm seed=41 hidden_minority_high

[292/900] phoneme svm seed=43 hidden_minority_low

[293/900] phoneme svm seed=43 hidden_minority_medium

[294/900] phoneme svm seed=43 hidden_minority_high

[295/900] phoneme svm seed=47 hidden_minority_low

[296/900] phoneme svm seed=47 hidden_minority_medium

[297/900] phoneme svm seed=47 hidden_minority_high

[298/900] phoneme svm seed=53 hidden_minority_low

[299/900] phoneme svm seed=53 hidden_minority_medium

[300/900] phoneme svm seed=53 hidden_minority_high

[301/900] breast_cancer lr seed=13 hidden_minority_low

[302/900] breast_cancer lr seed=13 hidden_minority_medium

[303/900] breast_cancer lr seed=13 hidden_minority_high

[304/900] breast_cancer lr seed=17 hidden_minority_low

[305/900] breast_cancer lr seed=17 hidden_minority_medium

[306/900] breast_cancer lr seed=17 hidden_minority_high

[307/900] breast_cancer lr seed=23 hidden_minority_low

[308/900] breast_cancer lr seed=23 hidden_minority_medium

[309/900] breast_cancer lr seed=23 hidden_minority_high

[310/900] breast_cancer lr seed=29 hidden_minority_low

[311/900] breast_cancer lr seed=29 hidden_minority_medium

[312/900] breast_cancer lr seed=29 hidden_minority_high

[313/900] breast_cancer lr seed=31 hidden_minority_low

[314/900] breast_cancer lr seed=31 hidden_minority_medium

[315/900] breast_cancer lr seed=31 hidden_minority_high

[316/900] breast_cancer lr seed=37 hidden_minority_low

[317/900] breast_cancer lr seed=37 hidden_minority_medium

[318/900] breast_cancer lr seed=37 hidden_minority_high

[319/900] breast_cancer lr seed=41 hidden_minority_low

[320/900] breast_cancer lr seed=41 hidden_minority_medium

[321/900] breast_cancer lr seed=41 hidden_minority_high

[322/900] breast_cancer lr seed=43 hidden_minority_low

[323/900] breast_cancer lr seed=43 hidden_minority_medium

[324/900] breast_cancer lr seed=43 hidden_minority_high

[325/900] breast_cancer lr seed=47 hidden_minority_low

[326/900] breast_cancer lr seed=47 hidden_minority_medium

[327/900] breast_cancer lr seed=47 hidden_minority_high

[328/900] breast_cancer lr seed=53 hidden_minority_low

[329/900] breast_cancer lr seed=53 hidden_minority_medium

[330/900] breast_cancer lr seed=53 hidden_minority_high

[331/900] breast_cancer svm seed=13 hidden_minority_low

[332/900] breast_cancer svm seed=13 hidden_minority_medium

[333/900] breast_cancer svm seed=13 hidden_minority_high

[334/900] breast_cancer svm seed=17 hidden_minority_low

[335/900] breast_cancer svm seed=17 hidden_minority_medium

[336/900] breast_cancer svm seed=17 hidden_minority_high

[337/900] breast_cancer svm seed=23 hidden_minority_low

[338/900] breast_cancer svm seed=23 hidden_minority_medium

[339/900] breast_cancer svm seed=23 hidden_minority_high

[340/900] breast_cancer svm seed=29 hidden_minority_low

[341/900] breast_cancer svm seed=29 hidden_minority_medium

[342/900] breast_cancer svm seed=29 hidden_minority_high

[343/900] breast_cancer svm seed=31 hidden_minority_low

[344/900] breast_cancer svm seed=31 hidden_minority_medium

[345/900] breast_cancer svm seed=31 hidden_minority_high

[346/900] breast_cancer svm seed=37 hidden_minority_low

[347/900] breast_cancer svm seed=37 hidden_minority_medium

[348/900] breast_cancer svm seed=37 hidden_minority_high

[349/900] breast_cancer svm seed=41 hidden_minority_low

[350/900] breast_cancer svm seed=41 hidden_minority_medium

[351/900] breast_cancer svm seed=41 hidden_minority_high

[352/900] breast_cancer svm seed=43 hidden_minority_low

[353/900] breast_cancer svm seed=43 hidden_minority_medium

[354/900] breast_cancer svm seed=43 hidden_minority_high

[355/900] breast_cancer svm seed=47 hidden_minority_low

[356/900] breast_cancer svm seed=47 hidden_minority_medium

[357/900] breast_cancer svm seed=47 hidden_minority_high

[358/900] breast_cancer svm seed=53 hidden_minority_low

[359/900] breast_cancer svm seed=53 hidden_minority_medium

[360/900] breast_cancer svm seed=53 hidden_minority_high

[361/900] ilpd lr seed=13 hidden_minority_low

[362/900] ilpd lr seed=13 hidden_minority_medium

[363/900] ilpd lr seed=13 hidden_minority_high

[364/900] ilpd lr seed=17 hidden_minority_low

[365/900] ilpd lr seed=17 hidden_minority_medium

[366/900] ilpd lr seed=17 hidden_minority_high

[367/900] ilpd lr seed=23 hidden_minority_low

[368/900] ilpd lr seed=23 hidden_minority_medium

[369/900] ilpd lr seed=23 hidden_minority_high

[370/900] ilpd lr seed=29 hidden_minority_low

[371/900] ilpd lr seed=29 hidden_minority_medium

[372/900] ilpd lr seed=29 hidden_minority_high

[373/900] ilpd lr seed=31 hidden_minority_low

[374/900] ilpd lr seed=31 hidden_minority_medium

[375/900] ilpd lr seed=31 hidden_minority_high

[376/900] ilpd lr seed=37 hidden_minority_low

[377/900] ilpd lr seed=37 hidden_minority_medium

[378/900] ilpd lr seed=37 hidden_minority_high

[379/900] ilpd lr seed=41 hidden_minority_low

[380/900] ilpd lr seed=41 hidden_minority_medium

[381/900] ilpd lr seed=41 hidden_minority_high

[382/900] ilpd lr seed=43 hidden_minority_low

[383/900] ilpd lr seed=43 hidden_minority_medium

[384/900] ilpd lr seed=43 hidden_minority_high

[385/900] ilpd lr seed=47 hidden_minority_low

[386/900] ilpd lr seed=47 hidden_minority_medium

[387/900] ilpd lr seed=47 hidden_minority_high

[388/900] ilpd lr seed=53 hidden_minority_low

[389/900] ilpd lr seed=53 hidden_minority_medium

[390/900] ilpd lr seed=53 hidden_minority_high

[391/900] ilpd svm seed=13 hidden_minority_low

[392/900] ilpd svm seed=13 hidden_minority_medium

[393/900] ilpd svm seed=13 hidden_minority_high

[394/900] ilpd svm seed=17 hidden_minority_low

[395/900] ilpd svm seed=17 hidden_minority_medium

[396/900] ilpd svm seed=17 hidden_minority_high

[397/900] ilpd svm seed=23 hidden_minority_low

[398/900] ilpd svm seed=23 hidden_minority_medium

[399/900] ilpd svm seed=23 hidden_minority_high

[400/900] ilpd svm seed=29 hidden_minority_low

[401/900] ilpd svm seed=29 hidden_minority_medium

[402/900] ilpd svm seed=29 hidden_minority_high

[403/900] ilpd svm seed=31 hidden_minority_low

[404/900] ilpd svm seed=31 hidden_minority_medium

[405/900] ilpd svm seed=31 hidden_minority_high

[406/900] ilpd svm seed=37 hidden_minority_low

[407/900] ilpd svm seed=37 hidden_minority_medium

[408/900] ilpd svm seed=37 hidden_minority_high

[409/900] ilpd svm seed=41 hidden_minority_low

[410/900] ilpd svm seed=41 hidden_minority_medium

[411/900] ilpd svm seed=41 hidden_minority_high

[412/900] ilpd svm seed=43 hidden_minority_low

[413/900] ilpd svm seed=43 hidden_minority_medium

[414/900] ilpd svm seed=43 hidden_minority_high

[415/900] ilpd svm seed=47 hidden_minority_low

[416/900] ilpd svm seed=47 hidden_minority_medium

[417/900] ilpd svm seed=47 hidden_minority_high

[418/900] ilpd svm seed=53 hidden_minority_low

[419/900] ilpd svm seed=53 hidden_minority_medium

[420/900] ilpd svm seed=53 hidden_minority_high

[421/900] blood lr seed=13 hidden_minority_low

[422/900] blood lr seed=13 hidden_minority_medium

[423/900] blood lr seed=13 hidden_minority_high

[424/900] blood lr seed=17 hidden_minority_low

[425/900] blood lr seed=17 hidden_minority_medium

[426/900] blood lr seed=17 hidden_minority_high

[427/900] blood lr seed=23 hidden_minority_low

[428/900] blood lr seed=23 hidden_minority_medium

[429/900] blood lr seed=23 hidden_minority_high

[430/900] blood lr seed=29 hidden_minority_low

[431/900] blood lr seed=29 hidden_minority_medium

[432/900] blood lr seed=29 hidden_minority_high

[433/900] blood lr seed=31 hidden_minority_low

[434/900] blood lr seed=31 hidden_minority_medium

[435/900] blood lr seed=31 hidden_minority_high

[436/900] blood lr seed=37 hidden_minority_low

[437/900] blood lr seed=37 hidden_minority_medium

[438/900] blood lr seed=37 hidden_minority_high

[439/900] blood lr seed=41 hidden_minority_low

[440/900] blood lr seed=41 hidden_minority_medium

[441/900] blood lr seed=41 hidden_minority_high

[442/900] blood lr seed=43 hidden_minority_low

[443/900] blood lr seed=43 hidden_minority_medium

[444/900] blood lr seed=43 hidden_minority_high

[445/900] blood lr seed=47 hidden_minority_low

[446/900] blood lr seed=47 hidden_minority_medium

[447/900] blood lr seed=47 hidden_minority_high

[448/900] blood lr seed=53 hidden_minority_low

[449/900] blood lr seed=53 hidden_minority_medium

[450/900] blood lr seed=53 hidden_minority_high

[451/900] blood svm seed=13 hidden_minority_low

[452/900] blood svm seed=13 hidden_minority_medium

[453/900] blood svm seed=13 hidden_minority_high

[454/900] blood svm seed=17 hidden_minority_low

[455/900] blood svm seed=17 hidden_minority_medium

[456/900] blood svm seed=17 hidden_minority_high

[457/900] blood svm seed=23 hidden_minority_low

[458/900] blood svm seed=23 hidden_minority_medium

[459/900] blood svm seed=23 hidden_minority_high

[460/900] blood svm seed=29 hidden_minority_low

[461/900] blood svm seed=29 hidden_minority_medium

[462/900] blood svm seed=29 hidden_minority_high

[463/900] blood svm seed=31 hidden_minority_low

[464/900] blood svm seed=31 hidden_minority_medium

[465/900] blood svm seed=31 hidden_minority_high

[466/900] blood svm seed=37 hidden_minority_low

[467/900] blood svm seed=37 hidden_minority_medium

[468/900] blood svm seed=37 hidden_minority_high

[469/900] blood svm seed=41 hidden_minority_low

[470/900] blood svm seed=41 hidden_minority_medium

[471/900] blood svm seed=41 hidden_minority_high

[472/900] blood svm seed=43 hidden_minority_low

[473/900] blood svm seed=43 hidden_minority_medium

[474/900] blood svm seed=43 hidden_minority_high

[475/900] blood svm seed=47 hidden_minority_low

[476/900] blood svm seed=47 hidden_minority_medium

[477/900] blood svm seed=47 hidden_minority_high

[478/900] blood svm seed=53 hidden_minority_low

[479/900] blood svm seed=53 hidden_minority_medium

[480/900] blood svm seed=53 hidden_minority_high

[481/900] haberman lr seed=13 hidden_minority_low

[482/900] haberman lr seed=13 hidden_minority_medium

[483/900] haberman lr seed=13 hidden_minority_high

[484/900] haberman lr seed=17 hidden_minority_low

[485/900] haberman lr seed=17 hidden_minority_medium

[486/900] haberman lr seed=17 hidden_minority_high

[487/900] haberman lr seed=23 hidden_minority_low

[488/900] haberman lr seed=23 hidden_minority_medium

[489/900] haberman lr seed=23 hidden_minority_high

[490/900] haberman lr seed=29 hidden_minority_low

[491/900] haberman lr seed=29 hidden_minority_medium

[492/900] haberman lr seed=29 hidden_minority_high

[493/900] haberman lr seed=31 hidden_minority_low

[494/900] haberman lr seed=31 hidden_minority_medium

[495/900] haberman lr seed=31 hidden_minority_high

[496/900] haberman lr seed=37 hidden_minority_low

[497/900] haberman lr seed=37 hidden_minority_medium

[498/900] haberman lr seed=37 hidden_minority_high

[499/900] haberman lr seed=41 hidden_minority_low

[500/900] haberman lr seed=41 hidden_minority_medium

[501/900] haberman lr seed=41 hidden_minority_high

[502/900] haberman lr seed=43 hidden_minority_low

[503/900] haberman lr seed=43 hidden_minority_medium

[504/900] haberman lr seed=43 hidden_minority_high

[505/900] haberman lr seed=47 hidden_minority_low

[506/900] haberman lr seed=47 hidden_minority_medium

[507/900] haberman lr seed=47 hidden_minority_high

[508/900] haberman lr seed=53 hidden_minority_low

[509/900] haberman lr seed=53 hidden_minority_medium

[510/900] haberman lr seed=53 hidden_minority_high

[511/900] haberman svm seed=13 hidden_minority_low

[512/900] haberman svm seed=13 hidden_minority_medium

[513/900] haberman svm seed=13 hidden_minority_high

[514/900] haberman svm seed=17 hidden_minority_low

[515/900] haberman svm seed=17 hidden_minority_medium

[516/900] haberman svm seed=17 hidden_minority_high

[517/900] haberman svm seed=23 hidden_minority_low

[518/900] haberman svm seed=23 hidden_minority_medium

[519/900] haberman svm seed=23 hidden_minority_high

[520/900] haberman svm seed=29 hidden_minority_low

[521/900] haberman svm seed=29 hidden_minority_medium

[522/900] haberman svm seed=29 hidden_minority_high

[523/900] haberman svm seed=31 hidden_minority_low

[524/900] haberman svm seed=31 hidden_minority_medium

[525/900] haberman svm seed=31 hidden_minority_high

[526/900] haberman svm seed=37 hidden_minority_low

[527/900] haberman svm seed=37 hidden_minority_medium

[528/900] haberman svm seed=37 hidden_minority_high

[529/900] haberman svm seed=41 hidden_minority_low

[530/900] haberman svm seed=41 hidden_minority_medium

[531/900] haberman svm seed=41 hidden_minority_high

[532/900] haberman svm seed=43 hidden_minority_low

[533/900] haberman svm seed=43 hidden_minority_medium

[534/900] haberman svm seed=43 hidden_minority_high

[535/900] haberman svm seed=47 hidden_minority_low

[536/900] haberman svm seed=47 hidden_minority_medium

[537/900] haberman svm seed=47 hidden_minority_high

[538/900] haberman svm seed=53 hidden_minority_low

[539/900] haberman svm seed=53 hidden_minority_medium

[540/900] haberman svm seed=53 hidden_minority_high

[541/900] ionosphere lr seed=13 hidden_minority_low

[542/900] ionosphere lr seed=13 hidden_minority_medium

[543/900] ionosphere lr seed=13 hidden_minority_high

[544/900] ionosphere lr seed=17 hidden_minority_low

[545/900] ionosphere lr seed=17 hidden_minority_medium

[546/900] ionosphere lr seed=17 hidden_minority_high

[547/900] ionosphere lr seed=23 hidden_minority_low

[548/900] ionosphere lr seed=23 hidden_minority_medium

[549/900] ionosphere lr seed=23 hidden_minority_high

[550/900] ionosphere lr seed=29 hidden_minority_low

[551/900] ionosphere lr seed=29 hidden_minority_medium

[552/900] ionosphere lr seed=29 hidden_minority_high

[553/900] ionosphere lr seed=31 hidden_minority_low

[554/900] ionosphere lr seed=31 hidden_minority_medium

[555/900] ionosphere lr seed=31 hidden_minority_high

[556/900] ionosphere lr seed=37 hidden_minority_low

[557/900] ionosphere lr seed=37 hidden_minority_medium

[558/900] ionosphere lr seed=37 hidden_minority_high

[559/900] ionosphere lr seed=41 hidden_minority_low

[560/900] ionosphere lr seed=41 hidden_minority_medium

[561/900] ionosphere lr seed=41 hidden_minority_high

[562/900] ionosphere lr seed=43 hidden_minority_low

[563/900] ionosphere lr seed=43 hidden_minority_medium

[564/900] ionosphere lr seed=43 hidden_minority_high

[565/900] ionosphere lr seed=47 hidden_minority_low

[566/900] ionosphere lr seed=47 hidden_minority_medium

[567/900] ionosphere lr seed=47 hidden_minority_high

[568/900] ionosphere lr seed=53 hidden_minority_low

[569/900] ionosphere lr seed=53 hidden_minority_medium

[570/900] ionosphere lr seed=53 hidden_minority_high

[571/900] ionosphere svm seed=13 hidden_minority_low

[572/900] ionosphere svm seed=13 hidden_minority_medium

[573/900] ionosphere svm seed=13 hidden_minority_high

[574/900] ionosphere svm seed=17 hidden_minority_low

[575/900] ionosphere svm seed=17 hidden_minority_medium

[576/900] ionosphere svm seed=17 hidden_minority_high

[577/900] ionosphere svm seed=23 hidden_minority_low

[578/900] ionosphere svm seed=23 hidden_minority_medium

[579/900] ionosphere svm seed=23 hidden_minority_high

[580/900] ionosphere svm seed=29 hidden_minority_low

[581/900] ionosphere svm seed=29 hidden_minority_medium

[582/900] ionosphere svm seed=29 hidden_minority_high

[583/900] ionosphere svm seed=31 hidden_minority_low

[584/900] ionosphere svm seed=31 hidden_minority_medium

[585/900] ionosphere svm seed=31 hidden_minority_high

[586/900] ionosphere svm seed=37 hidden_minority_low

[587/900] ionosphere svm seed=37 hidden_minority_medium

[588/900] ionosphere svm seed=37 hidden_minority_high

[589/900] ionosphere svm seed=41 hidden_minority_low

[590/900] ionosphere svm seed=41 hidden_minority_medium

[591/900] ionosphere svm seed=41 hidden_minority_high

[592/900] ionosphere svm seed=43 hidden_minority_low

[593/900] ionosphere svm seed=43 hidden_minority_medium

[594/900] ionosphere svm seed=43 hidden_minority_high

[595/900] ionosphere svm seed=47 hidden_minority_low

[596/900] ionosphere svm seed=47 hidden_minority_medium

[597/900] ionosphere svm seed=47 hidden_minority_high

[598/900] ionosphere svm seed=53 hidden_minority_low

[599/900] ionosphere svm seed=53 hidden_minority_medium

[600/900] ionosphere svm seed=53 hidden_minority_high

[601/900] vehicle_bus lr seed=13 hidden_minority_low

[602/900] vehicle_bus lr seed=13 hidden_minority_medium

[603/900] vehicle_bus lr seed=13 hidden_minority_high

[604/900] vehicle_bus lr seed=17 hidden_minority_low

[605/900] vehicle_bus lr seed=17 hidden_minority_medium

[606/900] vehicle_bus lr seed=17 hidden_minority_high

[607/900] vehicle_bus lr seed=23 hidden_minority_low

[608/900] vehicle_bus lr seed=23 hidden_minority_medium

[609/900] vehicle_bus lr seed=23 hidden_minority_high

[610/900] vehicle_bus lr seed=29 hidden_minority_low

[611/900] vehicle_bus lr seed=29 hidden_minority_medium

[612/900] vehicle_bus lr seed=29 hidden_minority_high

[613/900] vehicle_bus lr seed=31 hidden_minority_low

[614/900] vehicle_bus lr seed=31 hidden_minority_medium

[615/900] vehicle_bus lr seed=31 hidden_minority_high

[616/900] vehicle_bus lr seed=37 hidden_minority_low

[617/900] vehicle_bus lr seed=37 hidden_minority_medium

[618/900] vehicle_bus lr seed=37 hidden_minority_high

[619/900] vehicle_bus lr seed=41 hidden_minority_low

[620/900] vehicle_bus lr seed=41 hidden_minority_medium

[621/900] vehicle_bus lr seed=41 hidden_minority_high

[622/900] vehicle_bus lr seed=43 hidden_minority_low

[623/900] vehicle_bus lr seed=43 hidden_minority_medium

[624/900] vehicle_bus lr seed=43 hidden_minority_high

[625/900] vehicle_bus lr seed=47 hidden_minority_low

[626/900] vehicle_bus lr seed=47 hidden_minority_medium

[627/900] vehicle_bus lr seed=47 hidden_minority_high

[628/900] vehicle_bus lr seed=53 hidden_minority_low

[629/900] vehicle_bus lr seed=53 hidden_minority_medium

[630/900] vehicle_bus lr seed=53 hidden_minority_high

[631/900] vehicle_bus svm seed=13 hidden_minority_low

[632/900] vehicle_bus svm seed=13 hidden_minority_medium

[633/900] vehicle_bus svm seed=13 hidden_minority_high

[634/900] vehicle_bus svm seed=17 hidden_minority_low

[635/900] vehicle_bus svm seed=17 hidden_minority_medium

[636/900] vehicle_bus svm seed=17 hidden_minority_high

[637/900] vehicle_bus svm seed=23 hidden_minority_low

[638/900] vehicle_bus svm seed=23 hidden_minority_medium

[639/900] vehicle_bus svm seed=23 hidden_minority_high

[640/900] vehicle_bus svm seed=29 hidden_minority_low

[641/900] vehicle_bus svm seed=29 hidden_minority_medium

[642/900] vehicle_bus svm seed=29 hidden_minority_high

[643/900] vehicle_bus svm seed=31 hidden_minority_low

[644/900] vehicle_bus svm seed=31 hidden_minority_medium

[645/900] vehicle_bus svm seed=31 hidden_minority_high

[646/900] vehicle_bus svm seed=37 hidden_minority_low

[647/900] vehicle_bus svm seed=37 hidden_minority_medium

[648/900] vehicle_bus svm seed=37 hidden_minority_high

[649/900] vehicle_bus svm seed=41 hidden_minority_low

[650/900] vehicle_bus svm seed=41 hidden_minority_medium

[651/900] vehicle_bus svm seed=41 hidden_minority_high

[652/900] vehicle_bus svm seed=43 hidden_minority_low

[653/900] vehicle_bus svm seed=43 hidden_minority_medium

[654/900] vehicle_bus svm seed=43 hidden_minority_high

[655/900] vehicle_bus svm seed=47 hidden_minority_low

[656/900] vehicle_bus svm seed=47 hidden_minority_medium

[657/900] vehicle_bus svm seed=47 hidden_minority_high

[658/900] vehicle_bus svm seed=53 hidden_minority_low

[659/900] vehicle_bus svm seed=53 hidden_minority_medium

[660/900] vehicle_bus svm seed=53 hidden_minority_high

[661/900] glass_float lr seed=13 hidden_minority_low

[662/900] glass_float lr seed=13 hidden_minority_medium

[663/900] glass_float lr seed=13 hidden_minority_high

[664/900] glass_float lr seed=17 hidden_minority_low

[665/900] glass_float lr seed=17 hidden_minority_medium

[666/900] glass_float lr seed=17 hidden_minority_high

[667/900] glass_float lr seed=23 hidden_minority_low

[668/900] glass_float lr seed=23 hidden_minority_medium

[669/900] glass_float lr seed=23 hidden_minority_high

[670/900] glass_float lr seed=29 hidden_minority_low

[671/900] glass_float lr seed=29 hidden_minority_medium

[672/900] glass_float lr seed=29 hidden_minority_high

[673/900] glass_float lr seed=31 hidden_minority_low

[674/900] glass_float lr seed=31 hidden_minority_medium

[675/900] glass_float lr seed=31 hidden_minority_high

[676/900] glass_float lr seed=37 hidden_minority_low

[677/900] glass_float lr seed=37 hidden_minority_medium

[678/900] glass_float lr seed=37 hidden_minority_high

[679/900] glass_float lr seed=41 hidden_minority_low

[680/900] glass_float lr seed=41 hidden_minority_medium

[681/900] glass_float lr seed=41 hidden_minority_high

[682/900] glass_float lr seed=43 hidden_minority_low

[683/900] glass_float lr seed=43 hidden_minority_medium

[684/900] glass_float lr seed=43 hidden_minority_high

[685/900] glass_float lr seed=47 hidden_minority_low

[686/900] glass_float lr seed=47 hidden_minority_medium

[687/900] glass_float lr seed=47 hidden_minority_high

[688/900] glass_float lr seed=53 hidden_minority_low

[689/900] glass_float lr seed=53 hidden_minority_medium

[690/900] glass_float lr seed=53 hidden_minority_high

[691/900] glass_float svm seed=13 hidden_minority_low

[692/900] glass_float svm seed=13 hidden_minority_medium

[693/900] glass_float svm seed=13 hidden_minority_high

[694/900] glass_float svm seed=17 hidden_minority_low

[695/900] glass_float svm seed=17 hidden_minority_medium

[696/900] glass_float svm seed=17 hidden_minority_high

[697/900] glass_float svm seed=23 hidden_minority_low

[698/900] glass_float svm seed=23 hidden_minority_medium

[699/900] glass_float svm seed=23 hidden_minority_high

[700/900] glass_float svm seed=29 hidden_minority_low

[701/900] glass_float svm seed=29 hidden_minority_medium

[702/900] glass_float svm seed=29 hidden_minority_high

[703/900] glass_float svm seed=31 hidden_minority_low

[704/900] glass_float svm seed=31 hidden_minority_medium

[705/900] glass_float svm seed=31 hidden_minority_high

[706/900] glass_float svm seed=37 hidden_minority_low

[707/900] glass_float svm seed=37 hidden_minority_medium

[708/900] glass_float svm seed=37 hidden_minority_high

[709/900] glass_float svm seed=41 hidden_minority_low

[710/900] glass_float svm seed=41 hidden_minority_medium

[711/900] glass_float svm seed=41 hidden_minority_high

[712/900] glass_float svm seed=43 hidden_minority_low

[713/900] glass_float svm seed=43 hidden_minority_medium

[714/900] glass_float svm seed=43 hidden_minority_high

[715/900] glass_float svm seed=47 hidden_minority_low

[716/900] glass_float svm seed=47 hidden_minority_medium

[717/900] glass_float svm seed=47 hidden_minority_high

[718/900] glass_float svm seed=53 hidden_minority_low

[719/900] glass_float svm seed=53 hidden_minority_medium

[720/900] glass_float svm seed=53 hidden_minority_high

[721/900] abalone lr seed=13 hidden_minority_low

[722/900] abalone lr seed=13 hidden_minority_medium

[723/900] abalone lr seed=13 hidden_minority_high

[724/900] abalone lr seed=17 hidden_minority_low

[725/900] abalone lr seed=17 hidden_minority_medium

[726/900] abalone lr seed=17 hidden_minority_high

[727/900] abalone lr seed=23 hidden_minority_low

[728/900] abalone lr seed=23 hidden_minority_medium

[729/900] abalone lr seed=23 hidden_minority_high

[730/900] abalone lr seed=29 hidden_minority_low

[731/900] abalone lr seed=29 hidden_minority_medium

[732/900] abalone lr seed=29 hidden_minority_high

[733/900] abalone lr seed=31 hidden_minority_low

[734/900] abalone lr seed=31 hidden_minority_medium

[735/900] abalone lr seed=31 hidden_minority_high

[736/900] abalone lr seed=37 hidden_minority_low

[737/900] abalone lr seed=37 hidden_minority_medium

[738/900] abalone lr seed=37 hidden_minority_high

[739/900] abalone lr seed=41 hidden_minority_low

[740/900] abalone lr seed=41 hidden_minority_medium

[741/900] abalone lr seed=41 hidden_minority_high

[742/900] abalone lr seed=43 hidden_minority_low

[743/900] abalone lr seed=43 hidden_minority_medium

[744/900] abalone lr seed=43 hidden_minority_high

[745/900] abalone lr seed=47 hidden_minority_low

[746/900] abalone lr seed=47 hidden_minority_medium

[747/900] abalone lr seed=47 hidden_minority_high

[748/900] abalone lr seed=53 hidden_minority_low

[749/900] abalone lr seed=53 hidden_minority_medium

[750/900] abalone lr seed=53 hidden_minority_high

[751/900] abalone svm seed=13 hidden_minority_low

[752/900] abalone svm seed=13 hidden_minority_medium

[753/900] abalone svm seed=13 hidden_minority_high

[754/900] abalone svm seed=17 hidden_minority_low

[755/900] abalone svm seed=17 hidden_minority_medium

[756/900] abalone svm seed=17 hidden_minority_high

[757/900] abalone svm seed=23 hidden_minority_low

[758/900] abalone svm seed=23 hidden_minority_medium

[759/900] abalone svm seed=23 hidden_minority_high

[760/900] abalone svm seed=29 hidden_minority_low

[761/900] abalone svm seed=29 hidden_minority_medium

[762/900] abalone svm seed=29 hidden_minority_high

[763/900] abalone svm seed=31 hidden_minority_low

[764/900] abalone svm seed=31 hidden_minority_medium

[765/900] abalone svm seed=31 hidden_minority_high

[766/900] abalone svm seed=37 hidden_minority_low

[767/900] abalone svm seed=37 hidden_minority_medium

[768/900] abalone svm seed=37 hidden_minority_high

[769/900] abalone svm seed=41 hidden_minority_low

[770/900] abalone svm seed=41 hidden_minority_medium

[771/900] abalone svm seed=41 hidden_minority_high

[772/900] abalone svm seed=43 hidden_minority_low

[773/900] abalone svm seed=43 hidden_minority_medium

[774/900] abalone svm seed=43 hidden_minority_high

[775/900] abalone svm seed=47 hidden_minority_low

[776/900] abalone svm seed=47 hidden_minority_medium

[777/900] abalone svm seed=47 hidden_minority_high

[778/900] abalone svm seed=53 hidden_minority_low

[779/900] abalone svm seed=53 hidden_minority_medium

[780/900] abalone svm seed=53 hidden_minority_high

[781/900] spambase lr seed=13 hidden_minority_low

[782/900] spambase lr seed=13 hidden_minority_medium

[783/900] spambase lr seed=13 hidden_minority_high

[784/900] spambase lr seed=17 hidden_minority_low

[785/900] spambase lr seed=17 hidden_minority_medium

[786/900] spambase lr seed=17 hidden_minority_high

[787/900] spambase lr seed=23 hidden_minority_low

[788/900] spambase lr seed=23 hidden_minority_medium

[789/900] spambase lr seed=23 hidden_minority_high

[790/900] spambase lr seed=29 hidden_minority_low

[791/900] spambase lr seed=29 hidden_minority_medium

[792/900] spambase lr seed=29 hidden_minority_high

[793/900] spambase lr seed=31 hidden_minority_low

[794/900] spambase lr seed=31 hidden_minority_medium

[795/900] spambase lr seed=31 hidden_minority_high

[796/900] spambase lr seed=37 hidden_minority_low

[797/900] spambase lr seed=37 hidden_minority_medium

[798/900] spambase lr seed=37 hidden_minority_high

[799/900] spambase lr seed=41 hidden_minority_low

[800/900] spambase lr seed=41 hidden_minority_medium

[801/900] spambase lr seed=41 hidden_minority_high

[802/900] spambase lr seed=43 hidden_minority_low

[803/900] spambase lr seed=43 hidden_minority_medium

[804/900] spambase lr seed=43 hidden_minority_high

[805/900] spambase lr seed=47 hidden_minority_low

[806/900] spambase lr seed=47 hidden_minority_medium

[807/900] spambase lr seed=47 hidden_minority_high

[808/900] spambase lr seed=53 hidden_minority_low

[809/900] spambase lr seed=53 hidden_minority_medium

[810/900] spambase lr seed=53 hidden_minority_high

[811/900] spambase svm seed=13 hidden_minority_low

[812/900] spambase svm seed=13 hidden_minority_medium

[813/900] spambase svm seed=13 hidden_minority_high

[814/900] spambase svm seed=17 hidden_minority_low

[815/900] spambase svm seed=17 hidden_minority_medium

[816/900] spambase svm seed=17 hidden_minority_high

[817/900] spambase svm seed=23 hidden_minority_low

[818/900] spambase svm seed=23 hidden_minority_medium

[819/900] spambase svm seed=23 hidden_minority_high

[820/900] spambase svm seed=29 hidden_minority_low

[821/900] spambase svm seed=29 hidden_minority_medium

[822/900] spambase svm seed=29 hidden_minority_high

[823/900] spambase svm seed=31 hidden_minority_low

[824/900] spambase svm seed=31 hidden_minority_medium

[825/900] spambase svm seed=31 hidden_minority_high

[826/900] spambase svm seed=37 hidden_minority_low

[827/900] spambase svm seed=37 hidden_minority_medium

[828/900] spambase svm seed=37 hidden_minority_high

[829/900] spambase svm seed=41 hidden_minority_low

[830/900] spambase svm seed=41 hidden_minority_medium

[831/900] spambase svm seed=41 hidden_minority_high

[832/900] spambase svm seed=43 hidden_minority_low

[833/900] spambase svm seed=43 hidden_minority_medium

[834/900] spambase svm seed=43 hidden_minority_high

[835/900] spambase svm seed=47 hidden_minority_low

[836/900] spambase svm seed=47 hidden_minority_medium

[837/900] spambase svm seed=47 hidden_minority_high

[838/900] spambase svm seed=53 hidden_minority_low

[839/900] spambase svm seed=53 hidden_minority_medium

[840/900] spambase svm seed=53 hidden_minority_high

[841/900] kc1 lr seed=13 hidden_minority_low

[842/900] kc1 lr seed=13 hidden_minority_medium

[843/900] kc1 lr seed=13 hidden_minority_high

[844/900] kc1 lr seed=17 hidden_minority_low

[845/900] kc1 lr seed=17 hidden_minority_medium

[846/900] kc1 lr seed=17 hidden_minority_high

[847/900] kc1 lr seed=23 hidden_minority_low

[848/900] kc1 lr seed=23 hidden_minority_medium

[849/900] kc1 lr seed=23 hidden_minority_high

[850/900] kc1 lr seed=29 hidden_minority_low

[851/900] kc1 lr seed=29 hidden_minority_medium

[852/900] kc1 lr seed=29 hidden_minority_high

[853/900] kc1 lr seed=31 hidden_minority_low

[854/900] kc1 lr seed=31 hidden_minority_medium

[855/900] kc1 lr seed=31 hidden_minority_high

[856/900] kc1 lr seed=37 hidden_minority_low

[857/900] kc1 lr seed=37 hidden_minority_medium

[858/900] kc1 lr seed=37 hidden_minority_high

[859/900] kc1 lr seed=41 hidden_minority_low

[860/900] kc1 lr seed=41 hidden_minority_medium

[861/900] kc1 lr seed=41 hidden_minority_high

[862/900] kc1 lr seed=43 hidden_minority_low

[863/900] kc1 lr seed=43 hidden_minority_medium

[864/900] kc1 lr seed=43 hidden_minority_high

[865/900] kc1 lr seed=47 hidden_minority_low

[866/900] kc1 lr seed=47 hidden_minority_medium

[867/900] kc1 lr seed=47 hidden_minority_high

[868/900] kc1 lr seed=53 hidden_minority_low

[869/900] kc1 lr seed=53 hidden_minority_medium

[870/900] kc1 lr seed=53 hidden_minority_high

[871/900] kc1 svm seed=13 hidden_minority_low

[872/900] kc1 svm seed=13 hidden_minority_medium

[873/900] kc1 svm seed=13 hidden_minority_high

[874/900] kc1 svm seed=17 hidden_minority_low

[875/900] kc1 svm seed=17 hidden_minority_medium

[876/900] kc1 svm seed=17 hidden_minority_high

[877/900] kc1 svm seed=23 hidden_minority_low

[878/900] kc1 svm seed=23 hidden_minority_medium

[879/900] kc1 svm seed=23 hidden_minority_high

[880/900] kc1 svm seed=29 hidden_minority_low

[881/900] kc1 svm seed=29 hidden_minority_medium

[882/900] kc1 svm seed=29 hidden_minority_high

[883/900] kc1 svm seed=31 hidden_minority_low

[884/900] kc1 svm seed=31 hidden_minority_medium

[885/900] kc1 svm seed=31 hidden_minority_high

[886/900] kc1 svm seed=37 hidden_minority_low

[887/900] kc1 svm seed=37 hidden_minority_medium

[888/900] kc1 svm seed=37 hidden_minority_high

[889/900] kc1 svm seed=41 hidden_minority_low

[890/900] kc1 svm seed=41 hidden_minority_medium

[891/900] kc1 svm seed=41 hidden_minority_high

[892/900] kc1 svm seed=43 hidden_minority_low

[893/900] kc1 svm seed=43 hidden_minority_medium

[894/900] kc1 svm seed=43 hidden_minority_high

[895/900] kc1 svm seed=47 hidden_minority_low

[896/900] kc1 svm seed=47 hidden_minority_medium

[897/900] kc1 svm seed=47 hidden_minority_high

[898/900] kc1 svm seed=53 hidden_minority_low

[899/900] kc1 svm seed=53 hidden_minority_medium

[900/900] kc1 svm seed=53 hidden_minority_high

rows 5400 minutes 20.13

,dataset,model,seed,noise_protocol,mn_to_maj,maj_to_min,method,train_rows,test_rows,budget_count,true_noise_rate,runtime_sec,error,balanced_accuracy,accuracy,macro_f1,minority_precision,minority_recall,majority_recall,pr_auc,n_synthetic,deleted,mean_cwms_weight
0,pima,lr,13,hidden_minority_low,0.1,0.05,no_cleaning,441,192,44,0.072562,0.007504,,0.540239,0.671875,0.488303,0.700000,0.104478,0.976,0.670561,0,0,NaN
1,pima,lr,13,hidden_minority_low,0.1,0.05,class_proportional,441,192,44,0.072562,0.014519,,0.678806,0.739583,0.688109,0.680851,0.477612,0.880,0.662807,0,44,NaN
2,pima,lr,13,hidden_minority_low,0.1,0.05,smote,441,192,44,0.072562,0.133971,,0.614328,0.718750,0.608163,0.782609,0.268657,0.960,0.676608,44,0,NaN
3,pima,lr,13,hidden_minority_low,0.1,0.05,iw_smote,441,192,44,0.072562,0.157943,,0.772060,0.770833,0.758131,0.641975,0.776119,0.768,0.666475,44,109,NaN
4,pima,lr,13,hidden_minority_low,0.1,0.05,sw_approx,441,192,44,0.072562,0.139081,,0.609254,0.703125,0.606882,0.666667,0.298507,0.920,0.663803,44,0,NaN

In [9]:
metric_cols = ["balanced_accuracy", "macro_f1", "minority_precision", "minority_recall", "majority_recall", "pr_auc"]
summary = results.groupby(["model", "method"])[metric_cols].mean().reset_index().sort_values(["model", "balanced_accuracy"], ascending=[True, False])
summary

,model,method,balanced_accuracy,macro_f1,minority_precision,minority_recall,majority_recall,pr_auc
1,lr,coins,0.732660,0.702255,0.541962,0.717149,0.748171,0.637050
2,lr,iw_smote,0.726252,0.709757,0.574047,0.649923,0.802581,0.636764
0,lr,class_proportional,0.699631,0.699711,0.648397,0.483763,0.915499,0.647831
5,lr,sw_approx,0.660270,0.657457,0.698869,0.363418,0.957122,0.645011
4,lr,smote,0.645588,0.638065,0.711988,0.326877,0.964300,0.638473
3,lr,no_cleaning,0.601185,0.575924,0.691486,0.214579,0.987791,0.642796
8,svm,iw_smote,0.745932,0.736875,0.624884,0.651792,0.840073,0.658148
7,svm,coins,0.687820,0.678374,0.665906,0.427069,0.948570,0.655120
6,svm,class_proportional,0.671351,0.658679,0.658783,0.370537,0.972165,0.642094
11,svm,sw_approx,0.654660,0.645256,0.709640,0.334754,0.974565,0.660648
10,svm,smote,0.638024,0.621095,0.697749,0.294147,0.981901,0.653760
9,svm,no_cleaning,0.585256,0.543771,0.547208,0.174176,0.996337,0.618755

In [10]:
def stouffer_report(
    df: pd.DataFrame,
    model_name: str,
    base: str = "class_proportional",
    challenger: str = "coins",
) -> tuple[pd.DataFrame, dict[str, Any]]:
    """Run per-dataset Wilcoxon tests and combine them with Stouffer's Z.

    This avoids treating all seed/protocol rows as independent. Each dataset gets
    its own paired Wilcoxon test; dataset-level Z scores are then combined.
    """
    rows2: list[dict[str, Any]] = []
    sub = df[df.model == model_name]
    for data_name in sorted(sub.dataset.unique()):
        a = sub[(sub.dataset == data_name) & (sub.method == challenger)].set_index(["seed", "noise_protocol"])
        b = sub[(sub.dataset == data_name) & (sub.method == base)].set_index(["seed", "noise_protocol"])
        j = a[["balanced_accuracy"]].join(b[["balanced_accuracy"]], lsuffix="_coins", rsuffix="_base", how="inner").dropna()
        if len(j) < 2:
            rows2.append({"dataset": data_name, "n": len(j), "delta_ba": np.nan, "p": np.nan, "z": np.nan})
            continue
        d = j.balanced_accuracy_coins - j.balanced_accuracy_base
        try:
            _, p = wilcoxon(d, alternative="greater", zero_method="wilcox")
        except ValueError:
            p = 1.0 if d.mean() <= 0 else 0.5
        rows2.append({
            "dataset": data_name,
            "n": len(j),
            "delta_ba": float(d.mean()),
            "p": float(p),
            "z": float(norm.isf(min(max(p, 1e-15), 1 - 1e-15))),
        })
    detail = pd.DataFrame(rows2)
    z = detail.z.dropna().to_numpy()
    stat = z.sum() / np.sqrt(len(z)) if len(z) else np.nan
    return detail, {
        "model": model_name,
        "baseline": base,
        "challenger": challenger,
        "stouffer_z": stat,
        "stouffer_p": norm.sf(stat) if np.isfinite(stat) else np.nan,
        "significant_datasets_p005": int((detail.p < 0.05).sum()),
    }


for m in MODELS:
    detail, stat = stouffer_report(results, m)
    print(stat)
    display(detail)

{'model': 'lr', 'baseline': 'class_proportional', 'challenger': 'coins', 'stouffer_z': np.float64(9.993580065629923), 'stouffer_p': np.float64(8.130039353834052e-24), 'significant_datasets_p005': 10}

          dataset   n  delta_ba             p         z
0         abalone  30  0.056060  9.313226e-10  6.009354
1           blood  30  0.066807  6.519258e-09  5.685559
2   breast_cancer  30 -0.018721  9.984214e-01 -2.951998
3        credit-g  30  0.019460  1.578087e-03  2.952103
4           ecoli  30  0.003495  2.389621e-01  0.709645
5     glass_float  30  0.104167  2.111383e-05  4.094941
6        haberman  30  0.031681  3.075127e-04  3.424900
7            ilpd  30  0.066781  9.313226e-09  5.624297
8      ionosphere  30 -0.009375  8.457118e-01 -1.018214
9             kc1  30  0.056632  8.666533e-07  4.782265
10        phoneme  30  0.094672  9.313226e-10  6.009354
11           pima  30  0.037558  3.455207e-07  4.963865
12       spambase  30 -0.006130  9.404617e-01 -1.558661
13    vehicle_bus  30 -0.017705  9.943485e-01 -2.533187
14          yeast  30  0.010052  6.023811e-03  2.510746

{'model': 'svm', 'baseline': 'class_proportional', 'challenger': 'coins', 'stouffer_z': np.float64(7.466224811602646), 'stouffer_p': np.float64(4.126415094119126e-14), 'significant_datasets_p005': 10}

          dataset   n  delta_ba             p         z
0         abalone  30  0.021746  2.527442e-04  3.477831
1           blood  30  0.009579  3.705801e-02  1.785897
2   breast_cancer  30 -0.023382  9.999592e-01 -3.939839
3        credit-g  30  0.007175  2.214634e-02  2.011310
4           ecoli  30  0.054710  1.694183e-03  2.930115
5     glass_float  30  0.041667  1.326140e-04  3.647089
6        haberman  30  0.015380  5.614884e-02  1.587950
7            ilpd  30  0.009013  7.360566e-02  1.449452
8      ionosphere  30 -0.047991  9.966174e-01 -2.708184
9             kc1  30 -0.006831  8.644287e-01 -1.100435
10        phoneme  30  0.092674  9.313226e-10  6.009354
11           pima  30  0.014410  1.744908e-03  2.920936
12       spambase  30  0.012417  3.854845e-04  3.363012
13    vehicle_bus  30  0.029660  4.228399e-06  4.453281
14          yeast  30  0.016805  1.227654e-03  3.028796

## Interpretation Notes

- Full-mode results are rerun from cached datasets and can be used for presentation tables.
- Smoke-mode results are execution checks only.
- COINS is boundary repair for hidden-minority asymmetric noise, not general label cleaning.
- Original labels are never modified.