# COINS 03 - Final LR/SVM Actual Run Results

This notebook starts with the actual run-level results, not coverage. Each COINS result row is one dataset × seed × noise protocol run. Expected entries: 15 datasets × 10 seeds × 3 protocols = 450 rows per model.

In [1]:
from __future__ import annotations
import os, warnings
from pathlib import Path
import numpy as np
import pandas as pd
from scipy.stats import norm, wilcoxon
warnings.filterwarnings("ignore")
os.environ["PYTHONWARNINGS"] = "ignore"
pd.set_option("display.max_columns", 160)
pd.set_option("display.max_rows", 260)
ROOT = Path.cwd()
RAW_RESULTS = ROOT / "docs" / "experiments" / "raw" / "full-benchmark-solution-v2.csv"
results = pd.read_csv(RAW_RESULTS)
lr_svm = results[results["model"].isin(["lr", "svm"])].copy()
print("source", RAW_RESULTS)
print("full rows", len(results))
print("LR/SVM rows", len(lr_svm))

source /home/than-minh/project/DSP/docs/experiments/raw/full-benchmark-solution-v2.csv
full rows 24750
LR/SVM rows 6300

## Actual COINS Run Results: 450 Entries Per Model

These are the actual final COINS training results (`cwms_msbs`) for LR and SVM. They include BA, macro F1, minority/majority precision, and minority/majority recall for every dataset/seed/noise-protocol run.

In [2]:
coins_runs = lr_svm[lr_svm["method"] == "cwms_msbs"].copy()
run_cols = [
    "model", "dataset", "seed", "noise_protocol", "method",
    "balanced_accuracy", "macro_f1",
    "minority_precision", "majority_precision",
    "minority_recall", "majority_recall",
]
# Some older result files may not carry majority_precision. Compute a placeholder only if absent.
if "majority_precision" not in coins_runs.columns:
    coins_runs["majority_precision"] = np.nan
coins_run_results = coins_runs[run_cols].sort_values(["model", "dataset", "seed", "noise_protocol"]).reset_index(drop=True)
display(coins_run_results)

run_count = coins_run_results.groupby("model").size().reset_index(name="actual_entries")
run_count["expected_entries"] = 15 * 10 * 3
display(run_count)

,model,dataset,seed,noise_protocol,method,balanced_accuracy,macro_f1,minority_precision,majority_precision,minority_recall,majority_recall
0,lr,abalone,13,hidden_minority_high,cwms_msbs,0.694101,0.670706,0.526749,NaN,0.739884,0.648318
1,lr,abalone,13,hidden_minority_low,cwms_msbs,0.712247,0.709575,0.609890,NaN,0.641618,0.782875
2,lr,abalone,13,hidden_minority_medium,cwms_msbs,0.725504,0.722677,0.626374,NaN,0.658960,0.792049
3,lr,abalone,17,hidden_minority_high,cwms_msbs,0.782486,0.753030,0.609053,NaN,0.855491,0.709480
4,lr,abalone,17,hidden_minority_low,cwms_msbs,0.764252,0.763892,0.689655,NaN,0.693642,0.834862
...,...,...,...,...,...,...,...,...,...,...,...
895,svm,yeast,47,hidden_minority_low,cwms_msbs,0.723189,0.761047,0.763158,NaN,0.475410,0.970968
896,svm,yeast,47,hidden_minority_medium,cwms_msbs,0.693628,0.735689,0.781250,NaN,0.409836,0.977419
897,svm,yeast,53,hidden_minority_high,cwms_msbs,0.606822,0.631736,0.600000,NaN,0.245902,0.967742
898,svm,yeast,53,hidden_minority_low,cwms_msbs,0.760947,0.790881,0.755556,NaN,0.557377,0.964516
899,svm,yeast,53,hidden_minority_medium,cwms_msbs,0.669038,0.709168,0.758621,NaN,0.360656,0.977419

  model  actual_entries  expected_entries
0    lr             450               450
1   svm             450               450

## Actual No-Cleaning Baseline Run Results: 450 Entries Per Model

Same run-level layout for the raw no-cleaning baseline, so COINS has a direct row-level reference.

In [3]:
base_runs = lr_svm[lr_svm["method"] == "no_cleaning"].copy()
if "majority_precision" not in base_runs.columns:
    base_runs["majority_precision"] = np.nan
base_run_results = base_runs[run_cols].sort_values(["model", "dataset", "seed", "noise_protocol"]).reset_index(drop=True)
display(base_run_results)

,model,dataset,seed,noise_protocol,method,balanced_accuracy,macro_f1,minority_precision,majority_precision,minority_recall,majority_recall
0,lr,abalone,13,hidden_minority_high,no_cleaning,0.527373,0.453858,0.909091,NaN,0.057803,0.996942
1,lr,abalone,13,hidden_minority_low,no_cleaning,0.593511,0.573468,0.875000,NaN,0.202312,0.984709
2,lr,abalone,13,hidden_minority_medium,no_cleaning,0.550326,0.499920,0.863636,NaN,0.109827,0.990826
3,lr,abalone,17,hidden_minority_high,no_cleaning,0.511561,0.419926,1.000000,NaN,0.023121,1.000000
4,lr,abalone,17,hidden_minority_low,no_cleaning,0.565970,0.530603,0.812500,NaN,0.150289,0.981651
...,...,...,...,...,...,...,...,...,...,...,...
895,svm,yeast,47,hidden_minority_low,no_cleaning,0.642702,0.684664,0.857143,NaN,0.295082,0.990323
896,svm,yeast,47,hidden_minority_medium,no_cleaning,0.552538,0.556118,0.700000,NaN,0.114754,0.990323
897,svm,yeast,53,hidden_minority_high,no_cleaning,0.496774,0.453608,0.000000,NaN,0.000000,0.993548
898,svm,yeast,53,hidden_minority_low,no_cleaning,0.682073,0.729254,0.851852,NaN,0.377049,0.987097
899,svm,yeast,53,hidden_minority_medium,no_cleaning,0.514781,0.487002,0.666667,NaN,0.032787,0.996774

## Run-Level COINS vs No-Cleaning Delta

Paired by model, dataset, seed, and protocol. Positive delta means COINS improved that metric for the same run.

In [4]:
key = ["model", "dataset", "seed", "noise_protocol"]
paired = coins_run_results.set_index(key).join(base_run_results.set_index(key), lsuffix="_coins", rsuffix="_no_cleaning", how="inner").reset_index()
for metric in ["balanced_accuracy", "macro_f1", "minority_recall", "majority_recall"]:
    paired[f"delta_{metric}"] = paired[f"{metric}_coins"] - paired[f"{metric}_no_cleaning"]
display(paired[[*key, "delta_balanced_accuracy", "delta_macro_f1", "delta_minority_recall", "delta_majority_recall"]])

,model,dataset,seed,noise_protocol,delta_balanced_accuracy,delta_macro_f1,delta_minority_recall,delta_majority_recall
0,lr,abalone,13,hidden_minority_high,0.166729,0.216848,0.682081,-0.348624
1,lr,abalone,13,hidden_minority_low,0.118736,0.136107,0.439306,-0.201835
2,lr,abalone,13,hidden_minority_medium,0.175178,0.222757,0.549133,-0.198777
3,lr,abalone,17,hidden_minority_high,0.270925,0.333104,0.832370,-0.290520
4,lr,abalone,17,hidden_minority_low,0.198282,0.233289,0.543353,-0.146789
...,...,...,...,...,...,...,...,...
895,svm,yeast,47,hidden_minority_low,0.080487,0.076384,0.180328,-0.019355
896,svm,yeast,47,hidden_minority_medium,0.141089,0.179572,0.295082,-0.012903
897,svm,yeast,53,hidden_minority_high,0.110048,0.178127,0.245902,-0.025806
898,svm,yeast,53,hidden_minority_low,0.078874,0.061627,0.180328,-0.022581
899,svm,yeast,53,hidden_minority_medium,0.154257,0.222166,0.327869,-0.019355

## Aggregated Dataset Table: COINS vs No Cleaning

Mean over 10 seeds × 3 protocols for each dataset and model.

In [5]:
metric_cols = ["balanced_accuracy", "macro_f1", "minority_precision", "minority_recall", "majority_recall"]
agg_dataset = lr_svm[lr_svm["method"].isin(["cwms_msbs", "no_cleaning"])].groupby(["model", "dataset", "method"])[metric_cols].mean().reset_index()
display(agg_dataset.sort_values(["model", "dataset", "method"]))

,model,dataset,method,balanced_accuracy,macro_f1,minority_precision,minority_recall,majority_recall
0,lr,abalone,cwms_msbs,0.738683,0.725750,0.610951,0.728131,0.749235
1,lr,abalone,no_cleaning,0.556175,0.507369,0.892595,0.122543,0.989806
2,lr,blood,cwms_msbs,0.662514,0.632165,0.422386,0.598956,0.726071
3,lr,blood,no_cleaning,0.517495,0.468632,0.770000,0.036633,0.998357
4,lr,breast_cancer,cwms_msbs,0.871873,0.860222,0.785630,0.895597,0.848148
5,lr,breast_cancer,no_cleaning,0.799993,0.814921,0.966512,0.612579,0.987407
6,lr,credit-g,cwms_msbs,0.637746,0.620243,0.448364,0.600444,0.675048
7,lr,credit-g,no_cleaning,0.542127,0.501895,0.684853,0.104444,0.979810
8,lr,ecoli,cwms_msbs,0.850121,0.777549,0.560388,0.922807,0.777436
9,lr,ecoli,no_cleaning,0.716694,0.746932,0.948117,0.442105,0.991282
10,lr,glass_float,cwms_msbs,0.662963,0.626935,0.472148,0.729630,0.596296
11,lr,glass_float,no_cleaning,0.513889,0.438520,0.377222,0.044444,0.983333
12,lr,haberman,cwms_msbs,0.597164,0.588779,0.421205,0.430000,0.764327
13,lr,haberman,no_cleaning,0.505570,0.443354,0.231746,0.021667,0.989474
14,lr,ilpd,cwms_msbs,0.594368,0.569779,0.388727,0.554762,0.633974
15,lr,ilpd,no_cleaning,0.498634,0.415969,0.033333,0.000794,0.996474
16,lr,ionosphere,cwms_msbs,0.732143,0.738174,0.725697,0.612500,0.851786
17,lr,ionosphere,no_cleaning,0.703720,0.714464,0.946872,0.422917,0.984524
18,lr,kc1,cwms_msbs,0.700014,0.630508,0.328597,0.647561,0.752466
19,lr,kc1,no_cleaning,0.551242,0.552396,0.658066,0.115041,0.987444
20,lr,phoneme,cwms_msbs,0.748373,0.719530,0.553107,0.755657,0.741089
21,lr,phoneme,no_cleaning,0.513838,0.443778,0.481396,0.031517,0.996158
22,lr,pima,cwms_msbs,0.711268,0.695942,0.574075,0.712935,0.709600
23,lr,pima,no_cleaning,0.541343,0.479015,0.702275,0.096020,0.986667
24,lr,spambase,cwms_msbs,0.864985,0.857811,0.800393,0.881571,0.848398
25,lr,spambase,no_cleaning,0.708305,0.711060,0.946977,0.431865,0.984744
26,lr,vehicle_bus,cwms_msbs,0.890326,0.837284,0.670572,0.963030,0.817622
27,lr,vehicle_bus,no_cleaning,0.760116,0.783892,0.927724,0.532121,0.988110
28,lr,yeast,cwms_msbs,0.749461,0.686137,0.415331,0.706557,0.792366
29,lr,yeast,no_cleaning,0.564892,0.568910,0.666887,0.139891,0.989892
30,svm,abalone,cwms_msbs,0.599565,0.580615,0.775865,0.237765,0.961366
31,svm,abalone,no_cleaning,0.514022,0.426827,0.392044,0.033141,0.994903
32,svm,blood,cwms_msbs,0.530674,0.497890,0.665484,0.080993,0.980356
33,svm,blood,no_cleaning,0.506534,0.446569,0.416667,0.014242,0.998826
34,svm,breast_cancer,cwms_msbs,0.871709,0.885637,0.971295,0.757862,0.985556
35,svm,breast_cancer,no_cleaning,0.789326,0.799540,0.995631,0.580503,0.998148
36,svm,credit-g,cwms_msbs,0.564444,0.553072,0.520957,0.226222,0.902667
37,svm,credit-g,no_cleaning,0.502413,0.418442,0.174603,0.007111,0.997714
38,svm,ecoli,cwms_msbs,0.818677,0.824439,0.765719,0.703509,0.933846
39,svm,ecoli,no_cleaning,0.682119,0.700484,0.791734,0.371930,0.992308
40,svm,glass_float,cwms_msbs,0.590741,0.553122,0.500279,0.264815,0.916667
41,svm,glass_float,no_cleaning,0.507870,0.417705,0.233333,0.018519,0.997222
42,svm,haberman,cwms_msbs,0.528918,0.491993,0.425213,0.090000,0.967836
43,svm,haberman,no_cleaning,0.502997,0.432774,0.072222,0.008333,0.997661
44,svm,ilpd,cwms_msbs,0.513721,0.467067,0.256843,0.096032,0.931410
45,svm,ilpd,no_cleaning,0.500000,0.416000,0.000000,0.000000,1.000000
46,svm,ionosphere,cwms_msbs,0.788318,0.789752,0.885669,0.592708,0.983929
47,svm,ionosphere,no_cleaning,0.665104,0.629675,0.700000,0.330208,1.000000
48,svm,kc1,cwms_msbs,0.595024,0.611808,0.546901,0.227642,0.962407
49,svm,kc1,no_cleaning,0.525706,0.507860,0.566434,0.057317,0.994096
50,svm,phoneme,cwms_msbs,0.699999,0.714864,0.764023,0.461959,0.938040
51,svm,phoneme,no_cleaning,0.538809,0.490145,0.852022,0.080762,0.996856
52,svm,pima,cwms_msbs,0.591934,0.573522,0.698877,0.246269,0.937600
53,svm,pima,no_cleaning,0.514880,0.427221,0.550450,0.034826,0.994933
54,svm,spambase,cwms_msbs,0.824379,0.837957,0.941549,0.676065,0.972692
55,svm,spambase,no_cleaning,0.713829,0.713618,0.974203,0.435022,0.992635
56,svm,vehicle_bus,cwms_msbs,0.917580,0.924671,0.927414,0.860000,0.975159
57,svm,vehicle_bus,no_cleaning,0.714393,0.716858,0.858067,0.430909,0.997877
58,svm,yeast,cwms_msbs,0.712859,0.745459,0.723998,0.461202,0.964516
59,svm,yeast,no_cleaning,0.603354,0.618927,0.748361,0.215847,0.990860

## Comparative Training: LR/SVM COINS vs Other Methods

This compares COINS with every LR/SVM method in the cached full benchmark.

In [6]:
all_metric_cols = ["balanced_accuracy", "macro_f1", "minority_precision", "minority_recall", "majority_recall", "pr_auc"]
display(lr_svm.groupby(["model", "method"])[all_metric_cols].mean().reset_index().sort_values(["model", "balanced_accuracy"], ascending=[True, False]))
display(lr_svm.groupby(["model", "method", "noise_protocol"])[all_metric_cols].mean().reset_index().sort_values(["model", "noise_protocol", "balanced_accuracy"], ascending=[True, True, False]))
display(lr_svm.pivot_table(index=["model", "dataset"], columns="method", values="balanced_accuracy", aggfunc="mean").reset_index().sort_values(["model", "dataset"]))

,model,method,balanced_accuracy,macro_f1,minority_precision,minority_recall,majority_recall,pr_auc
2,lr,cwms_msbs,0.734133,0.704454,0.545171,0.716009,0.752258,0.637694
3,lr,cwms_msbs_shuffled,0.716811,0.704790,0.597786,0.604218,0.829404,0.640702
1,lr,cwms,0.715478,0.711278,0.623656,0.557669,0.873287,0.642490
0,lr,class_proportional,0.702488,0.703100,0.654241,0.489710,0.915265,0.649156
4,lr,msbs,0.648319,0.641836,0.693285,0.335896,0.960741,0.638457
6,lr,smote,0.643809,0.634726,0.704718,0.321399,0.966220,0.640964
5,lr,no_cleaning,0.599602,0.572740,0.682305,0.210305,0.988899,0.644871
9,svm,cwms_msbs,0.676570,0.670124,0.691339,0.398869,0.954270,0.660248
7,svm,class_proportional,0.672893,0.660773,0.664122,0.374155,0.971631,0.641813
10,svm,cwms_msbs_shuffled,0.668310,0.660318,0.691728,0.373638,0.962982,0.656295
13,svm,smote,0.637606,0.621222,0.693814,0.293739,0.981472,0.653516
11,svm,msbs,0.634614,0.614754,0.680165,0.285704,0.983525,0.651105
8,svm,cwms,0.617464,0.589554,0.623445,0.245120,0.989809,0.639011
12,svm,no_cleaning,0.585424,0.544176,0.555051,0.174578,0.996269,0.619706

,model,method,noise_protocol,balanced_accuracy,macro_f1,minority_precision,minority_recall,majority_recall,pr_auc
9,lr,cwms_msbs_shuffled,hidden_minority_high,0.703927,0.668233,0.500339,0.698259,0.709596,0.598208
6,lr,cwms_msbs,hidden_minority_high,0.703146,0.655579,0.470080,0.750133,0.656159,0.598881
3,lr,cwms,hidden_minority_high,0.699229,0.688117,0.563773,0.572244,0.826213,0.606638
0,lr,class_proportional,hidden_minority_high,0.681061,0.680242,0.613631,0.455737,0.906384,0.613283
12,lr,msbs,hidden_minority_high,0.616994,0.604727,0.664936,0.275644,0.958344,0.593035
18,lr,smote,hidden_minority_high,0.610930,0.593859,0.667337,0.256819,0.965042,0.598195
15,lr,no_cleaning,hidden_minority_high,0.567038,0.529361,0.600617,0.145248,0.988827,0.604251
7,lr,cwms_msbs,hidden_minority_low,0.759420,0.739592,0.597973,0.710791,0.808049,0.671736
4,lr,cwms,hidden_minority_low,0.737252,0.736970,0.663842,0.580622,0.893883,0.675243
10,lr,cwms_msbs_shuffled,hidden_minority_low,0.733981,0.734969,0.666427,0.571493,0.896469,0.676797
1,lr,class_proportional,hidden_minority_low,0.724670,0.726378,0.681976,0.535397,0.913944,0.678238
13,lr,msbs,hidden_minority_low,0.684480,0.683669,0.700823,0.414500,0.954460,0.676261
19,lr,smote,hidden_minority_low,0.680852,0.679920,0.724998,0.401653,0.960052,0.679019
16,lr,no_cleaning,hidden_minority_low,0.641290,0.627206,0.753546,0.296813,0.985768,0.680455
8,lr,cwms_msbs,hidden_minority_medium,0.739835,0.718190,0.567461,0.687104,0.792565,0.642466
11,lr,cwms_msbs_shuffled,hidden_minority_medium,0.712524,0.711166,0.626591,0.542901,0.882146,0.647100
5,lr,cwms,hidden_minority_medium,0.709953,0.708748,0.643353,0.520142,0.899764,0.645590
2,lr,class_proportional,hidden_minority_medium,0.701732,0.702680,0.667115,0.477997,0.925467,0.655947
14,lr,msbs,hidden_minority_medium,0.643482,0.637112,0.714096,0.317544,0.969419,0.646074
20,lr,smote,hidden_minority_medium,0.639645,0.630399,0.721820,0.305724,0.973566,0.645678
17,lr,no_cleaning,hidden_minority_medium,0.590478,0.561654,0.692752,0.188855,0.992102,0.649906
27,svm,cwms_msbs,hidden_minority_high,0.654254,0.645893,0.633382,0.372502,0.936006,0.616401
30,svm,cwms_msbs_shuffled,hidden_minority_high,0.652560,0.644720,0.646430,0.360120,0.945001,0.612623
21,svm,class_proportional,hidden_minority_high,0.641512,0.622688,0.609151,0.308116,0.974908,0.599168
39,svm,smote,hidden_minority_high,0.598906,0.573175,0.640750,0.216901,0.980911,0.612390
33,svm,msbs,hidden_minority_high,0.592655,0.562428,0.627388,0.200852,0.984459,0.606498
24,svm,cwms,hidden_minority_high,0.588602,0.555841,0.603970,0.190153,0.987051,0.602208
36,svm,no_cleaning,hidden_minority_high,0.540970,0.484970,0.454651,0.085088,0.996853,0.569903
28,svm,cwms_msbs,hidden_minority_low,0.714526,0.712772,0.721396,0.476424,0.952628,0.698476
22,svm,class_proportional,hidden_minority_low,0.707020,0.703268,0.712869,0.451958,0.962083,0.682994
31,svm,cwms_msbs_shuffled,hidden_minority_low,0.700626,0.697317,0.731262,0.436805,0.964447,0.695945
40,svm,smote,hidden_minority_low,0.684480,0.679731,0.738535,0.392654,0.976306,0.691762
34,svm,msbs,hidden_minority_low,0.683488,0.675262,0.715753,0.390211,0.976765,0.691841
25,svm,cwms,hidden_minority_low,0.661101,0.641958,0.671996,0.334251,0.987951,0.683244
37,svm,no_cleaning,hidden_minority_low,0.640257,0.614016,0.657295,0.286188,0.994326,0.672139
23,svm,class_proportional,hidden_minority_medium,0.670148,0.656364,0.670346,0.362392,0.977903,0.643275
29,svm,cwms_msbs,hidden_minority_medium,0.660929,0.651708,0.719239,0.347683,0.974175,0.665866
32,svm,cwms_msbs_shuffled,hidden_minority_medium,0.651743,0.638917,0.697491,0.323988,0.979498,0.660316
41,svm,smote,hidden_minority_medium,0.629431,0.610761,0.702158,0.271663,0.987200,0.656397
35,svm,msbs,hidden_minority_medium,0.627700,0.606572,0.697352,0.266049,0.989351,0.654975
26,svm,cwms,hidden_minority_medium,0.602690,0.570863,0.594370,0.210955,0.994424,0.631580
38,svm,no_cleaning,hidden_minority_medium,0.575044,0.533543,0.553208,0.152458,0.997629,0.617077

method,model,dataset,class_proportional,cwms,cwms_msbs,cwms_msbs_shuffled,msbs,no_cleaning,smote
0,lr,abalone,0.685868,0.709224,0.738683,0.717644,0.611102,0.556175,0.600832
1,lr,blood,0.583298,0.585354,0.662514,0.615551,0.537425,0.517495,0.533457
2,lr,breast_cancer,0.891978,0.892467,0.871873,0.875405,0.842082,0.799993,0.839605
3,lr,credit-g,0.611841,0.631016,0.637746,0.624476,0.580508,0.542127,0.583746
4,lr,ecoli,0.843360,0.846370,0.850121,0.847665,0.801997,0.716694,0.795533
5,lr,glass_float,0.564815,0.613426,0.662963,0.615278,0.544444,0.513889,0.544444
6,lr,haberman,0.588596,0.577281,0.597164,0.572427,0.516257,0.505570,0.515307
7,lr,ilpd,0.526786,0.541819,0.594368,0.563744,0.506647,0.498634,0.503617
8,lr,ionosphere,0.738914,0.752530,0.732143,0.729836,0.729836,0.703720,0.723363
9,lr,kc1,0.654211,0.675630,0.700014,0.687186,0.592242,0.551242,0.594199
10,lr,phoneme,0.655268,0.697826,0.748373,0.714860,0.563470,0.513838,0.550174
11,lr,pima,0.671879,0.688133,0.711268,0.688100,0.610738,0.541343,0.599839
12,lr,spambase,0.873125,0.867264,0.864985,0.847724,0.780597,0.708305,0.776444
13,lr,vehicle_bus,0.906381,0.905518,0.890326,0.908570,0.860743,0.760116,0.857352
14,lr,yeast,0.740995,0.748311,0.749461,0.743693,0.646690,0.564892,0.639224
15,svm,abalone,0.605198,0.530719,0.599565,0.593200,0.551978,0.514022,0.557294
16,svm,blood,0.533378,0.507943,0.530674,0.527497,0.516425,0.506534,0.516678
17,svm,breast_cancer,0.898620,0.832296,0.871709,0.864385,0.841506,0.789326,0.830370
18,svm,credit-g,0.548317,0.517524,0.564444,0.544095,0.536127,0.502413,0.545968
19,svm,ecoli,0.780297,0.738758,0.818677,0.811269,0.770985,0.682119,0.761741
20,svm,glass_float,0.539815,0.534259,0.590741,0.576852,0.550463,0.507870,0.549074
21,svm,haberman,0.517675,0.506243,0.528918,0.527164,0.507149,0.502997,0.512018
22,svm,ilpd,0.500939,0.501816,0.513721,0.509692,0.501015,0.500000,0.504396
23,svm,ionosphere,0.857961,0.710789,0.788318,0.787351,0.713542,0.665104,0.720685
24,svm,kc1,0.623519,0.541096,0.595024,0.590646,0.555338,0.525706,0.560709
25,svm,phoneme,0.660076,0.574329,0.699999,0.686805,0.613955,0.538809,0.618393
26,svm,pima,0.578651,0.527102,0.591934,0.580691,0.552020,0.514880,0.562919
27,svm,spambase,0.831707,0.764975,0.824379,0.815235,0.784926,0.713829,0.786423
28,svm,vehicle_bus,0.904765,0.816921,0.917580,0.903522,0.846450,0.714393,0.861224
29,svm,yeast,0.712482,0.657195,0.712859,0.706244,0.677337,0.603354,0.676195